// Created by Crowbar 0.71

$modelname "humans/pete/pete_agents.mdl"

$surfaceprop "default"

$jointsurfaceprop "jx_c_delta" ""
$jointsurfaceprop "jx_c_pov" ""
$jointsurfaceprop "jx_c_camera" ""
$jointsurfaceprop "def_c_hip" ""
$jointsurfaceprop "jx_c_start" ""
$jointsurfaceprop "def_c_spineA" ""
$jointsurfaceprop "def_c_spineB" ""
$jointsurfaceprop "def_c_spineC" ""
$jointsurfaceprop "ja_c_propGun" ""
$jointsurfaceprop "def_c_neckA" ""
$jointsurfaceprop "jx_c_neckB" ""
$jointsurfaceprop "def_c_neckB" ""
$jointsurfaceprop "def_c_head" ""
$jointsurfaceprop "def_l_clav" ""
$jointsurfaceprop "def_l_shoulder" ""
$jointsurfaceprop "def_l_shoulderTwist" ""
$jointsurfaceprop "def_l_elbowB" ""
$jointsurfaceprop "def_l_shoulderMid" ""
$jointsurfaceprop "def_l_elbow" ""
$jointsurfaceprop "def_l_forearm" ""
$jointsurfaceprop "def_l_wrist" ""
$jointsurfaceprop "def_l_finIndexA" ""
$jointsurfaceprop "def_l_finIndexB" ""
$jointsurfaceprop "def_l_finIndexC" ""
$jointsurfaceprop "def_l_finMidA" ""
$jointsurfaceprop "def_l_finMidB" ""
$jointsurfaceprop "def_l_finMidC" ""
$jointsurfaceprop "def_l_finThumbA" ""
$jointsurfaceprop "def_l_finThumbB" ""
$jointsurfaceprop "def_l_finThumbC" ""
$jointsurfaceprop "def_l_finRingCarpal" ""
$jointsurfaceprop "def_l_finRingA" ""
$jointsurfaceprop "def_l_finRingB" ""
$jointsurfaceprop "def_l_finRingC" ""
$jointsurfaceprop "def_l_finPinkyA" ""
$jointsurfaceprop "def_l_finPinkyB" ""
$jointsurfaceprop "def_l_finPinkyC" ""
$jointsurfaceprop "def_r_clav" ""
$jointsurfaceprop "def_r_shoulder" ""
$jointsurfaceprop "def_r_shoulderTwist" ""
$jointsurfaceprop "def_r_elbowB" ""
$jointsurfaceprop "def_r_shoulderMid" ""
$jointsurfaceprop "def_r_elbow" ""
$jointsurfaceprop "def_r_forearm" ""
$jointsurfaceprop "def_r_wrist" ""
$jointsurfaceprop "def_r_finIndexA" ""
$jointsurfaceprop "def_r_finIndexB" ""
$jointsurfaceprop "def_r_finIndexC" ""
$jointsurfaceprop "def_r_finMidA" ""
$jointsurfaceprop "def_r_finMidB" ""
$jointsurfaceprop "def_r_finMidC" ""
$jointsurfaceprop "def_r_finThumbA" ""
$jointsurfaceprop "def_r_finThumbB" ""
$jointsurfaceprop "def_r_finThumbC" ""
$jointsurfaceprop "def_r_finRingCarpal" ""
$jointsurfaceprop "def_r_finRingA" ""
$jointsurfaceprop "def_r_finRingB" ""
$jointsurfaceprop "def_r_finRingC" ""
$jointsurfaceprop "def_r_finPinkyA" ""
$jointsurfaceprop "def_r_finPinkyB" ""
$jointsurfaceprop "def_r_finPinkyC" ""
$jointsurfaceprop "def_l_thigh" ""
$jointsurfaceprop "def_l_knee" ""
$jointsurfaceprop "def_l_ankle" ""
$jointsurfaceprop "def_l_ball" ""
$jointsurfaceprop "def_l_kneeB" ""
$jointsurfaceprop "def_r_thigh" ""
$jointsurfaceprop "def_r_knee" ""
$jointsurfaceprop "def_r_ankle" ""
$jointsurfaceprop "def_r_ball" ""
$jointsurfaceprop "def_r_kneeB" ""
$jointsurfaceprop "ja_l_propHand" ""
$jointsurfaceprop "ja_r_propHand" ""
$jointsurfaceprop "def_fc_c_jaw_1" ""
$jointsurfaceprop "def_fc_c_jaw_2" ""
$jointsurfaceprop "def_fc_c_nose_1" ""
$jointsurfaceprop "def_fc_c_nose_2" ""
$jointsurfaceprop "def_fc_c_tongue_1" ""
$jointsurfaceprop "def_fc_c_tongue_2" ""
$jointsurfaceprop "def_fc_c_tongue_3" ""
$jointsurfaceprop "def_fc_l_botlip_1" ""
$jointsurfaceprop "def_fc_l_botlip_2" ""
$jointsurfaceprop "def_fc_l_botlip_3" ""
$jointsurfaceprop "def_fc_l_botlip_4" ""
$jointsurfaceprop "def_fc_l_brow_1" ""
$jointsurfaceprop "def_fc_l_brow_2" ""
$jointsurfaceprop "def_fc_l_brow_3" ""
$jointsurfaceprop "def_fc_l_brow_4" ""
$jointsurfaceprop "def_fc_l_cheek_1" ""
$jointsurfaceprop "def_fc_l_cheek_2" ""
$jointsurfaceprop "def_fc_l_cheek_3" ""
$jointsurfaceprop "def_fc_l_cheek_4" ""
$jointsurfaceprop "def_fc_l_cheek_5" ""
$jointsurfaceprop "def_fc_l_cheek_6" ""
$jointsurfaceprop "def_fc_l_eye_1" ""
$jointsurfaceprop "def_fc_l_eye_2" ""
$jointsurfaceprop "def_fc_l_eye_3" ""
$jointsurfaceprop "def_fc_l_forehead_1" ""
$jointsurfaceprop "def_fc_l_forehead_2" ""
$jointsurfaceprop "def_fc_l_jaw_1" ""
$jointsurfaceprop "def_fc_l_jaw_2" ""
$jointsurfaceprop "def_fc_l_jaw_3" ""
$jointsurfaceprop "def_fc_l_mustache_1" ""
$jointsurfaceprop "def_fc_l_mustache_2" ""
$jointsurfaceprop "def_fc_l_neck_1" ""
$jointsurfaceprop "def_fc_l_neck_2" ""
$jointsurfaceprop "def_fc_l_nose_1" ""
$jointsurfaceprop "def_fc_l_nose_2" ""
$jointsurfaceprop "def_fc_l_nose_3" ""
$jointsurfaceprop "def_fc_l_nose_4" ""
$jointsurfaceprop "def_fc_l_nose_5" ""
$jointsurfaceprop "def_fc_l_toplip_1" ""
$jointsurfaceprop "def_fc_l_toplip_2" ""
$jointsurfaceprop "def_fc_l_toplip_3" ""
$jointsurfaceprop "def_fc_l_toplip_4" ""
$jointsurfaceprop "def_fc_r_botlip_1" ""
$jointsurfaceprop "def_fc_r_botlip_2" ""
$jointsurfaceprop "def_fc_r_botlip_3" ""
$jointsurfaceprop "def_fc_r_botlip_4" ""
$jointsurfaceprop "def_fc_r_brow_1" ""
$jointsurfaceprop "def_fc_r_brow_2" ""
$jointsurfaceprop "def_fc_r_brow_3" ""
$jointsurfaceprop "def_fc_r_brow_4" ""
$jointsurfaceprop "def_fc_r_cheek_1" ""
$jointsurfaceprop "def_fc_r_cheek_2" ""
$jointsurfaceprop "def_fc_r_cheek_3" ""
$jointsurfaceprop "def_fc_r_cheek_4" ""
$jointsurfaceprop "def_fc_r_cheek_5" ""
$jointsurfaceprop "def_fc_r_cheek_6" ""
$jointsurfaceprop "def_fc_r_eye_1" ""
$jointsurfaceprop "def_fc_r_eye_2" ""
$jointsurfaceprop "def_fc_r_eye_3" ""
$jointsurfaceprop "def_fc_r_forehead_1" ""
$jointsurfaceprop "def_fc_r_forehead_2" ""
$jointsurfaceprop "def_fc_r_jaw_1" ""
$jointsurfaceprop "def_fc_r_jaw_2" ""
$jointsurfaceprop "def_fc_r_jaw_3" ""
$jointsurfaceprop "def_fc_r_mustache_1" ""
$jointsurfaceprop "def_fc_r_mustache_2" ""
$jointsurfaceprop "def_fc_r_neck_1" ""
$jointsurfaceprop "def_fc_r_neck_2" ""
$jointsurfaceprop "def_fc_r_nose_1" ""
$jointsurfaceprop "def_fc_r_nose_2" ""
$jointsurfaceprop "def_fc_r_nose_3" ""
$jointsurfaceprop "def_fc_r_nose_4" ""
$jointsurfaceprop "def_fc_r_nose_5" ""
$jointsurfaceprop "def_fc_r_toplip_1" ""
$jointsurfaceprop "def_fc_r_toplip_2" ""
$jointsurfaceprop "def_fc_r_toplip_3" ""
$jointsurfaceprop "def_fc_r_toplip_4" ""
$jointsurfaceprop "def_c_knife" ""

$contents "solid"

$jointcontents "jx_c_delta" "notsolid"
$jointcontents "jx_c_pov" "notsolid"
$jointcontents "jx_c_camera" "notsolid"
$jointcontents "def_c_hip" "notsolid"
$jointcontents "jx_c_start" "notsolid"
$jointcontents "def_c_spineA" "notsolid"
$jointcontents "def_c_spineB" "notsolid"
$jointcontents "def_c_spineC" "notsolid"
$jointcontents "ja_c_propGun" "notsolid"
$jointcontents "def_c_neckA" "notsolid"
$jointcontents "jx_c_neckB" "notsolid"
$jointcontents "def_c_neckB" "notsolid"
$jointcontents "def_c_head" "notsolid"
$jointcontents "def_l_clav" "notsolid"
$jointcontents "def_l_shoulder" "notsolid"
$jointcontents "def_l_shoulderTwist" "notsolid"
$jointcontents "def_l_elbowB" "notsolid"
$jointcontents "def_l_shoulderMid" "notsolid"
$jointcontents "def_l_elbow" "notsolid"
$jointcontents "def_l_forearm" "notsolid"
$jointcontents "def_l_wrist" "notsolid"
$jointcontents "def_l_finIndexA" "notsolid"
$jointcontents "def_l_finIndexB" "notsolid"
$jointcontents "def_l_finIndexC" "notsolid"
$jointcontents "def_l_finMidA" "notsolid"
$jointcontents "def_l_finMidB" "notsolid"
$jointcontents "def_l_finMidC" "notsolid"
$jointcontents "def_l_finThumbA" "notsolid"
$jointcontents "def_l_finThumbB" "notsolid"
$jointcontents "def_l_finThumbC" "notsolid"
$jointcontents "def_l_finRingCarpal" "notsolid"
$jointcontents "def_l_finRingA" "notsolid"
$jointcontents "def_l_finRingB" "notsolid"
$jointcontents "def_l_finRingC" "notsolid"
$jointcontents "def_l_finPinkyA" "notsolid"
$jointcontents "def_l_finPinkyB" "notsolid"
$jointcontents "def_l_finPinkyC" "notsolid"
$jointcontents "def_r_clav" "notsolid"
$jointcontents "def_r_shoulder" "notsolid"
$jointcontents "def_r_shoulderTwist" "notsolid"
$jointcontents "def_r_elbowB" "notsolid"
$jointcontents "def_r_shoulderMid" "notsolid"
$jointcontents "def_r_elbow" "notsolid"
$jointcontents "def_r_forearm" "notsolid"
$jointcontents "def_r_wrist" "notsolid"
$jointcontents "def_r_finIndexA" "notsolid"
$jointcontents "def_r_finIndexB" "notsolid"
$jointcontents "def_r_finIndexC" "notsolid"
$jointcontents "def_r_finMidA" "notsolid"
$jointcontents "def_r_finMidB" "notsolid"
$jointcontents "def_r_finMidC" "notsolid"
$jointcontents "def_r_finThumbA" "notsolid"
$jointcontents "def_r_finThumbB" "notsolid"
$jointcontents "def_r_finThumbC" "notsolid"
$jointcontents "def_r_finRingCarpal" "notsolid"
$jointcontents "def_r_finRingA" "notsolid"
$jointcontents "def_r_finRingB" "notsolid"
$jointcontents "def_r_finRingC" "notsolid"
$jointcontents "def_r_finPinkyA" "notsolid"
$jointcontents "def_r_finPinkyB" "notsolid"
$jointcontents "def_r_finPinkyC" "notsolid"
$jointcontents "def_l_thigh" "notsolid"
$jointcontents "def_l_knee" "notsolid"
$jointcontents "def_l_ankle" "notsolid"
$jointcontents "def_l_ball" "notsolid"
$jointcontents "def_l_kneeB" "notsolid"
$jointcontents "def_r_thigh" "notsolid"
$jointcontents "def_r_knee" "notsolid"
$jointcontents "def_r_ankle" "notsolid"
$jointcontents "def_r_ball" "notsolid"
$jointcontents "def_r_kneeB" "notsolid"
$jointcontents "ja_l_propHand" "notsolid"
$jointcontents "ja_r_propHand" "notsolid"
$jointcontents "def_fc_c_jaw_1" "notsolid"
$jointcontents "def_fc_c_jaw_2" "notsolid"
$jointcontents "def_fc_c_nose_1" "notsolid"
$jointcontents "def_fc_c_nose_2" "notsolid"
$jointcontents "def_fc_c_tongue_1" "notsolid"
$jointcontents "def_fc_c_tongue_2" "notsolid"
$jointcontents "def_fc_c_tongue_3" "notsolid"
$jointcontents "def_fc_l_botlip_1" "notsolid"
$jointcontents "def_fc_l_botlip_2" "notsolid"
$jointcontents "def_fc_l_botlip_3" "notsolid"
$jointcontents "def_fc_l_botlip_4" "notsolid"
$jointcontents "def_fc_l_brow_1" "notsolid"
$jointcontents "def_fc_l_brow_2" "notsolid"
$jointcontents "def_fc_l_brow_3" "notsolid"
$jointcontents "def_fc_l_brow_4" "notsolid"
$jointcontents "def_fc_l_cheek_1" "notsolid"
$jointcontents "def_fc_l_cheek_2" "notsolid"
$jointcontents "def_fc_l_cheek_3" "notsolid"
$jointcontents "def_fc_l_cheek_4" "notsolid"
$jointcontents "def_fc_l_cheek_5" "notsolid"
$jointcontents "def_fc_l_cheek_6" "notsolid"
$jointcontents "def_fc_l_eye_1" "notsolid"
$jointcontents "def_fc_l_eye_2" "notsolid"
$jointcontents "def_fc_l_eye_3" "notsolid"
$jointcontents "def_fc_l_forehead_1" "notsolid"
$jointcontents "def_fc_l_forehead_2" "notsolid"
$jointcontents "def_fc_l_jaw_1" "notsolid"
$jointcontents "def_fc_l_jaw_2" "notsolid"
$jointcontents "def_fc_l_jaw_3" "notsolid"
$jointcontents "def_fc_l_mustache_1" "notsolid"
$jointcontents "def_fc_l_mustache_2" "notsolid"
$jointcontents "def_fc_l_neck_1" "notsolid"
$jointcontents "def_fc_l_neck_2" "notsolid"
$jointcontents "def_fc_l_nose_1" "notsolid"
$jointcontents "def_fc_l_nose_2" "notsolid"
$jointcontents "def_fc_l_nose_3" "notsolid"
$jointcontents "def_fc_l_nose_4" "notsolid"
$jointcontents "def_fc_l_nose_5" "notsolid"
$jointcontents "def_fc_l_toplip_1" "notsolid"
$jointcontents "def_fc_l_toplip_2" "notsolid"
$jointcontents "def_fc_l_toplip_3" "notsolid"
$jointcontents "def_fc_l_toplip_4" "notsolid"
$jointcontents "def_fc_r_botlip_1" "notsolid"
$jointcontents "def_fc_r_botlip_2" "notsolid"
$jointcontents "def_fc_r_botlip_3" "notsolid"
$jointcontents "def_fc_r_botlip_4" "notsolid"
$jointcontents "def_fc_r_brow_1" "notsolid"
$jointcontents "def_fc_r_brow_2" "notsolid"
$jointcontents "def_fc_r_brow_3" "notsolid"
$jointcontents "def_fc_r_brow_4" "notsolid"
$jointcontents "def_fc_r_cheek_1" "notsolid"
$jointcontents "def_fc_r_cheek_2" "notsolid"
$jointcontents "def_fc_r_cheek_3" "notsolid"
$jointcontents "def_fc_r_cheek_4" "notsolid"
$jointcontents "def_fc_r_cheek_5" "notsolid"
$jointcontents "def_fc_r_cheek_6" "notsolid"
$jointcontents "def_fc_r_eye_1" "notsolid"
$jointcontents "def_fc_r_eye_2" "notsolid"
$jointcontents "def_fc_r_eye_3" "notsolid"
$jointcontents "def_fc_r_forehead_1" "notsolid"
$jointcontents "def_fc_r_forehead_2" "notsolid"
$jointcontents "def_fc_r_jaw_1" "notsolid"
$jointcontents "def_fc_r_jaw_2" "notsolid"
$jointcontents "def_fc_r_jaw_3" "notsolid"
$jointcontents "def_fc_r_mustache_1" "notsolid"
$jointcontents "def_fc_r_mustache_2" "notsolid"
$jointcontents "def_fc_r_neck_1" "notsolid"
$jointcontents "def_fc_r_neck_2" "notsolid"
$jointcontents "def_fc_r_nose_1" "notsolid"
$jointcontents "def_fc_r_nose_2" "notsolid"
$jointcontents "def_fc_r_nose_3" "notsolid"
$jointcontents "def_fc_r_nose_4" "notsolid"
$jointcontents "def_fc_r_nose_5" "notsolid"
$jointcontents "def_fc_r_toplip_1" "notsolid"
$jointcontents "def_fc_r_toplip_2" "notsolid"
$jointcontents "def_fc_r_toplip_3" "notsolid"
$jointcontents "def_fc_r_toplip_4" "notsolid"
$jointcontents "def_c_knife" "notsolid"

$illumposition -0.949 2.364 49.799

$eyeposition 0 0 64

$cdmaterials ""

$attachment "OFFSET" "jx_c_delta" 0 0 0 rotate -90 -90 0
$attachment "REF" "jx_c_start" 0 0 0 rotate -90 -90 0
$attachment "HEADFOCUS" "def_c_neckB" 0 0 0 rotate -90 -90 0
$attachment "HEADSHOT" "def_c_head" 0 0 0 rotate -90 -90 0
$attachment "CHESTFOCUS" "def_c_spineC" 0 0 0 rotate -90 -90 0
$attachment "PROPGUN" "ja_c_propGun" 0 0 0 rotate -90 -90 0
$attachment "VDU" "jx_c_camera" 0 0 0 rotate -90 -90 0
$attachment "L_HAND" "ja_l_propHand" 0 0 0 rotate 0 0 0
$attachment "R_HAND" "ja_r_propHand" 0 0 0 rotate 0 0 0
$attachment "ORIGIN" "jx_c_delta" 0 0 0 rotate -90 -90 0
$attachment "foot_L_sole" "def_l_ankle" 0 0 0 rotate 0 0 0
$attachment "foot_R_sole" "def_r_ankle" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -26.792 -32.262 -4.472 22.065 30.364 70.871

$hboxset "default"
$hbox 3 "def_c_hip" -8.487779 -7.432269 -6.419672 8.487779 -0.259842 6.419672 ""
$hbox 2 "def_c_neckA" -5.93109 0.125984 -6.546837 5.93109 3.253537 4.463771 ""
$hbox 1 "def_c_neckB" -4.197236 -3.048813 3.509442 4.197236 6.814553 5.775185 ""
$hbox 1 "def_c_neckB" -5.198021 -1.115746 -5.868098 5.198021 8.319275 4.448023 ""
$hbox 3 "def_c_spineA" -8.098409 0 -6.561404 8.098409 5.59054 6.561404 ""
$hbox 3 "def_c_spineB" -8.098409 0 -6.561404 8.098409 5.55117 6.561404 ""
$hbox 2 "def_c_spineC" -8.45707 -0.112992 -8.436991 8.45707 8.860218 7.276757 ""
$hbox 6 "def_l_ankle" -2.683853 -2.82401 -2.818498 2.607869 2.82401 2.818498 ""
$hbox 6 "def_l_ball" -2.101177 -0.120079 -2.818498 4.225582 3.787788 2.818498 ""
$hbox 4 "def_l_elbow" -2.082673 -3.08149 -1.983461 10.077932 3.08149 1.983461 ""
$hbox 6 "def_l_knee" 0 -4.383456 -3.50393 17.311777 4.383456 3.50393 ""
$hbox 4 "def_l_shoulder" -1.976768 -3.457867 -2.64094 11.110608 3.457867 2.64094 ""
$hbox 6 "def_l_thigh" 0 -4.23385 -3.842906 18.172012 5.373218 3.842906 ""
$hbox 4 "def_l_wrist" -0.281102 -1.56732 -1.558658 4.255109 0.825983 1.862201 ""
$hbox 7 "def_r_ankle" -2.607869 -2.82401 -2.818498 2.683853 2.82401 2.818498 ""
$hbox 7 "def_r_ball" -4.225582 -3.804323 -2.818498 2.101177 0.103543 2.818498 ""
$hbox 5 "def_r_elbow" -10.078327 -3.08149 -1.983461 2.082673 3.081884 1.983461 ""
$hbox 7 "def_r_knee" -17.311777 -4.383456 -3.50393 0 4.383456 3.50393 ""
$hbox 5 "def_r_shoulder" -11.100765 -3.457867 -2.64094 1.986217 3.457867 2.64094 ""
$hbox 7 "def_r_thigh" -18.172012 -5.373218 -3.842906 0 4.23385 3.842906 ""
$hbox 5 "def_r_wrist" -4.255503 -0.825983 -1.862201 0.281102 1.567713 1.558658 ""
$hbox 1 "def_c_head" -2.389365 -6.197625 0.915353 2.389365 -0.738975 4.97125 ""
$hbox 1 "def_c_head" -2.191334 -1.288186 3.938969 2.191334 2.88149 6.08109 ""
$hbox 1 "def_c_head" -2.443696 -3.336608 -5.300383 2.443696 2.54842 -3.845268 ""
$hbox 1 "def_c_head" -2.804325 1.687792 -2.713381 2.804325 4.177157 3.911803 ""
$hbox 1 "def_c_head" -3.917709 -3.348025 -3.852355 3.917709 2.550782 3.933457 ""
$hbox 1 "def_c_head" -2.069287 -6.102744 4.963376 2.069287 -2.68779 6.2055 ""
$hbox 2 "def_c_neckA" -3.599599 0.33307 -4.669676 3.599599 4.963769 3.804717 ""
$hbox 2 "def_c_spineC" -7.513371 0.003543 -6.315342 7.513371 8.838566 6.079122 ""
$hbox 3 "def_c_hip" -7.513371 -7.049199 -6.197232 7.513371 0.000394 6.197232 ""
$hbox 3 "def_c_spineA" -7.513371 0 -6.197232 7.513371 5.59054 6.197232 ""
$hbox 3 "def_c_spineB" -7.513371 0 -6.197232 7.513371 5.55117 6.197232 ""
$hbox 4 "def_l_shoulder" -2.066138 -2.014563 -2.835034 11.231867 2.014563 2.835034 ""
$hbox 4 "def_l_elbow" -1.651965 -1.791335 -1.64606 9.750375 1.791335 1.64606 ""
$hbox 4 "def_l_wrist" -0.291732 -1.342123 -1.670075 3.675583 0.581495 1.894484 ""
$hbox 5 "def_r_shoulder" -11.215726 -2.014563 -2.835034 2.081886 2.014563 2.835034 ""
$hbox 5 "def_r_elbow" -9.74998 -1.791335 -1.64606 1.651965 1.791335 1.64606 ""
$hbox 5 "def_r_wrist" -3.675583 -0.581495 -1.894484 0.291732 1.342123 1.670075 ""
$hbox 6 "def_l_thigh" 0 -2.208657 -3.148813 18.097996 4.371645 3.148813 ""
$hbox 6 "def_l_knee" 0 -2.686215 -3.148813 17.311777 2.686215 3.148813 ""
$hbox 6 "def_l_ankle" -2.103145 -1.918107 -2.531885 3.188576 1.918107 2.531885 ""
$hbox 6 "def_l_ball" -1.637005 -0.124016 -2.520074 3.419285 2.612987 2.520074 ""
$hbox 7 "def_r_thigh" -18.097996 -4.371251 -3.148813 0 2.208657 3.148813 ""
$hbox 7 "def_r_knee" -17.311777 -2.686215 -3.148813 0 2.686215 3.148813 ""
$hbox 7 "def_r_ankle" -3.188576 -1.918107 -2.531885 2.103145 1.918107 2.531885 ""
$hbox 7 "def_r_ball" -3.418891 -2.615349 -2.520074 1.636611 0.121653 2.520074 ""
$hbox 1 "def_c_head" -2.389365 -6.197625 0.915353 2.389365 -0.738975 4.97125 ""
$hbox 1 "def_c_head" -2.191334 -1.288186 3.938969 2.191334 2.88149 6.08109 ""
$hbox 1 "def_c_head" -2.443696 -3.336608 -5.300383 2.443696 2.54842 -3.845268 ""
$hbox 1 "def_c_head" -2.804325 1.687792 -2.713381 2.804325 4.177157 3.911803 ""
$hbox 1 "def_c_head" -3.917315 -3.350387 -5.350383 3.917315 2.551176 5.43306 ""
$hbox 1 "def_c_head" -2.069287 -6.102744 4.963376 2.069287 -2.68779 6.2055 ""
$hbox 1 "def_c_head" -3.598418 -7.515733 -6.2992 3.598418 -2.885821 2.299208 ""
$hbox 2 "def_c_spineC" -7.511796 -0.496062 -6.314949 7.511796 7.338568 6.078728 ""
$hbox 3 "def_c_hip" -7.513371 -7.049199 -6.197232 7.513371 0.000394 6.197232 ""
$hbox 3 "def_c_spineA" -7.513371 0 -6.197232 7.513371 5.59054 6.197232 ""
$hbox 3 "def_c_spineB" -7.513371 0 -6.197232 7.513371 5.55117 6.197232 ""
$hbox 4 "def_l_shoulder" -2.066138 -2.014563 -2.835034 11.231867 2.014563 2.835034 ""
$hbox 4 "def_l_elbow" -1.651965 -1.791335 -1.64606 9.750375 1.791335 1.64606 ""
$hbox 4 "def_l_wrist" -0.291732 -1.342123 -1.670075 3.675583 0.581495 1.894484 ""
$hbox 5 "def_r_shoulder" -11.215726 -2.014563 -2.835034 2.081886 2.014563 2.835034 ""
$hbox 5 "def_r_elbow" -9.74998 -1.791335 -1.64606 1.651965 1.791335 1.64606 ""
$hbox 5 "def_r_wrist" -3.675583 -0.581495 -1.894484 0.291732 1.342123 1.670075 ""
$hbox 6 "def_l_thigh" 0 -2.208657 -3.148813 18.097996 4.371645 3.148813 ""
$hbox 6 "def_l_knee" 0 -2.686215 -3.148813 17.311777 2.686215 3.148813 ""
$hbox 6 "def_l_ankle" -2.103145 -1.918107 -2.531885 3.188576 1.918107 2.531885 ""
$hbox 6 "def_l_ball" -1.637005 -0.124016 -2.520074 3.419285 2.612987 2.520074 ""
$hbox 7 "def_r_thigh" -18.097996 -4.371251 -3.148813 0 2.208657 3.148813 ""
$hbox 7 "def_r_knee" -17.311777 -2.686215 -3.148813 0 2.686215 3.148813 ""
$hbox 7 "def_r_ankle" -3.188576 -1.918107 -2.531885 2.103145 1.918107 2.531885 ""
$hbox 7 "def_r_ball" -3.418891 -2.615349 -2.520074 1.636611 0.121653 2.520074 ""
$hbox 1 "def_c_head" -3.982669 -3.10708 -5.731091 3.982669 6.545656 4.677943 ""
$hbox 2 "def_c_neckA" -2.537003 -0.029134 -2.432672 2.537003 1.337005 3.101568 ""
$hbox 2 "def_c_spineC" -6.705893 0 -5.230305 6.705893 9.785808 5.049202 ""
$hbox 3 "def_c_hip" -7.545654 -3.373222 -5.146446 7.545654 0.889368 5.146446 ""
$hbox 3 "def_c_spineA" -6.924789 0 -5.146446 6.924789 7.326757 5.146446 ""
$hbox 3 "def_c_spineB" -6.705893 0 -5.104714 6.705893 5.08503 5.104714 ""
$hbox 4 "def_l_shoulder" -1.968894 -1.592517 -1.661808 11.015332 1.592517 1.661808 ""
$hbox 4 "def_l_elbow" 0 -1.592517 -1.670469 8.980691 1.592517 1.653146 ""
$hbox 4 "def_l_wrist" -0.312598 -1.597241 -1.648816 5.555107 0.635826 1.704327 ""
$hbox 5 "def_r_shoulder" -10.927931 -1.592517 -1.661808 2.056295 1.592517 1.661808 ""
$hbox 5 "def_r_elbow" -8.980297 -1.592517 -1.653146 0 1.592123 1.670469 ""
$hbox 5 "def_r_wrist" -5.555501 -0.635826 -1.704327 0.312991 1.597635 1.648422 ""
$hbox 6 "def_l_thigh" 0 -3.081884 -2.94527 15.393669 3.081884 2.94527 ""
$hbox 6 "def_l_knee" 0 -2.875585 -3.064955 16.67477 2.875585 3.064955 ""
$hbox 6 "def_l_ankle" -2.515743 -2.058657 -1.977555 3.28897 2.058657 1.977555 ""
$hbox 6 "def_l_ball" -1.376769 -0.181889 -1.977555 3.501174 3.935031 1.977555 ""
$hbox 7 "def_r_thigh" -15.393669 -3.081884 -2.94527 0 3.081884 2.94527 ""
$hbox 7 "def_r_knee" -16.67477 -2.875585 -3.064955 0 2.875585 3.064955 ""
$hbox 7 "def_r_ankle" -3.28897 -2.058657 -1.977555 2.515743 2.058657 1.977555 ""
$hbox 7 "def_r_ball" -3.501174 -3.938181 -1.977555 1.376769 0.179134 1.977555 ""
$hboxset "default"
$hbox 3 "def_c_hip" -8.24644 -7.823213 -6.693688 8.24644 0.085433 6.693688 ""
$hbox 2 "def_c_neckA" -3.961016 0.075984 -3.683457 3.961016 3.80078 4.722826 ""
$hbox 1 "def_c_neckB" -3.576371 -1.004329 -7.018096 3.576371 5.824398 8.120063 ""
$hbox 3 "def_c_spineA" -8.389354 0 -6.687388 8.389354 6.149594 6.687388 ""
$hbox 3 "def_c_spineB" -8.389354 0 -6.687388 8.389354 6.106287 6.687388 ""
$hbox 2 "def_c_spineC" -8.725574 0.118897 -6.686995 8.725574 9.777539 6.686995 ""
$hbox 6 "def_l_ankle" -1.201966 -2.641333 -2.641333 7.023608 2.641333 2.641333 ""
$hbox 6 "def_l_ball" -3.191332 -2.660231 -2.660231 5.527942 2.660231 2.660231 ""
$hbox 4 "def_l_elbow" -3.894874 -1.635824 -1.635824 10.914545 1.635824 1.635824 ""
$hbox 6 "def_l_knee" 0.392519 -3.368891 -3.368891 18.649961 3.368891 3.368891 ""
$hbox 4 "def_l_shoulder" -2.76968 -2.424798 -2.424798 12.63462 2.424798 2.424798 ""
$hbox 6 "def_l_thigh" -0.684251 -1.917319 -4.054323 20.673582 3.170466 4.054323 ""
$hbox 4 "def_l_wrist" -0.598424 -1.367714 -1.755508 4.02322 0.551967 2.089366 ""
$hbox 7 "def_r_ankle" -7.023608 -2.641333 -2.641333 1.201966 2.641333 2.641333 ""
$hbox 7 "def_r_ball" -5.527942 -2.660231 -2.660231 3.191332 2.660231 2.660231 ""
$hbox 5 "def_r_elbow" -10.914545 -1.635824 -1.635824 3.894874 1.635824 1.635824 ""
$hbox 7 "def_r_knee" -18.649961 -3.368891 -3.368891 -0.392519 3.368891 3.368891 ""
$hbox 5 "def_r_shoulder" -12.623203 -2.424798 -2.424798 2.780703 2.424798 2.424798 ""
$hbox 7 "def_r_thigh" -20.673582 -3.170466 -4.054323 0.684251 1.917319 4.054323 ""
$hbox 5 "def_r_wrist" -4.023614 -0.551967 -2.089366 0.598424 1.368107 1.755508 ""
$hbox 8 "def_c_spineC" -5.62676 -4.834636 -12.27281 5.62676 6.736994 -6.911404 ""
$skipboneinbbox

$screenalign def_l_clav "sphere"
$screenalign def_l_shoulderTwist "sphere"
$screenalign def_l_elbowB "sphere"
$screenalign def_l_shoulderMid "sphere"
$screenalign def_l_elbow "cylinder"
$screenalign def_l_wrist "sphere"
$screenalign def_l_finIndexA "cylinder"
$screenalign def_l_finIndexB "sphere"
$screenalign def_l_finMidA "sphere"
$screenalign def_l_finMidB "cylinder"
$screenalign def_l_finMidC "cylinder"
$screenalign def_l_finThumbA "cylinder"
$screenalign def_l_finThumbC "sphere"
$screenalign def_l_finRingCarpal "sphere"
$screenalign def_l_finRingB "sphere"
$screenalign def_l_finRingC "sphere"
$screenalign def_l_finPinkyA "cylinder"
$screenalign def_l_finPinkyB "cylinder"
$screenalign def_l_finPinkyC "cylinder"
$screenalign def_r_clav "sphere"
$screenalign def_r_shoulderMid "sphere"
$screenalign def_r_elbow "sphere"
$screenalign def_r_wrist "sphere"
$screenalign def_r_finIndexA "sphere"
$screenalign def_r_finIndexB "sphere"
$screenalign def_r_finIndexC "cylinder"
$screenalign def_r_finMidA "sphere"
$screenalign def_r_finMidB "sphere"
$screenalign def_r_finMidC "sphere"
$screenalign def_r_finThumbA "cylinder"
$screenalign def_r_finThumbC "cylinder"
$screenalign def_r_finRingCarpal "cylinder"
$screenalign def_r_finRingA "sphere"
$screenalign def_r_finPinkyA "sphere"
$screenalign def_r_finPinkyB "sphere"
$screenalign def_r_finPinkyC "sphere"
$screenalign def_l_thigh "sphere"
$screenalign def_l_knee "sphere"
$screenalign def_l_ankle "sphere"
$screenalign def_l_ball "sphere"
$screenalign def_l_kneeB "sphere"
$screenalign def_r_thigh "sphere"
$screenalign def_r_ankle "cylinder"
$screenalign def_r_kneeB "sphere"
$screenalign ja_l_propHand "cylinder"
$screenalign ja_r_propHand "sphere"
$screenalign def_c_knife "sphere"

$definebone "jx_c_delta" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_pov" "jx_c_delta" 0 62.992001 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_camera" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hip" "jx_c_delta" 0 39.369999 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_start" "jx_c_delta" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineA" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineB" "def_c_spineA" 0 5.590542 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineC" "def_c_spineB" 0 5.55117 0 0 0 0 0 0 0 0 0 0
$definebone "ja_c_propGun" "def_c_spineC" 0 -7.204712 9.8425 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckA" "def_c_spineC" 0 8.503922 -0.23622 0 0 0 0 0 0 0 0 0
$definebone "jx_c_neckB" "def_c_neckA" 0 4.370071 0.94488 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckB" "jx_c_neckB" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_head" "def_c_neckB" 0 3.936996 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_clav" "def_c_spineC" 1.176218 6.023808 -0.588109 6.983374 3.661928 0.44582 0 0 0 0 0 0
$definebone "def_l_shoulder" "def_l_clav" 5.448854 0.000011 0 -4.860232 -48.915267 4.890265 0 0 0 0 0 0
$definebone "def_l_shoulderTwist" "def_l_shoulder" 0 0 0 0 0.000002 0 0 0 0 0 0 0
$definebone "def_l_elbowB" "def_l_shoulder" 11.630213 -0.000008 0.000027 -44.997331 -0.027096 0.877916 0 0 0 0 0 0
$definebone "def_l_shoulderMid" "def_l_shoulder" 4.890762 0.000004 0 -2.688722 -0.057131 0.006099 0 0 0 0 0 0
$definebone "def_l_elbow" "def_l_shoulderMid" 6.444214 -0.000004 0 -37.014561 0.164812 0.006865 0 0 0 0 0 0
$definebone "def_l_forearm" "def_l_elbow" 4.63045 0.000011 0.000002 -5.291108 -0.116958 0.007797 0 0 0 0 0 0
$definebone "def_l_wrist" "def_l_elbow" 9.956749 -0.010864 0.493276 -5.403714 -0.039456 -0.000075 0 0 0 0 0 0
$definebone "def_l_finIndexA" "def_l_wrist" 3.077315 -0.138939 1.24732 -3.532782 -45.109219 3.539624 0 0 0 0 0 0
$definebone "def_l_finIndexB" "def_l_finIndexA" 1.748371 0 0.000002 -0.001187 -45.000005 0.001192 0 0 0 0 0 0
$definebone "def_l_finIndexC" "def_l_finIndexB" 1.19545 -0.000003 0.000002 0.000615 -45.000008 -0.000614 0 0 0 0 0 0
$definebone "def_l_finMidA" "def_l_wrist" 3.080781 -0.067951 0.349253 6.351203 -45.354918 -6.390478 0 0 0 0 0 0
$definebone "def_l_finMidB" "def_l_finMidA" 1.836349 0.000002 0.000002 0.000002 -45.000005 0.000002 0 0 0 0 0 0
$definebone "def_l_finMidC" "def_l_finMidB" 1.309196 -0.000001 0.000008 -0.002988 -45.000008 0.00298 0 0 0 0 0 0
$definebone "def_l_finThumbA" "def_l_wrist" 0.504171 -0.563503 0.770155 -42.349748 -57.483275 126.990511 0 0 0 0 0 0
$definebone "def_l_finThumbB" "def_l_finThumbA" 2.132282 0.000006 0.000004 3.259416 -22.647167 2.460338 0 0 0 0 0 0
$definebone "def_l_finThumbC" "def_l_finThumbB" 1.240841 -0.000003 0 0.074487 -45.185656 0.008913 0 0 0 0 0 0
$definebone "def_l_finRingCarpal" "def_l_wrist" 2.513066 -0.138184 -0.333538 17.995868 0.000025 0.000075 0 0 0 0 0 0
$definebone "def_l_finRingA" "def_l_finRingCarpal" 0.316793 0.000004 -0.000001 0.003163 -44.999994 -0.003168 0 0 0 0 0 0
$definebone "def_l_finRingB" "def_l_finRingA" 1.966316 0.000002 -0.000002 0.000002 -45.000001 0.000001 0 0 0 0 0 0
$definebone "def_l_finRingC" "def_l_finRingB" 1.00687 0.000001 0.000008 0.000598 -45.000008 -0.000594 0 0 0 0 0 0
$definebone "def_l_finPinkyA" "def_l_finRingCarpal" -0.030562 -0.172359 -0.590865 18.727351 -48.299806 -19.816788 0 0 0 0 0 0
$definebone "def_l_finPinkyB" "def_l_finPinkyA" 1.644444 -0.000002 0 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_l_finPinkyC" "def_l_finPinkyB" 0.763287 -0.000002 0 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_r_clav" "def_c_spineC" -1.176218 6.024002 -0.588109 -6.983374 -3.661928 -179.554171 0 0 0 0 0 0
$definebone "def_r_shoulder" "def_r_clav" -5.448845 0.000145 0 -4.860235 -48.915264 4.890268 0 0 0 0 0 0
$definebone "def_r_shoulderTwist" "def_r_shoulder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_elbowB" "def_r_shoulder" -11.630196 0.000011 -0.000028 -44.997327 -0.027091 0.877916 0 0 0 0 0 0
$definebone "def_r_shoulderMid" "def_r_shoulder" -4.890709 -0.000069 -0.000002 -2.688722 -0.057138 0.006099 0 0 0 0 0 0
$definebone "def_r_elbow" "def_r_shoulderMid" -6.444286 0.00013 0.000005 -37.014561 0.164812 0.006865 0 0 0 0 0 0
$definebone "def_r_forearm" "def_r_elbow" -4.630386 -0.000137 -0.000053 -5.291104 -0.116958 0.007796 0 0 0 0 0 0
$definebone "def_r_wrist" "def_r_elbow" -9.956816 0.010937 -0.493216 -5.403711 -0.039457 -0.000077 0 0 0 0 0 0
$definebone "def_r_finIndexA" "def_r_wrist" -3.077376 0.138977 -1.247286 -3.532781 -45.109219 3.539621 0 0 0 0 0 0
$definebone "def_r_finIndexB" "def_r_finIndexA" -1.748192 0.000002 -0.000114 -0.001197 -45.000001 0.001184 0 0 0 0 0 0
$definebone "def_r_finIndexC" "def_r_finIndexB" -1.195347 0.00008 -0.000078 0.000611 -45.000005 -0.000613 0 0 0 0 0 0
$definebone "def_r_finMidA" "def_r_wrist" -3.08066 0.067764 -0.349348 6.351203 -45.354908 -6.390478 0 0 0 0 0 0
$definebone "def_r_finMidB" "def_r_finMidA" -1.836304 -0.000002 -0.00005 -0.000003 -44.999994 0.000005 0 0 0 0 0 0
$definebone "def_r_finMidC" "def_r_finMidB" -1.309258 -0.000061 0.000052 -0.002987 -45.000008 0.002984 0 0 0 0 0 0
$definebone "def_r_finThumbA" "def_r_wrist" -0.504133 0.563412 -0.770212 -42.349741 -57.483255 126.990511 0 0 0 0 0 0
$definebone "def_r_finThumbB" "def_r_finThumbA" -2.132332 0.000069 -0.00008 3.25942 -22.647166 2.460342 0 0 0 0 0 0
$definebone "def_r_finThumbC" "def_r_finThumbB" -1.240768 -0.000023 0.00005 0.074482 -45.185656 0.008905 0 0 0 0 0 0
$definebone "def_r_finRingCarpal" "def_r_wrist" -2.513052 0.138145 0.333541 17.995867 0.000031 0.000083 0 0 0 0 0 0
$definebone "def_r_finRingA" "def_r_finRingCarpal" -0.316674 -0.000145 -0.000084 0.003161 -45.000001 -0.003161 0 0 0 0 0 0
$definebone "def_r_finRingB" "def_r_finRingA" -1.966396 0.000031 0.000019 0.000002 -45.000005 0.000004 0 0 0 0 0 0
$definebone "def_r_finRingC" "def_r_finRingB" -1.006874 -0.000014 -0.000002 0.000599 -45.000005 -0.000595 0 0 0 0 0 0
$definebone "def_r_finPinkyA" "def_r_finRingCarpal" 0.030523 0.172421 0.590875 18.727346 -48.299795 -19.816788 0 0 0 0 0 0
$definebone "def_r_finPinkyB" "def_r_finPinkyA" -1.644104 -0.000021 0.00001 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_r_finPinkyC" "def_r_finPinkyB" -0.763535 -0.000238 -0.000006 0 -45.000001 0 0 0 0 0 0 0
$definebone "def_l_thigh" "def_c_hip" 5.219006 -1.00618 -0.600196 -0.050695 -90.000003 90.000003 0 0 0 0 0 0
$definebone "def_l_knee" "def_l_thigh" 18.098003 0 0 0 -3.72269 0 0 0 0 0 0 0
$definebone "def_l_ankle" "def_l_knee" 17.311804 0 0 -3.795738 61.268573 0 0 0 0 0 0 0
$definebone "def_l_ball" "def_l_ankle" 5.292377 0 0 0.427673 29.592491 1.875762 0 0 0 0 0 0
$definebone "def_l_kneeB" "def_l_thigh" 18.246761 1.130153 0 0 -7.498168 0 0 0 0 0 0 0
$definebone "def_r_thigh" "def_c_hip" -5.219006 -1.00618 -0.600196 0.050695 90.000003 -90.000003 0 0 0 0 0 0
$definebone "def_r_knee" "def_r_thigh" -18.098003 0 0 0 -3.72269 0 0 0 0 0 0 0
$definebone "def_r_ankle" "def_r_knee" -17.311804 0 0 -3.795738 61.268573 0 0 0 0 0 0 0
$definebone "def_r_ball" "def_r_ankle" -5.292377 0 0 0.427673 29.592491 1.875761 0 0 0 0 0 0
$definebone "def_r_kneeB" "def_r_thigh" -18.246761 -1.130153 0 0 -7.498168 -0.000001 0 0 0 0 0 0
$definebone "ja_l_propHand" "def_l_wrist" 4.441361 -1.883156 0.77133 0.000002 0 -0.000002 0 0 0 0 0 0
$definebone "ja_r_propHand" "def_r_wrist" -4.441751 1.88372 -0.770998 0.000002 0 0.000003 0 0 0 0 0 0
$definebone "def_fc_c_jaw_1" "def_c_head" 0.000008 -3.528931 1.714772 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_jaw_2" "def_c_head" -0.002348 -5.904533 4.421052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_nose_1" "def_c_head" -0.000222 -1.906204 5.126512 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_nose_2" "def_c_head" -0.000014 -2.56337 5.497591 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_1" "def_c_head" 0.000008 -3.896217 1.86384 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_2" "def_c_head" 0.000008 -3.781494 3.033485 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_3" "def_c_head" 0.000008 -4.107208 4.160108 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_1" "def_c_head" 0.187538 -4.486393 4.876977 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_2" "def_c_head" 0.714897 -4.453117 4.719345 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_3" "def_c_head" 1.01442 -4.33876 4.225265 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_4" "def_c_head" 1.217984 -5.240444 4.107803 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_1" "def_c_head" 0.316672 -0.401428 4.700243 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_2" "def_c_head" 0.729493 -0.26873 4.664347 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_3" "def_c_head" 1.52846 -0.217766 4.366918 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_4" "def_c_head" 2.391509 -0.44352 3.275908 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_1" "def_c_head" 0.281779 -1.435074 4.650091 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_2" "def_c_head" 0.554045 -1.595055 4.504138 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_3" "def_c_head" 1.314057 -2.258446 4.347957 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_4" "def_c_head" 1.849152 -2.377121 4.039434 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_5" "def_c_head" 2.300972 -1.677475 3.350968 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_6" "def_c_head" 2.839564 -1.334602 2.411699 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_1" "def_c_head" 1.26353 -1.073029 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_2" "def_c_head" 1.26353 -1.073418 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_3" "def_c_head" 1.26353 -1.073814 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_forehead_1" "def_c_head" 0.565769 0.634354 4.519776 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_forehead_2" "def_c_head" 1.638682 1.018105 3.771194 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_1" "def_c_head" 2.086407 -3.40559 3.642359 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_2" "def_c_head" 2.6396 -2.433846 0.748599 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_3" "def_c_head" 3.312682 -1.020157 -0.649023 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_mustache_1" "def_c_head" 0.295735 -3.25177 4.951944 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_mustache_2" "def_c_head" 0.865967 -3.347313 4.613052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_neck_1" "def_c_head" 0.508073 -7.319633 1.372036 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_neck_2" "def_c_head" 1.413078 -5.992386 1.191715 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_1" "def_c_head" 0.812187 -2.579361 4.895335 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_2" "def_c_head" 0.662534 -2.266006 4.638642 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_3" "def_c_head" 1.249506 -2.995415 4.387953 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_4" "def_c_head" 1.564873 -3.679466 4.16363 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_5" "def_c_head" 1.514009 -4.425018 4.054327 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_1" "def_c_head" 0.224988 -3.668037 5.156847 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_2" "def_c_head" 0.731265 -3.800255 4.86531 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_3" "def_c_head" 1.048409 -3.885151 4.371408 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_4" "def_c_head" 1.217984 -4.143848 4.08142 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_1" "def_c_head" -0.187538 -4.486393 4.876977 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_2" "def_c_head" -0.714897 -4.453117 4.719345 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_3" "def_c_head" -1.01442 -4.33876 4.225265 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_4" "def_c_head" -1.217984 -5.240444 4.107803 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_1" "def_c_head" -0.316672 -0.401428 4.700243 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_2" "def_c_head" -0.729493 -0.26873 4.664347 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_3" "def_c_head" -1.52846 -0.217766 4.366918 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_4" "def_c_head" -2.391509 -0.44352 3.275908 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_1" "def_c_head" -0.281779 -1.435074 4.650091 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_2" "def_c_head" -0.554045 -1.595055 4.504138 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_3" "def_c_head" -1.314057 -2.258446 4.347957 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_4" "def_c_head" -1.849152 -2.377121 4.039434 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_5" "def_c_head" -2.300972 -1.677475 3.350968 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_6" "def_c_head" -2.839564 -1.334602 2.411699 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_1" "def_c_head" -1.26353 -1.073029 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_2" "def_c_head" -1.26353 -1.073418 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_3" "def_c_head" -1.26353 -1.073814 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_forehead_1" "def_c_head" -0.565769 0.634354 4.519776 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_forehead_2" "def_c_head" -1.638682 1.018105 3.771194 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_1" "def_c_head" -2.086407 -3.40559 3.642359 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_2" "def_c_head" -2.6396 -2.433846 0.748599 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_3" "def_c_head" -3.312682 -1.020157 -0.649023 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_mustache_1" "def_c_head" -0.295735 -3.25177 4.951944 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_mustache_2" "def_c_head" -0.865967 -3.347313 4.613052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_neck_1" "def_c_head" -0.508073 -7.319633 1.372036 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_neck_2" "def_c_head" -1.413078 -5.992386 1.191715 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_1" "def_c_head" -0.812187 -2.579361 4.895335 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_2" "def_c_head" -0.662534 -2.266006 4.638642 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_3" "def_c_head" -1.249506 -2.995415 4.387953 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_4" "def_c_head" -1.564873 -3.679466 4.16363 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_5" "def_c_head" -1.514009 -4.425018 4.054327 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_1" "def_c_head" -0.224988 -3.668037 5.156847 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_2" "def_c_head" -0.731265 -3.800255 4.86531 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_3" "def_c_head" -1.048409 -3.885151 4.371408 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_4" "def_c_head" -1.217984 -4.143848 4.08142 0 0 0 0 0 0 0 0 0
$definebone "def_c_knife" "def_c_spineC" 0 0 0 -89.999975 -90.000003 0 0 0 0 0 0 0

$bonemerge "def_l_clav"
$bonemerge "def_l_shoulder"
$bonemerge "def_l_shoulderTwist"
$bonemerge "def_l_elbowB"
$bonemerge "def_l_shoulderMid"
$bonemerge "def_l_elbow"
$bonemerge "def_l_forearm"
$bonemerge "def_l_wrist"
$bonemerge "def_l_finIndexA"
$bonemerge "def_l_finIndexB"
$bonemerge "def_l_finIndexC"
$bonemerge "def_l_finMidA"
$bonemerge "def_l_finMidB"
$bonemerge "def_l_finMidC"
$bonemerge "def_l_finRingCarpal"
$bonemerge "def_l_finRingA"
$bonemerge "def_l_finRingB"
$bonemerge "def_l_finRingC"
$bonemerge "def_l_finPinkyA"
$bonemerge "def_l_finPinkyB"
$bonemerge "def_l_finPinkyC"
$bonemerge "def_r_clav"
$bonemerge "def_r_shoulder"
$bonemerge "def_r_shoulderTwist"
$bonemerge "def_r_elbowB"
$bonemerge "def_r_shoulderMid"
$bonemerge "def_r_elbow"
$bonemerge "def_r_forearm"
$bonemerge "def_r_wrist"
$bonemerge "def_r_finIndexA"
$bonemerge "def_r_finIndexB"
$bonemerge "def_r_finIndexC"
$bonemerge "def_r_finMidA"
$bonemerge "def_r_finMidB"
$bonemerge "def_r_finMidC"
$bonemerge "def_r_finRingCarpal"
$bonemerge "def_r_finRingA"
$bonemerge "def_r_finRingB"
$bonemerge "def_r_finRingC"
$bonemerge "def_r_finPinkyA"
$bonemerge "def_r_finPinkyB"
$bonemerge "def_r_finPinkyC"
$bonemerge "def_l_ankle"
$bonemerge "def_l_ball"
$bonemerge "def_r_ankle"
$bonemerge "def_r_ball"
$bonemerge "ja_l_propHand"
$bonemerge "ja_r_propHand"
$bonemerge "def_c_knife"


$bonesaveframe "def_l_clav" position rotation
$bonesaveframe "def_l_shoulder" position rotation
$bonesaveframe "def_l_shoulderTwist" position rotation
$bonesaveframe "def_l_elbowB" position
$bonesaveframe "def_l_shoulderMid" position rotation
$bonesaveframe "def_l_elbow" rotation
$bonesaveframe "def_l_forearm" position
$bonesaveframe "def_l_wrist" position
$bonesaveframe "def_l_finIndexA" position
$bonesaveframe "def_l_finIndexB" position
$bonesaveframe "def_l_finIndexC" position
$bonesaveframe "def_l_finMidA" rotation
$bonesaveframe "def_l_finMidB" rotation
$bonesaveframe "def_l_finMidC" rotation
$bonesaveframe "def_l_finThumbA" position
$bonesaveframe "def_l_finRingCarpal" position rotation
$bonesaveframe "def_l_finRingA" position rotation
$bonesaveframe "def_l_finRingB" position rotation
$bonesaveframe "def_l_finRingC" position rotation
$bonesaveframe "def_l_finPinkyA" position rotation
$bonesaveframe "def_l_finPinkyB" position rotation
$bonesaveframe "def_l_finPinkyC" position rotation
$bonesaveframe "def_r_clav" position rotation
$bonesaveframe "def_r_shoulder" position rotation
$bonesaveframe "def_r_shoulderTwist" position rotation
$bonesaveframe "def_r_elbowB" position
$bonesaveframe "def_r_shoulderMid" position rotation
$bonesaveframe "def_r_elbow" rotation
$bonesaveframe "def_r_forearm" position
$bonesaveframe "def_r_wrist" position
$bonesaveframe "def_r_finIndexA" position
$bonesaveframe "def_r_finIndexB" position
$bonesaveframe "def_r_finIndexC" position
$bonesaveframe "def_r_finMidA" rotation
$bonesaveframe "def_r_finMidB" rotation
$bonesaveframe "def_r_finMidC" rotation
$bonesaveframe "def_r_finThumbA" position
$bonesaveframe "def_r_finRingCarpal" position rotation
$bonesaveframe "def_r_finRingA" position rotation
$bonesaveframe "def_r_finRingB" position rotation
$bonesaveframe "def_r_finRingC" position rotation
$bonesaveframe "def_r_finPinkyA" position rotation
$bonesaveframe "def_r_finPinkyB" position rotation
$bonesaveframe "def_r_finPinkyC" position rotation
$bonesaveframe "def_l_thigh" position
$bonesaveframe "def_l_knee" position
$bonesaveframe "def_l_ankle" position rotation
$bonesaveframe "def_l_ball" rotation
$bonesaveframe "def_l_kneeB" position
$bonesaveframe "def_r_thigh" position
$bonesaveframe "def_r_knee" position
$bonesaveframe "def_r_ankle" position rotation
$bonesaveframe "def_r_ball" rotation
$bonesaveframe "ja_l_propHand" position
$bonesaveframe "ja_r_propHand" position

$animation "face_neutral_ag" "pete_agents_anims\face_neutral_ag.smd" {
	fps 30
}

$animation "a_aim_stand_neutral_pistol_Reload" "pete_agents_anims\a_aim_stand_neutral_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_down_left_pistol_Reload" "pete_agents_anims\a_aim_stand_down_left_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_down_center_pistol_Reload" "pete_agents_anims\a_aim_stand_down_center_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_down_right_pistol_Reload" "pete_agents_anims\a_aim_stand_down_right_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_mid_left_pistol_Reload" "pete_agents_anims\a_aim_stand_mid_left_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_mid_center_pistol_Reload" "pete_agents_anims\a_aim_stand_mid_center_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_mid_right_pistol_Reload" "pete_agents_anims\a_aim_stand_mid_right_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_up_left_pistol_Reload" "pete_agents_anims\a_aim_stand_up_left_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_up_center_pistol_Reload" "pete_agents_anims\a_aim_stand_up_center_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_up_right_pistol_Reload" "pete_agents_anims\a_aim_stand_up_right_pistol_Reload.smd" {
	fps 30
}

$animation "a_aim_stand_straightup_pistol_Reload" "pete_agents_anims\a_aim_stand_straightup_pistol_Reload.smd" {
	fps 30
}

$sequence "pt_agent_reload_dodge_shift" {
	"pete_agents_anims\pt_agent_reload_dodge_shift.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_agent_search_2_angry" {
	"pete_agents_anims\pt_agent_search_2_angry.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_agent_trans_2_search" {
	"pete_agents_anims\pt_agent_trans_2_search.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_pain_ag" {
	"pete_agents_anims\add_face_pain_ag.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_surprise_ag" {
	"pete_agents_anims\add_face_surprise_ag.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_angryPose_ag" {
	"pete_agents_anims\add_face_angryPose_ag.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_Poised_ag" {
	"pete_agents_anims\add_face_Poised_ag.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_fierce_ag" {
	"pete_agents_anims\add_face_fierce_ag.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_focused_ag" {
	"pete_agents_anims\add_face_focused_ag.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_fire_ag" {
	"pete_agents_anims\add_face_fire_ag.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Aim_agent_static" {
	"a_aim_stand_up_left_pistol_Reload"
	"a_aim_stand_up_center_pistol_Reload"
	"a_aim_stand_up_right_pistol_Reload"
	"a_aim_stand_mid_left_pistol_Reload"
	"a_aim_stand_mid_center_pistol_Reload"
	"a_aim_stand_mid_right_pistol_Reload"
	"a_aim_stand_down_left_pistol_Reload"
	"a_aim_stand_down_center_pistol_Reload"
	"a_aim_stand_down_right_pistol_Reload"
}

$sequence "pt_agent_angry_scan" {
	"pete_agents_anims\pt_agent_angry_scan.smd"
	activity "ACT_IDLE_SCAN" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 1 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 5 "step_light" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 17 "step_light" }
	{ event AE_CL_PLAYSOUND 118 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_agent_casual_search" {
	"pete_agents_anims\pt_agent_casual_search.smd"
	activity "ACT_IDLE" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 98 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 100 "step_light" }
	{ event AE_CL_PLAYSOUND 101 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 165 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_R 174 "step_light" }
	{ event AE_CL_PLAYSOUND 175 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 202 "step_light" }
	{ event AE_CL_PLAYSOUND 203 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 247 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 300 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_agent_angry_idle" {
	"pete_agents_anims\pt_agent_angry_idle.smd"
	activity "ACT_IDLE_COMBAT" 3
	activitymodifier pistol
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_agent_angry_twitch" {
	"pete_agents_anims\pt_agent_angry_twitch.smd"
	activity "ACT_IDLE_COMBAT" 3
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 11 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
	loop
}

$sequence "agent_idle_old" {
	"pete_agents_anims\agent_idle_old.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_agent_idle_static" {
	"pete_agents_anims\pt_agent_idle_static.smd"
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	fps 30
}

$sequence "pt_agent_fire" {
	"pete_agents_anims\pt_agent_fire.smd"
	activity "ACT_RANGE_ATTACK1" 5
	activitymodifier pistol
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fire_ag" 0 0 0 0
	fps 40
}

$sequence "pt_agent_ranged_attack2_TMP" {
	"pete_agents_anims\pt_agent_ranged_attack2_TMP.smd"
	activity "ACT_RANGE_ATTACK2" -1
	activitymodifier pistol
	{ event AE_NPC_WEAPON_FIRE 22 "" }
	{ event AE_NPC_WEAPON_FIRE 32 "" }
	{ event AE_NPC_WEAPON_FIRE 35 "" }
	{ event AE_NPC_WEAPON_FIRE 45 "" }
	{ event AE_NPC_WEAPON_FIRE 51 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fire_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_reload_front" {
	"pete_agents_anims\pt_agent_reload_front.smd"
	activity "ACT_RELOAD" 3
	activitymodifier pistol
	{ event AE_NPC_WEAPON_RELOAD 25 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 46 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 1 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_CL_PLAYSOUND 12 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 19 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_CL_PLAYSOUND 27 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 27 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 30 "weapon_pistol_3p_reload_boltfront" }
	{ event AE_CL_PLAYSOUND 32 "grunt_mvmt_fol_soft_med" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_reload_side" {
	"pete_agents_anims\pt_agent_reload_side.smd"
	activity "ACT_RELOAD" 3
	activitymodifier pistol
	{ event AE_NPC_WEAPON_RELOAD 36 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 56 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 1 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_CL_PLAYSOUND 15 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 22 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_CL_PLAYSOUND 33 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 33 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 36 "weapon_pistol_3p_reload_boltfront" }
	{ event AE_CL_PLAYSOUND 41 "grunt_mvmt_fol_soft_med" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_reload_dodge_weave" {
	"pete_agents_anims\pt_agent_reload_dodge_weave.smd"
	activity "ACT_RELOAD" 1
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 50 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 100 "" }
	{ event AE_NPC_WEAPON_RELOAD 22 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 50 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 105 "" }
	{ event AE_CL_PLAYSOUND 1 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 3 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_CL_PLAYSOUND 13 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 18 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_CL_PLAYSOUND 29 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 29 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 32 "weapon_pistol_3p_reload_boltfront" }
	{ event AE_CL_PLAYSOUND 38 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_R 42 "step_light" }
	{ event AE_CL_PLAYSOUND 43 "grunt_mvmt_fol_gear_run" }
	{ event AE_FOOTSTEP_L 54 "" }
	{ event AE_CL_PLAYSOUND 55 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 65 "step_light" }
	{ event AE_CL_PLAYSOUND 66 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 82 "step_light" }
	{ event AE_CL_PLAYSOUND 83 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 96 "step_light" }
	{ event AE_CL_PLAYSOUND 97 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 103 "step_light" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_reload_dodge_R" {
	"pete_agents_anims\pt_agent_reload_dodge_R.smd"
	activity "ACT_RELOAD_DODGE_RIGHT" 1
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 18 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 35 "" }
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 12 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 39 "" }
	{ event AE_NPC_WEAPON_RELOAD 70 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 12 "" }
	{ event AE_FOOTSTEP_R 6 "" }
	{ event AE_CL_PLAYSOUND 7 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_CL_PLAYSOUND 22 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 32 "step_light" }
	{ event AE_CL_PLAYSOUND 33 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 40 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 41 "step_light" }
	{ event AE_CL_PLAYSOUND 42 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 46 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_CL_PLAYSOUND 55 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 60 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_CL_PLAYSOUND 72 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 72 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 75 "weapon_pistol_3p_reload_boltfront" }
	{ event AE_CL_PLAYSOUND 79 "grunt_mvmt_fol_soft_med" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_reload_backpedal_fast" {
	"pete_agents_anims\pt_agent_reload_backpedal_fast.smd"
	activity "ACT_RELOAD_DODGE_RIGHT" 1
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 10 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 40 "" }
	{ event AE_NPC_ENEMY_ALIGN 80 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 100 "" }
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 4 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 24 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 83 "" }
	{ event AE_NPC_WEAPON_RELOAD 50 "" }
	{ event AE_GROUND_CONTACT_L 4 "step_light" }
	{ event AE_CL_PLAYSOUND 5 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 13 "step_light" }
	{ event AE_GROUND_CONTACT_L 22 "step_light" }
	{ event AE_CL_PLAYSOUND 23 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 23 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 31 "step_light" }
	{ event AE_CL_PLAYSOUND 32 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 32 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_CL_PLAYSOUND 43 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 47 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_CL_PLAYSOUND 60 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 60 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 63 "weapon_pistol_3p_reload_boltfront" }
	{ event AE_CL_PLAYSOUND 69 "grunt_mvmt_fol_soft_med" }
	{ event AE_FOOTSTEP_L 74 "" }
	{ event AE_CL_PLAYSOUND 75 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 86 "step_light" }
	{ event AE_CL_PLAYSOUND 87 "grunt_mvmt_fol_gear_run" }
	{ event AE_FOOTSTEP_L 97 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_reload_dodge_L" {
	"pete_agents_anims\pt_agent_reload_dodge_L.smd"
	activity "ACT_RELOAD_DODGE_LEFT" 1
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 10 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 35 "" }
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 8 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 60 "" }
	{ event AE_NPC_WEAPON_RELOAD 90 "" }
	{ event AE_GROUND_CONTACT_L 1 "step_light" }
	{ event AE_CL_PLAYSOUND 2 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_R 18 "" }
	{ event AE_CL_PLAYSOUND 19 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_L 31 "" }
	{ event AE_CL_PLAYSOUND 32 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 48 "step_light" }
	{ event AE_CL_PLAYSOUND 49 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 57 "step_light" }
	{ event AE_CL_PLAYSOUND 63 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 67 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_CL_PLAYSOUND 78 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 84 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_CL_PLAYSOUND 97 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 97 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 100 "weapon_pistol_3p_reload_boltfront" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_reload_sidestep" {
	"pete_agents_anims\pt_agent_reload_sidestep.smd"
	activity "ACT_RELOAD_DODGE_LEFT" 1
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 13 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 20 "" }
	{ event AE_NPC_ENEMY_ALIGN 68 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 80 "" }
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 20 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 96 "" }
	{ event AE_NPC_WEAPON_RELOAD 130 "" }
	{ event AE_CL_PLAYSOUND 1 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 9 "step_light" }
	{ event AE_CL_PLAYSOUND 10 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 21 "step_light" }
	{ event AE_CL_PLAYSOUND 42 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 47 "step_light" }
	{ event AE_CL_PLAYSOUND 48 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_L 59 "" }
	{ event AE_CL_PLAYSOUND 60 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_R 73 "" }
	{ event AE_CL_PLAYSOUND 74 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 82 "step_light" }
	{ event AE_CL_PLAYSOUND 94 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 98 "step_light" }
	{ event AE_CL_PLAYSOUND 103 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 104 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_CL_PLAYSOUND 112 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 117 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_CL_PLAYSOUND 125 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 125 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 128 "weapon_pistol_3p_reload_boltfront" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_reload_duck" {
	"pete_agents_anims\pt_agent_reload_duck.smd"
	activity "ACT_RANGE_ATTACK1_EVASIVE" 1
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 17 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 30 "" }
	{ event AE_NPC_ENEMY_ALIGN 66 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 80 "" }
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 9 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 55 "" }
	{ event AE_NPC_WEAPON_RELOAD 90 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 122 "" }
	{ event AE_CL_PLAYSOUND 4 "grunt_mvmt_fol_gear_run" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_CL_PLAYSOUND 12 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 26 "step_light" }
	{ event AE_CL_PLAYSOUND 27 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 35 "step_light" }
	{ event AE_CL_PLAYSOUND 47 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 57 "step_light" }
	{ event AE_CL_PLAYSOUND 58 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 63 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 70 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_GROUND_CONTACT_R 74 "step_light" }
	{ event AE_CL_PLAYSOUND 75 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 79 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 83 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_GROUND_CONTACT_L 85 "step_light" }
	{ event AE_CL_PLAYSOUND 90 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 90 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 93 "weapon_pistol_3p_reload_boltfront" }
	{ event AE_CL_PLAYSOUND 102 "grunt_mvmt_fol_soft_med" }
	{ event AE_FOOTSTEP_L 108 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_focused_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_dodge_L" {
	"pete_agents_anims\pt_agent_dodge_L.smd"
	activity "ACT_RANGE_ATTACK1_EVASIVE" 2
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 12 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 36 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 12 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 30 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 2 "step_light" }
	{ event AE_CL_PLAYSOUND 3 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 3 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 12 "step_light" }
	{ event AE_CL_PLAYSOUND 13 "grunt_mvmt_fol_gear_run" }
	{ event AE_FOOTSTEP_R 24 "" }
	{ event AE_CL_PLAYSOUND 25 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_L 32 "step_light" }
	{ event AE_CL_PLAYSOUND 33 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 42 "step_light" }
	{ event AE_CL_PLAYSOUND 43 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 47 "step_light" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_dodge_L_duck" {
	"pete_agents_anims\pt_agent_dodge_L_duck.smd"
	activity "ACT_RANGE_ATTACK1_EVASIVE" 2
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 24 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 40 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 20 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 30 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 55 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 5 "step_light" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_gear_run" }
	{ event AE_FOOTSTEP_L 13 "" }
	{ event AE_CL_PLAYSOUND 14 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 26 "step_light" }
	{ event AE_CL_PLAYSOUND 27 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 37 "step_light" }
	{ event AE_CL_PLAYSOUND 38 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 41 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_R 49 "step_light" }
	{ event AE_CL_PLAYSOUND 50 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 55 "step_light" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_dodge_R" {
	"pete_agents_anims\pt_agent_dodge_R.smd"
	activity "ACT_RANGE_ATTACK1_EVASIVE" 2
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 20 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 28 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 20 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 25 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 37 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 4 "step_light" }
	{ event AE_CL_PLAYSOUND 5 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 9 "step_light" }
	{ event AE_CL_PLAYSOUND 10 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 24 "step_light" }
	{ event AE_CL_PLAYSOUND 35 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 29 "step_light" }
	{ event AE_CL_PLAYSOUND 33 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_L 37 "step_light" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_dodge_R_duck" {
	"pete_agents_anims\pt_agent_dodge_R_duck.smd"
	activity "ACT_RANGE_ATTACK1_EVASIVE" 2
	activitymodifier pistol
	{ event AE_NPC_ENEMY_ALIGN 15 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 40 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 15 "" }
	{ event AE_NPC_SHOOT_OVERLAY_OFF 35 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 50 "" }
	{ event AE_CL_PLAYSOUND 2 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_L 5 "step_light" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 8 "step_light" }
	{ event AE_GROUND_CONTACT_L 24 "jog" }
	{ event AE_CL_PLAYSOUND 25 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 33 "jog" }
	{ event AE_CL_PLAYSOUND 34 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 39 "step_light" }
	{ event AE_CL_PLAYSOUND 40 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 40 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 44 "step_light" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "agent_reload_old" {
	"pete_agents_anims\agent_reload_old.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_agent_pain_head" {
	"pete_agents_anims\pt_agent_pain_head.smd"
	activity "ACT_FLINCH_HEAD" 2
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 19 "step_light" }
	{ event AE_CL_PLAYSOUND 20 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 27 "step_light" }
	{ event AE_CL_PLAYSOUND 41 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_L 50 "" }
	{ event AE_CL_PLAYSOUND 51 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 58 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_helmet" {
	"pete_agents_anims\pt_agent_pain_helmet.smd"
	activity "ACT_FLINCH_HEAD" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 13 "step_light" }
	{ event AE_CL_PLAYSOUND 24 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 31 "step_light" }
	{ event AE_CL_PLAYSOUND 35 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_helmet_knockdown" {
	"pete_agents_anims\pt_agent_pain_helmet_knockdown.smd"
	activity "ACT_FLINCH_HEAD" 1
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 25 "crouch" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_ON 17 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_ON 17 "" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_OFF 80 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_OFF 80 "" }
	{ event AE_NPC_SET_STANCE 95 "stand" }
	{ event AE_NPC_WEAPON_FIRE 65 "" }
	{ event AE_NPC_WEAPON_FIRE 73 "" }
	{ event AE_NPC_PATH_ALIGN 76 "" }
	{ event AE_NPC_WEAPON_FIRE 81 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_short" }
	{ event AE_GROUND_CONTACT_R 20 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 47 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_R 60 "crouch" }
	{ event AE_CL_PLAYSOUND 86 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 90 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 98 "step_light" }
	{ event AE_CL_PLAYSOUND 99 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 107 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_chest" {
	"pete_agents_anims\pt_agent_pain_chest.smd"
	activity "ACT_FLINCH_CHEST" 1
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 10 "crouch" }
	{ event AE_NPC_SET_STANCE 40 "stand" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 13 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 33 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 43 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_R 49 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_R_stumble" {
	"pete_agents_anims\pt_agent_pain_R_stumble.smd"
	activity "ACT_FLINCH_RIGHTARM" 2
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 16 "step_light" }
	{ event AE_CL_PLAYSOUND 17 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 21 "step_light" }
	{ event AE_CL_PLAYSOUND 22 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 48 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_FOOTSTEP_L 52 "" }
	{ event AE_CL_PLAYSOUND 53 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 61 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_L_shoulder" {
	"pete_agents_anims\pt_agent_pain_L_shoulder.smd"
	activity "ACT_FLINCH_LEFTARM" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 21 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 27 "step_light" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_L_stumble" {
	"pete_agents_anims\pt_agent_pain_L_stumble.smd"
	activity "ACT_FLINCH_LEFTARM" 2
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 16 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 21 "step_light" }
	{ event AE_CL_PLAYSOUND 22 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 31 "step_light" }
	{ event AE_GROUND_CONTACT_L 45 "step_light" }
	{ event AE_CL_PLAYSOUND 46 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 55 "step_light" }
	{ event AE_CL_PLAYSOUND 56 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 56 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_L 63 "step_light" }
	{ event AE_CL_PLAYSOUND 64 "grunt_mvmt_fol_gear_walk" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_hip" {
	"pete_agents_anims\pt_agent_pain_hip.smd"
	activity "ACT_FLINCH_STOMACH" 1
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 6 "crouch" }
	{ event AE_NPC_SET_STANCE 67 "stand" }
	{ event AE_NPC_WEAPON_FIRE 63 "" }
	{ event AE_NPC_WEAPON_FIRE 70 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 5 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 29 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 45 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 52 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 65 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 72 "step_light" }
	{ event AE_CL_PLAYSOUND 73 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 81 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_hip_alt" {
	"pete_agents_anims\pt_agent_pain_hip_alt.smd"
	activity "ACT_FLINCH_STOMACH" 1
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 10 "crouch" }
	{ event AE_NPC_SET_STANCE 40 "stand" }
	{ event AE_NPC_WEAPON_FIRE 41 "" }
	{ event AE_NPC_WEAPON_FIRE 53 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 3 "step_light" }
	{ event AE_GROUND_CONTACT_R 9 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 18 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 21 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_L 24 "crouch" }
	{ event AE_CL_PLAYSOUND 33 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_R 45 "step_light" }
	{ event AE_CL_PLAYSOUND 46 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 53 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_sidefall" {
	"pete_agents_anims\pt_agent_pain_sidefall.smd"
	activity "ACT_FLINCH_RIGHTLEG" 1
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 10 "crouch" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_ON 8 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_ON 8 "" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_OFF 78 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_OFF 78 "" }
	{ event AE_NPC_SET_STANCE 88 "stand" }
	{ event AE_NPC_WEAPON_FIRE 88 "" }
	{ event AE_NPC_WEAPON_FIRE 94 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 8 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 32 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 51 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 60 "step_light" }
	{ event AE_CL_PLAYSOUND 61 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 64 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_L 69 "step_light" }
	{ event AE_CL_PLAYSOUND 70 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 80 "crouch" }
	{ event AE_CL_PLAYSOUND 83 "grunt_mvmt_fol_soft_med" }
	{ event AE_FOOTSTEP_L 96 "" }
	{ event AE_CL_PLAYSOUND 97 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 102 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_pain_sidefall_alt" {
	"pete_agents_anims\pt_agent_pain_sidefall_alt.smd"
	activity "ACT_FLINCH_LEFTLEG" 1
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 12 "crouch" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_ON 5 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_ON 5 "" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_OFF 68 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_OFF 68 "" }
	{ event AE_NPC_SET_STANCE 85 "stand" }
	{ event AE_NPC_WEAPON_FIRE 64 "" }
	{ event AE_NPC_WEAPON_FIRE 78 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 6 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 23 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 41 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 50 "crouch" }
	{ event AE_CL_PLAYSOUND 51 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 77 "crouch" }
	{ event AE_CL_PLAYSOUND 78 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 85 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_FOOTSTEP_L 95 "" }
	{ event AE_CL_PLAYSOUND 96 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 101 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_encircle" {
	"pete_agents_anims\pt_agent_signal_encircle.smd"
	activity "ACT_SIGNAL_FORWARD" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 18 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_gogo" {
	"pete_agents_anims\pt_agent_signal_gogo.smd"
	activity "ACT_SIGNAL_FORWARD" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 14 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 22 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_gogogo" {
	"pete_agents_anims\pt_agent_signal_gogogo.smd"
	activity "ACT_SIGNAL_FORWARD" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 11 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 16 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 21 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_hold" {
	"pete_agents_anims\pt_agent_signal_hold.smd"
	activity "ACT_SIGNAL_FORWARD" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_readyup" {
	"pete_agents_anims\pt_agent_signal_readyup.smd"
	activity "ACT_SIGNAL_FORWARD" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 7 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 13 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 42 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_spotted" {
	"pete_agents_anims\pt_agent_signal_spotted.smd"
	activity "ACT_SIGNAL_FORWARD" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 26 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 62 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_2_search" {
	"pete_agents_anims\pt_agent_react_2_search.smd"
	activitymodifier pistol
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_wildfire_TMP" {
	"pete_agents_anims\pt_agent_react_wildfire_TMP.smd"
	activity "ACT_REACT_SURPRISED" 1
	activitymodifier pistol
	{ event AE_NPC_WEAPON_FIRE 22 "" }
	{ event AE_NPC_WEAPON_FIRE 32 "" }
	{ event AE_NPC_WEAPON_FIRE 35 "" }
	{ event AE_NPC_WEAPON_FIRE 45 "" }
	{ event AE_NPC_WEAPON_FIRE 51 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fire_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_react_far_TMP" {
	"pete_agents_anims\pt_agent_signal_react_far_TMP.smd"
	activity "ACT_REACT_SURPRISED_FAR" 1
	activitymodifier pistol
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_group_TMP" {
	"pete_agents_anims\pt_agent_signal_group_TMP.smd"
	activity "ACT_SIGNAL_GROUP" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_acknowledge_TMP" {
	"pete_agents_anims\pt_agent_signal_acknowledge_TMP.smd"
	activity "ACT_SIGNAL_ACKNOWLEDGE" 1
	activitymodifier pistol
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_bullet_TMP" {
	"pete_agents_anims\pt_agent_react_bullet_TMP.smd"
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 2 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_L 5 "step_light" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 8 "step_light" }
	{ event AE_GROUND_CONTACT_L 24 "jog" }
	{ event AE_CL_PLAYSOUND 25 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 33 "jog" }
	{ event AE_CL_PLAYSOUND 34 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 39 "step_light" }
	{ event AE_CL_PLAYSOUND 40 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 40 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 44 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_bullet_far_TMP" {
	"pete_agents_anims\pt_agent_react_bullet_far_TMP.smd"
	activity "ACT_REACT_BULLET_FAR" 1
	activitymodifier pistol
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_WEAPON_FIRE 9 "" }
	{ event AE_NPC_WEAPON_FIRE 18 "" }
	{ event AE_NPC_WEAPON_FIRE 33 "" }
	{ event AE_NPC_WEAPON_FIRE 48 "" }
	{ event AE_NPC_WEAPON_FIRE 55 "" }
	{ event AE_NPC_WEAPON_RELOAD 90 "" }
	{ event AE_NPC_WEAPON_FIRE 122 "" }
	{ event AE_CL_PLAYSOUND 4 "grunt_mvmt_fol_gear_run" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_CL_PLAYSOUND 12 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 26 "step_light" }
	{ event AE_CL_PLAYSOUND 27 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 35 "step_light" }
	{ event AE_CL_PLAYSOUND 47 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 57 "step_light" }
	{ event AE_CL_PLAYSOUND 58 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 63 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 70 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_GROUND_CONTACT_R 74 "step_light" }
	{ event AE_CL_PLAYSOUND 75 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 79 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 83 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_GROUND_CONTACT_L 85 "step_light" }
	{ event AE_CL_PLAYSOUND 90 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 90 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 93 "weapon_pistol_3p_reload_boltfront" }
	{ event AE_CL_PLAYSOUND 102 "grunt_mvmt_fol_soft_med" }
	{ event AE_FOOTSTEP_L 108 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_signal_salute_TMP" {
	"pete_agents_anims\pt_agent_signal_salute_TMP.smd"
	activity "ACT_SIGNAL_SALUTE" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_cower_TMP" {
	"pete_agents_anims\pt_agent_cower_TMP.smd"
	activity "ACT_COWER" 1
	activitymodifier pistol
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_WEAPON_FIRE 13 "" }
	{ event AE_NPC_WEAPON_FIRE 24 "" }
	{ event AE_NPC_WEAPON_FIRE 36 "" }
	{ event AE_NPC_WEAPON_FIRE 42 "" }
	{ event AE_NPC_WEAPON_RELOAD 82 "" }
	{ event AE_NPC_WEAPON_FIRE 105 "" }
	{ event AE_NPC_WEAPON_FIRE 112 "" }
	{ event AE_NPC_WEAPON_FIRE 119 "" }
	{ event AE_NPC_WEAPON_FIRE 125 "" }
	{ event AE_NPC_WEAPON_FIRE 135 "" }
	{ event AE_NPC_WEAPON_FIRE 145 "" }
	{ event AE_GROUND_CONTACT_R 6 "step_light" }
	{ event AE_CL_PLAYSOUND 7 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 17 "step_light" }
	{ event AE_CL_PLAYSOUND 18 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 24 "step_light" }
	{ event AE_CL_PLAYSOUND 25 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 35 "step_light" }
	{ event AE_CL_PLAYSOUND 36 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 44 "step_light" }
	{ event AE_CL_PLAYSOUND 54 "Weapon_Pistol_3P_Reload_Magout" }
	{ event AE_CL_PLAYSOUND 63 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 69 "Weapon_Pistol_3P_Reload_MagInsert" }
	{ event AE_CL_PLAYSOUND 79 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 79 "weapon_pistol_3p_reload_boltback" }
	{ event AE_CL_PLAYSOUND 82 "weapon_pistol_3p_reload_boltfront" }
	{ event AE_CL_PLAYSOUND 90 "grunt_mvmt_fol_soft_med" }
	{ event AE_FOOTSTEP_L 96 "" }
	{ event AE_CL_PLAYSOUND 97 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_R 115 "" }
	{ event AE_CL_PLAYSOUND 116 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_L 132 "" }
	{ event AE_CL_PLAYSOUND 133 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 142 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_turn_L90_snap" {
	"pete_agents_anims\pt_agent_turn_L90_snap.smd"
	activity "ACT_90_LEFT" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_OFF 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 21 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 1 "step_light" }
	{ event AE_CL_PLAYSOUND 2 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 15 "step_light" }
	{ event AE_CL_PLAYSOUND 16 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_turn_L90_spin" {
	"pete_agents_anims\pt_agent_turn_L90_spin.smd"
	activity "ACT_90_LEFT" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_OFF 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 21 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 3 "step_light" }
	{ event AE_CL_PLAYSOUND 4 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 16 "step_light" }
	{ event AE_CL_PLAYSOUND 17 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_turn_R90_snap" {
	"pete_agents_anims\pt_agent_turn_R90_snap.smd"
	activity "ACT_90_RIGHT" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_OFF 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 24 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 9 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 18 "step_light" }
	{ event AE_CL_PLAYSOUND 19 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_turn_R90_spin" {
	"pete_agents_anims\pt_agent_turn_R90_spin.smd"
	activity "ACT_90_RIGHT" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_OFF 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 25 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 4 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 10 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 20 "step_light" }
	{ event AE_CL_PLAYSOUND 21 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_turn_L180_snap" {
	"pete_agents_anims\pt_agent_turn_L180_snap.smd"
	activity "ACT_180_LEFT" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_OFF 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 26 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_L 18 "step_light" }
	{ event AE_CL_PLAYSOUND 19 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 27 "step_light" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_turn_L180_spin" {
	"pete_agents_anims\pt_agent_turn_L180_spin.smd"
	activity "ACT_180_LEFT" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_OFF 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 28 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_L 18 "step_light" }
	{ event AE_CL_PLAYSOUND 19 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 25 "step_light" }
	{ event AE_CL_PLAYSOUND 26 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_turn_R180_snap" {
	"pete_agents_anims\pt_agent_turn_R180_snap.smd"
	activity "ACT_180_RIGHT" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_OFF 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 25 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 1 "step_light" }
	{ event AE_GROUND_CONTACT_R 8 "step_light" }
	{ event AE_CL_PLAYSOUND 9 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 20 "step_light" }
	{ event AE_CL_PLAYSOUND 21 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_turn_R180_spin" {
	"pete_agents_anims\pt_agent_turn_R180_spin.smd"
	activity "ACT_180_RIGHT" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_OFF 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 22 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_L 16 "step_light" }
	{ event AE_CL_PLAYSOUND 17 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_walk_start_F_TMP" {
	"pete_agents_anims\pt_agent_walk_start_F_TMP.smd"
	activity "ACT_STAND_TO_WALK_FORWARD" 1
	activitymodifier pistol
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_run_start_F" {
	"pete_agents_anims\pt_agent_run_start_F.smd"
	activity "ACT_STAND_TO_RUN_FORWARD" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 4 "step_light" }
	{ event AE_GROUND_CONTACT_L 7 "step_light" }
	{ event AE_CL_PLAYSOUND 8 "grunt_mvmt_fol_gear_run" }
	{ event AE_FOOTSTEP_R 21 "" }
	{ event AE_CL_PLAYSOUND 22 "grunt_mvmt_fol_gear_run" }
	{ event AE_FOOTSTEP_L 30 "" }
	{ event AE_CL_PLAYSOUND 31 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_run_stop_F" {
	"pete_agents_anims\pt_agent_run_stop_F.smd"
	activity "ACT_WALK_TO_STAND_FORWARD" 1
	activitymodifier pistol
	{ event AE_FOOTSTEP_R 3 "" }
	{ event AE_CL_PLAYSOUND 4 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 8 "step_light" }
	{ event AE_CL_PLAYSOUND 9 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_run_stop_F_hop" {
	"pete_agents_anims\pt_agent_run_stop_F_hop.smd"
	activity "ACT_RUN_TO_STAND_FORWARD" 1
	activitymodifier pistol
	{ event AE_FOOTSTEP_R 1 "" }
	{ event AE_GROUND_CONTACT_L 5 "step_light" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_melee_swing" {
	"pete_agents_anims\pt_agent_melee_swing.smd"
	activity "ACT_MELEE_ATTACK1" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 3 "grunt_mvmt_fol_soft_short" }
	{ event AE_FOOTSTEP_R 5 "" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 18 "step_light" }
	{ event AE_CL_PLAYSOUND 18 "Grunt_Melee_pt_melee_elbowstrike" }
	{ event AE_CL_PLAYSOUND_SPECTRE 18 "Spectre.Servo.Melee.Short" }
	{ event AE_CL_PLAYSOUND 19 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 29 "step_light" }
	{ event AE_CL_PLAYSOUND 30 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 32 "grunt_melee_pt_melee_push" }
	{ event AE_GROUND_CONTACT_L 34 "step_light" }
	{ event AE_CL_PLAYSOUND 41 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 51 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 53 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 58 "step_light" }
	{ event AE_CL_PLAYSOUND 59 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 66 "step_light" }
	{ event AE_CL_PLAYSOUND 67 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 74 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_R 77 "step_light" }
	{ event AE_MELEE_HIT 25 "" }
	{ event AE_NPC_CHARGE_HIT 40 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_melee_stab_TMP" {
	"pete_agents_anims\pt_agent_melee_stab_TMP.smd"
	activity "ACT_MELEE_ATTACK1" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_melee_pt_melee_push" }
	{ event AE_GROUND_CONTACT_L 11 "step_light" }
	{ event AE_CL_PLAYSOUND 12 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 20 "Grunt_Melee_pt_melee_elbowstrike" }
	{ event AE_GROUND_CONTACT_R 27 "step_light" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 35 "step_light" }
	{ event AE_CL_PLAYSOUND 42 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 53 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 57 "step_light" }
	{ event AE_CL_PLAYSOUND 58 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 68 "step_light" }
	{ event AE_CL_PLAYSOUND 69 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 72 "step_light" }
	{ event AE_CL_PLAYSOUND_SPECTRE 0 "Spectre.Servo.Melee.Short" }
	{ event AE_MELEE_HIT 7 "" }
	{ event AE_NPC_ENEMY_ALIGN 23 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 35 "" }
	{ event AE_NPC_CHARGE_HIT 27 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_melee_charge" {
	"pete_agents_anims\pt_agent_melee_charge.smd"
	activity "ACT_MELEE_ATTACK1" 2
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_melee_pt_melee_push" }
	{ event AE_GROUND_CONTACT_L 11 "step_light" }
	{ event AE_CL_PLAYSOUND 12 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 20 "Grunt_Melee_pt_melee_elbowstrike" }
	{ event AE_GROUND_CONTACT_R 27 "step_light" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 35 "step_light" }
	{ event AE_CL_PLAYSOUND 42 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 53 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 57 "step_light" }
	{ event AE_CL_PLAYSOUND 58 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 68 "step_light" }
	{ event AE_CL_PLAYSOUND 69 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 72 "step_light" }
	{ event AE_CL_PLAYSOUND_SPECTRE 0 "Spectre.Servo.Melee.Short" }
	{ event AE_MELEE_HIT 7 "" }
	{ event AE_NPC_ENEMY_ALIGN 23 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 35 "" }
	{ event AE_NPC_CHARGE_HIT 27 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_ARC_fall" {
	"pete_agents_anims\pt_agent_react_ARC_fall.smd"
	activity "ACT_STUNNED" 2
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 60 "crouch" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_ON 65 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_ON 65 "" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_OFF 130 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_OFF 130 "" }
	{ event AE_NPC_SET_STANCE 145 "stand" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_R 62 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 85 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 102 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 116 "crouch" }
	{ event AE_CL_PLAYSOUND 130 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_R 138 "crouch" }
	{ event AE_CL_PLAYSOUND 139 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 144 "step_light" }
	{ event AE_CL_PLAYSOUND 145 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 160 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_ARC_kneefall" {
	"pete_agents_anims\pt_agent_react_ARC_kneefall.smd"
	activity "ACT_STUNNED" 2
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 51 "crouch" }
	{ event AE_NPC_SET_STANCE 91 "stand" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_R 44 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 74 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_L 82 "crouch" }
	{ event AE_CL_PLAYSOUND 85 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 95 "step_light" }
	{ event AE_CL_PLAYSOUND 96 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 102 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_ARC_sidefall" {
	"pete_agents_anims\pt_agent_react_ARC_sidefall.smd"
	activity "ACT_STUNNED" 2
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 45 "crouch" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_ON 50 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_ON 50 "" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_OFF 115 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_OFF 115 "" }
	{ event AE_NPC_SET_STANCE 143 "stand" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_L 48 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 85 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 103 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 110 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_L 122 "crouch" }
	{ event AE_CL_PLAYSOUND 131 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_R 146 "step_light" }
	{ event AE_CL_PLAYSOUND 147 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 157 "step_light" }
	{ event AE_CL_PLAYSOUND 158 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 163 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_ARC_slowfall" {
	"pete_agents_anims\pt_agent_react_ARC_slowfall.smd"
	activity "ACT_STUNNED" 2
	activitymodifier pistol
	{ event AE_NPC_SET_STANCE 84 "crouch" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_ON 95 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_ON 95 "" }
	{ event AE_NPC_RAGDOLL_IMMEDIATE_OFF 110 "" }
	{ event AE_NPC_DIE_ANY_DAMAGE_OFF 110 "" }
	{ event AE_NPC_SET_STANCE 160 "stand" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_R 84 "mvmt_fol_bodyfall" }
	{ event AE_GROUND_CONTACT_R 94 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 118 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 133 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 145 "crouch" }
	{ event AE_CL_PLAYSOUND 146 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 158 "step_light" }
	{ event AE_CL_PLAYSOUND 159 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_ARC_scream" {
	"pete_agents_anims\pt_agent_react_ARC_scream.smd"
	activity "ACT_STUNNED" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_CL_PLAYSOUND 60 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 66 "step_light" }
	{ event AE_CL_PLAYSOUND 80 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 89 "step_light" }
	{ event AE_CL_PLAYSOUND 92 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_ARC_stumble_F" {
	"pete_agents_anims\pt_agent_react_ARC_stumble_F.smd"
	activity "ACT_STUNNED" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_CL_PLAYSOUND 60 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 71 "step_light" }
	{ event AE_CL_PLAYSOUND 81 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 93 "step_light" }
	{ event AE_CL_PLAYSOUND 94 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_ARC_stumble_R" {
	"pete_agents_anims\pt_agent_react_ARC_stumble_R.smd"
	activity "ACT_STUNNED" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_CL_PLAYSOUND 38 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 44 "step_light" }
	{ event AE_CL_PLAYSOUND 53 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 61 "step_light" }
	{ event AE_CL_PLAYSOUND 76 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 84 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 91 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_beckpedal" {
	"pete_agents_anims\pt_agent_react_cloak_beckpedal.smd"
	activity "ACT_REACT_CLOAK_DISAPPEAR_NEAR" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 85 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_CL_PLAYSOUND 9 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 27 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_R 50 "" }
	{ event AE_CL_PLAYSOUND 51 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 66 "step_light" }
	{ event AE_CL_PLAYSOUND 67 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 76 "step_light" }
	{ event AE_CL_PLAYSOUND 77 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 85 "step_light" }
	{ event AE_CL_PLAYSOUND 86 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_blindfire" {
	"pete_agents_anims\pt_agent_react_cloak_blindfire.smd"
	activity "ACT_REACT_CLOAK_DISAPPEAR_NEAR" 1
	activitymodifier pistol
	{ event AE_NPC_WEAPON_FIRE 49 "" }
	{ event AE_NPC_WEAPON_FIRE 59 "" }
	{ event AE_NPC_WEAPON_FIRE 72 "" }
	{ event AE_NPC_WEAPON_FIRE 80 "" }
	{ event AE_NPC_WEAPON_FIRE 85 "" }
	{ event AE_NPC_WEAPON_FIRE 95 "" }
	{ event AE_NPC_WEAPON_FIRE 118 "" }
	{ event AE_NPC_WEAPON_FIRE 124 "" }
	{ event AE_GROUND_CONTACT_R 1 "step_light" }
	{ event AE_GROUND_CONTACT_R 23 "step_light" }
	{ event AE_CL_PLAYSOUND 24 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 33 "step_light" }
	{ event AE_GROUND_CONTACT_R 53 "step_light" }
	{ event AE_CL_PLAYSOUND 54 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 67 "step_light" }
	{ event AE_GROUND_CONTACT_R 88 "step_light" }
	{ event AE_GROUND_CONTACT_L 142 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_look360" {
	"pete_agents_anims\pt_agent_react_cloak_look360.smd"
	activity "ACT_REACT_CLOAK_DISAPPEAR_NEAR" 4
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 170 "" }
	{ event AE_GROUND_CONTACT_R 1 "step_light" }
	{ event AE_CL_PLAYSOUND 2 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 8 "step_light" }
	{ event AE_CL_PLAYSOUND 38 "grunt_mvmt_fol_soft_med" }
	{ event AE_GROUND_CONTACT_L 70 "step_light" }
	{ event AE_CL_PLAYSOUND 91 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 111 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 117 "step_light" }
	{ event AE_CL_PLAYSOUND 160 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_search" {
	"pete_agents_anims\pt_agent_react_cloak_search.smd"
	activity "ACT_REACT_CLOAK_DISAPPEAR_NEAR" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 85 "" }
	{ event AE_GROUND_CONTACT_R 3 "step_light" }
	{ event AE_CL_PLAYSOUND 4 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 20 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 64 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_L 67 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_serach_F" {
	"pete_agents_anims\pt_agent_react_cloak_serach_F.smd"
	activity "ACT_REACT_CLOAK_DISAPPEAR_NEAR" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 100 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 11 "step_light" }
	{ event AE_CL_PLAYSOUND 12 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 26 "step_light" }
	{ event AE_CL_PLAYSOUND 27 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 38 "step_light" }
	{ event AE_CL_PLAYSOUND 39 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 54 "step_light" }
	{ event AE_CL_PLAYSOUND 55 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 68 "step_light" }
	{ event AE_CL_PLAYSOUND 92 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 124 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 129 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_panic" {
	"pete_agents_anims\pt_agent_react_cloak_panic.smd"
	activity "ACT_REACT_CLOAK_DISAPPEAR_NEAR" 3
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 80 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_L 3 "jog" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 23 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_L 38 "" }
	{ event AE_CL_PLAYSOUND 39 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 52 "step_light" }
	{ event AE_CL_PLAYSOUND 53 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 67 "step_light" }
	{ event AE_CL_PLAYSOUND 68 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 74 "step_light" }
	{ event AE_FOOTSTEP_R 88 "" }
	{ event AE_GROUND_CONTACT_L 100 "step_light" }
	{ event AE_CL_PLAYSOUND 101 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 113 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 157 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_search_far" {
	"pete_agents_anims\pt_agent_react_cloak_search_far.smd"
	activity "ACT_REACT_CLOAK_DISAPPEAR_FAR" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 85 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 5 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 20 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 50 "step_light" }
	{ event AE_CL_PLAYSOUND 65 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_L 67 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_serach_F_far" {
	"pete_agents_anims\pt_agent_react_cloak_serach_F_far.smd"
	activity "ACT_REACT_CLOAK_DISAPPEAR_FAR" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 100 "" }
	{ event AE_CL_PLAYSOUND 3 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 10 "step_light" }
	{ event AE_CL_PLAYSOUND 11 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 26 "step_light" }
	{ event AE_CL_PLAYSOUND 27 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 38 "step_light" }
	{ event AE_CL_PLAYSOUND 39 "grunt_mvmt_fol_gear_walk" }
	{ event AE_CL_PLAYSOUND 51 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_GROUND_CONTACT_R 54 "step_light" }
	{ event AE_CL_PLAYSOUND 55 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 68 "step_light" }
	{ event AE_CL_PLAYSOUND 92 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 125 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_panic_fire" {
	"pete_agents_anims\pt_agent_react_cloak_panic_fire.smd"
	activity "ACT_REACT_CLOAK_APPEAR_NEAR" 1
	activitymodifier pistol
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_ENEMY_ALIGN 15 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 25 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 35 "" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 11 "step_light" }
	{ event AE_CL_PLAYSOUND 12 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 27 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 29 "step_light" }
	{ event AE_CL_PLAYSOUND 30 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 37 "step_light" }
	{ event AE_CL_PLAYSOUND 61 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 69 "step_light" }
	{ event AE_CL_PLAYSOUND 70 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 83 "step_light" }
	{ event AE_CL_PLAYSOUND 95 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 103 "step_light" }
	{ event AE_GROUND_CONTACT_L 119 "step_light" }
	{ event AE_GROUND_CONTACT_R 127 "step_light" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	fps 30
}

$sequence "pt_agent_react_cloak_wildfire" {
	"pete_agents_anims\pt_agent_react_cloak_wildfire.smd"
	activity "ACT_REACT_CLOAK_APPEAR_NEAR" 1
	activitymodifier pistol
	{ event AE_NPC_WEAPON_RELOAD 1 "" }
	{ event AE_NPC_ENEMY_ALIGN 36 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 52 "" }
	{ event AE_NPC_WEAPON_FIRE 42 "" }
	{ event AE_NPC_WEAPON_FIRE 48 "" }
	{ event AE_NPC_WEAPON_FIRE 56 "" }
	{ event AE_NPC_WEAPON_FIRE 74 "" }
	{ event AE_NPC_WEAPON_FIRE 82 "" }
	{ event AE_NPC_WEAPON_FIRE 93 "" }
	{ event AE_GROUND_CONTACT_R 2 "step_light" }
	{ event AE_CL_PLAYSOUND 3 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 8 "step_light" }
	{ event AE_CL_PLAYSOUND 9 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 27 "step_light" }
	{ event AE_CL_PLAYSOUND 28 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 30 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 42 "step_light" }
	{ event AE_GROUND_CONTACT_R 50 "step_light" }
	{ event AE_GROUND_CONTACT_L 61 "step_light" }
	{ event AE_CL_PLAYSOUND 62 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 93 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 94 "step_light" }
	{ event AE_CL_PLAYSOUND 95 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 104 "step_light" }
	{ event AE_GROUND_CONTACT_L 134 "step_light" }
	{ event AE_CL_PLAYSOUND 146 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 157 "step_light" }
	{ event AE_CL_PLAYSOUND 158 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 168 "step_light" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_surprise_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_react_cloak_panic_fire_far" {
	"pete_agents_anims\pt_agent_react_cloak_panic_fire_far.smd"
	activity "ACT_REACT_CLOAK_APPEAR_FAR" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 35 "" }
	{ event AE_CL_PLAYSOUND 5 "grunt_mvmt_fol_soft_short" }
	{ event AE_FOOTSTEP_L 11 "" }
	{ event AE_CL_PLAYSOUND 12 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_L 37 "step_light" }
	{ event AE_CL_PLAYSOUND 58 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_R 70 "step_light" }
	{ event AE_CL_PLAYSOUND 74 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 83 "step_light" }
	{ event AE_CL_PLAYSOUND 84 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 102 "step_light" }
	{ event AE_CL_PLAYSOUND 103 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 119 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_twitch_shift_forward" {
	"pete_agents_anims\pt_agent_twitch_shift_forward.smd"
	activity "ACT_RANGE_ATTACK_TWITCH" 3
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 2 "" }
	{ event AE_GROUND_CONTACT_R 4 "step_light" }
	{ event AE_CL_PLAYSOUND 5 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 14 "step_light" }
	{ event AE_CL_PLAYSOUND 15 "grunt_mvmt_fol_gear_run" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_twitch_shift_side" {
	"pete_agents_anims\pt_agent_twitch_shift_side.smd"
	activity "ACT_RANGE_ATTACK_TWITCH" 3
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 2 "" }
	{ event AE_NPC_ENEMY_ALIGN 14 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 26 "" }
	{ event AE_GROUND_CONTACT_R 0 "step_light" }
	{ event AE_CL_PLAYSOUND 1 "grunt_mvmt_fol_gear_walk" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 13 "grunt_mvmt_fol_gear_walk" }
	{ event AE_GROUND_CONTACT_R 27 "step_light" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_twitch_encircle" {
	"pete_agents_anims\pt_agent_twitch_encircle.smd"
	activity "ACT_RANGE_ATTACK_TWITCH" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 50 "" }
	{ event AE_CL_PLAYSOUND 1 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 18 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_twitch_gogo" {
	"pete_agents_anims\pt_agent_twitch_gogo.smd"
	activity "ACT_RANGE_ATTACK_TWITCH" 1
	activitymodifier pistol
	{ event AE_NPC_SHOOT_OVERLAY_ON 42 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 14 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 23 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_twitch_spot" {
	"pete_agents_anims\pt_agent_twitch_spot.smd"
	activity "ACT_RANGE_ATTACK_TWITCH" 1
	activitymodifier pistol
	{ event AE_CL_PLAYSOUND 5 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 38 "grunt_mvmt_fol_soft_slow_cloth" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 40
}

$sequence "pt_agent_twitch_scan" {
	"pete_agents_anims\pt_agent_twitch_scan.smd"
	activitymodifier pistol
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_agent_twitch_twitch" {
	"pete_agents_anims\pt_agent_twitch_twitch.smd"
	activitymodifier pistol
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_agent_static"
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_swap_from_pistol" {
	"pete_agents_anims\pt_swap_from_pistol.smd"
	activity "ACT_SWITCH_WEAPON" 1
	activitymodifier pistol
	{ event AE_NPC_SWITCH_WEAPON 28 "primary" }
	{ event AE_NPC_ENEMY_ALIGN 40 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 57 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 16 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 42 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 49 "grunt_mvmt_fol_soft_short" }
	{ event AE_GROUND_CONTACT_L 49 "step_light" }
	{ event AE_CL_PLAYSOUND 53 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 53 "grunt_rifle_mvmt" }
	{ event AE_GROUND_CONTACT_R 58 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_swap_to_pistol" {
	"pete_agents_anims\pt_swap_to_pistol.smd"
	activity "ACT_SWITCH_WEAPON" 1
	{ event AE_NPC_ENEMY_ALIGN 9 "" }
	{ event AE_NPC_SWITCH_WEAPON 14 "primary" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 26 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 9 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 11 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 17 "step_light" }
	{ event AE_CL_PLAYSOUND 19 "grunt_mvmt_fol_soft_short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}

$sequence "pt_swap_to_pistol_charge" {
	"pete_agents_anims\pt_swap_to_pistol_charge.smd"
	activity "ACT_SWITCH_WEAPON" 1
	{ event AE_NPC_ENEMY_ALIGN 9 "" }
	{ event AE_NPC_SWITCH_WEAPON 11 "primary" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 23 "" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 7 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_L 16 "step_light" }
	{ event AE_CL_PLAYSOUND 17 "grunt_mvmt_fol_gear_run" }
	{ event AE_GROUND_CONTACT_R 27 "step_light" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_ag" 0 0 0 0
	fps 30
}
