// Created by Crowbar 0.71

$modelname "humans/pete/pete_skits.mdl"

$surfaceprop "default"

$jointsurfaceprop "jx_c_delta" ""
$jointsurfaceprop "jx_c_pov" ""
$jointsurfaceprop "jx_c_camera" ""
$jointsurfaceprop "def_c_hip" ""
$jointsurfaceprop "jx_c_start" ""
$jointsurfaceprop "def_c_spineA" ""
$jointsurfaceprop "def_c_spineB" ""
$jointsurfaceprop "def_c_spineC" ""
$jointsurfaceprop "ja_c_propGun" ""
$jointsurfaceprop "def_c_neckA" ""
$jointsurfaceprop "jx_c_neckB" ""
$jointsurfaceprop "def_c_neckB" ""
$jointsurfaceprop "def_c_head" ""
$jointsurfaceprop "def_l_clav" ""
$jointsurfaceprop "def_l_shoulder" ""
$jointsurfaceprop "def_l_shoulderTwist" ""
$jointsurfaceprop "def_l_elbowB" ""
$jointsurfaceprop "def_l_shoulderMid" ""
$jointsurfaceprop "def_l_elbow" ""
$jointsurfaceprop "def_l_forearm" ""
$jointsurfaceprop "def_l_wrist" ""
$jointsurfaceprop "def_l_finIndexA" ""
$jointsurfaceprop "def_l_finIndexB" ""
$jointsurfaceprop "def_l_finIndexC" ""
$jointsurfaceprop "def_l_finMidA" ""
$jointsurfaceprop "def_l_finMidB" ""
$jointsurfaceprop "def_l_finMidC" ""
$jointsurfaceprop "def_l_finThumbA" ""
$jointsurfaceprop "def_l_finThumbB" ""
$jointsurfaceprop "def_l_finThumbC" ""
$jointsurfaceprop "def_l_finRingCarpal" ""
$jointsurfaceprop "def_l_finRingA" ""
$jointsurfaceprop "def_l_finRingB" ""
$jointsurfaceprop "def_l_finRingC" ""
$jointsurfaceprop "def_l_finPinkyA" ""
$jointsurfaceprop "def_l_finPinkyB" ""
$jointsurfaceprop "def_l_finPinkyC" ""
$jointsurfaceprop "def_r_clav" ""
$jointsurfaceprop "def_r_shoulder" ""
$jointsurfaceprop "def_r_shoulderTwist" ""
$jointsurfaceprop "def_r_elbowB" ""
$jointsurfaceprop "def_r_shoulderMid" ""
$jointsurfaceprop "def_r_elbow" ""
$jointsurfaceprop "def_r_forearm" ""
$jointsurfaceprop "def_r_wrist" ""
$jointsurfaceprop "def_r_finIndexA" ""
$jointsurfaceprop "def_r_finIndexB" ""
$jointsurfaceprop "def_r_finIndexC" ""
$jointsurfaceprop "def_r_finMidA" ""
$jointsurfaceprop "def_r_finMidB" ""
$jointsurfaceprop "def_r_finMidC" ""
$jointsurfaceprop "def_r_finThumbA" ""
$jointsurfaceprop "def_r_finThumbB" ""
$jointsurfaceprop "def_r_finThumbC" ""
$jointsurfaceprop "def_r_finRingCarpal" ""
$jointsurfaceprop "def_r_finRingA" ""
$jointsurfaceprop "def_r_finRingB" ""
$jointsurfaceprop "def_r_finRingC" ""
$jointsurfaceprop "def_r_finPinkyA" ""
$jointsurfaceprop "def_r_finPinkyB" ""
$jointsurfaceprop "def_r_finPinkyC" ""
$jointsurfaceprop "def_l_thigh" ""
$jointsurfaceprop "def_l_knee" ""
$jointsurfaceprop "def_l_ankle" ""
$jointsurfaceprop "def_l_ball" ""
$jointsurfaceprop "def_l_kneeB" ""
$jointsurfaceprop "def_r_thigh" ""
$jointsurfaceprop "def_r_knee" ""
$jointsurfaceprop "def_r_ankle" ""
$jointsurfaceprop "def_r_ball" ""
$jointsurfaceprop "def_r_kneeB" ""
$jointsurfaceprop "ja_l_propHand" ""
$jointsurfaceprop "ja_r_propHand" ""
$jointsurfaceprop "def_fc_c_jaw_1" ""
$jointsurfaceprop "def_fc_c_jaw_2" ""
$jointsurfaceprop "def_fc_c_nose_1" ""
$jointsurfaceprop "def_fc_c_nose_2" ""
$jointsurfaceprop "def_fc_c_tongue_1" ""
$jointsurfaceprop "def_fc_c_tongue_2" ""
$jointsurfaceprop "def_fc_c_tongue_3" ""
$jointsurfaceprop "def_fc_l_botlip_1" ""
$jointsurfaceprop "def_fc_l_botlip_2" ""
$jointsurfaceprop "def_fc_l_botlip_3" ""
$jointsurfaceprop "def_fc_l_botlip_4" ""
$jointsurfaceprop "def_fc_l_brow_1" ""
$jointsurfaceprop "def_fc_l_brow_2" ""
$jointsurfaceprop "def_fc_l_brow_3" ""
$jointsurfaceprop "def_fc_l_brow_4" ""
$jointsurfaceprop "def_fc_l_cheek_1" ""
$jointsurfaceprop "def_fc_l_cheek_2" ""
$jointsurfaceprop "def_fc_l_cheek_3" ""
$jointsurfaceprop "def_fc_l_cheek_4" ""
$jointsurfaceprop "def_fc_l_cheek_5" ""
$jointsurfaceprop "def_fc_l_cheek_6" ""
$jointsurfaceprop "def_fc_l_eye_1" ""
$jointsurfaceprop "def_fc_l_eye_2" ""
$jointsurfaceprop "def_fc_l_eye_3" ""
$jointsurfaceprop "def_fc_l_forehead_1" ""
$jointsurfaceprop "def_fc_l_forehead_2" ""
$jointsurfaceprop "def_fc_l_jaw_1" ""
$jointsurfaceprop "def_fc_l_jaw_2" ""
$jointsurfaceprop "def_fc_l_jaw_3" ""
$jointsurfaceprop "def_fc_l_mustache_1" ""
$jointsurfaceprop "def_fc_l_mustache_2" ""
$jointsurfaceprop "def_fc_l_neck_1" ""
$jointsurfaceprop "def_fc_l_neck_2" ""
$jointsurfaceprop "def_fc_l_nose_1" ""
$jointsurfaceprop "def_fc_l_nose_2" ""
$jointsurfaceprop "def_fc_l_nose_3" ""
$jointsurfaceprop "def_fc_l_nose_4" ""
$jointsurfaceprop "def_fc_l_nose_5" ""
$jointsurfaceprop "def_fc_l_toplip_1" ""
$jointsurfaceprop "def_fc_l_toplip_2" ""
$jointsurfaceprop "def_fc_l_toplip_3" ""
$jointsurfaceprop "def_fc_l_toplip_4" ""
$jointsurfaceprop "def_fc_r_botlip_1" ""
$jointsurfaceprop "def_fc_r_botlip_2" ""
$jointsurfaceprop "def_fc_r_botlip_3" ""
$jointsurfaceprop "def_fc_r_botlip_4" ""
$jointsurfaceprop "def_fc_r_brow_1" ""
$jointsurfaceprop "def_fc_r_brow_2" ""
$jointsurfaceprop "def_fc_r_brow_3" ""
$jointsurfaceprop "def_fc_r_brow_4" ""
$jointsurfaceprop "def_fc_r_cheek_1" ""
$jointsurfaceprop "def_fc_r_cheek_2" ""
$jointsurfaceprop "def_fc_r_cheek_3" ""
$jointsurfaceprop "def_fc_r_cheek_4" ""
$jointsurfaceprop "def_fc_r_cheek_5" ""
$jointsurfaceprop "def_fc_r_cheek_6" ""
$jointsurfaceprop "def_fc_r_eye_1" ""
$jointsurfaceprop "def_fc_r_eye_2" ""
$jointsurfaceprop "def_fc_r_eye_3" ""
$jointsurfaceprop "def_fc_r_forehead_1" ""
$jointsurfaceprop "def_fc_r_forehead_2" ""
$jointsurfaceprop "def_fc_r_jaw_1" ""
$jointsurfaceprop "def_fc_r_jaw_2" ""
$jointsurfaceprop "def_fc_r_jaw_3" ""
$jointsurfaceprop "def_fc_r_mustache_1" ""
$jointsurfaceprop "def_fc_r_mustache_2" ""
$jointsurfaceprop "def_fc_r_neck_1" ""
$jointsurfaceprop "def_fc_r_neck_2" ""
$jointsurfaceprop "def_fc_r_nose_1" ""
$jointsurfaceprop "def_fc_r_nose_2" ""
$jointsurfaceprop "def_fc_r_nose_3" ""
$jointsurfaceprop "def_fc_r_nose_4" ""
$jointsurfaceprop "def_fc_r_nose_5" ""
$jointsurfaceprop "def_fc_r_toplip_1" ""
$jointsurfaceprop "def_fc_r_toplip_2" ""
$jointsurfaceprop "def_fc_r_toplip_3" ""
$jointsurfaceprop "def_fc_r_toplip_4" ""

$contents "solid"

$jointcontents "jx_c_delta" "notsolid"
$jointcontents "jx_c_pov" "notsolid"
$jointcontents "jx_c_camera" "notsolid"
$jointcontents "def_c_hip" "notsolid"
$jointcontents "jx_c_start" "notsolid"
$jointcontents "def_c_spineA" "notsolid"
$jointcontents "def_c_spineB" "notsolid"
$jointcontents "def_c_spineC" "notsolid"
$jointcontents "ja_c_propGun" "notsolid"
$jointcontents "def_c_neckA" "notsolid"
$jointcontents "jx_c_neckB" "notsolid"
$jointcontents "def_c_neckB" "notsolid"
$jointcontents "def_c_head" "notsolid"
$jointcontents "def_l_clav" "notsolid"
$jointcontents "def_l_shoulder" "notsolid"
$jointcontents "def_l_shoulderTwist" "notsolid"
$jointcontents "def_l_elbowB" "notsolid"
$jointcontents "def_l_shoulderMid" "notsolid"
$jointcontents "def_l_elbow" "notsolid"
$jointcontents "def_l_forearm" "notsolid"
$jointcontents "def_l_wrist" "notsolid"
$jointcontents "def_l_finIndexA" "notsolid"
$jointcontents "def_l_finIndexB" "notsolid"
$jointcontents "def_l_finIndexC" "notsolid"
$jointcontents "def_l_finMidA" "notsolid"
$jointcontents "def_l_finMidB" "notsolid"
$jointcontents "def_l_finMidC" "notsolid"
$jointcontents "def_l_finThumbA" "notsolid"
$jointcontents "def_l_finThumbB" "notsolid"
$jointcontents "def_l_finThumbC" "notsolid"
$jointcontents "def_l_finRingCarpal" "notsolid"
$jointcontents "def_l_finRingA" "notsolid"
$jointcontents "def_l_finRingB" "notsolid"
$jointcontents "def_l_finRingC" "notsolid"
$jointcontents "def_l_finPinkyA" "notsolid"
$jointcontents "def_l_finPinkyB" "notsolid"
$jointcontents "def_l_finPinkyC" "notsolid"
$jointcontents "def_r_clav" "notsolid"
$jointcontents "def_r_shoulder" "notsolid"
$jointcontents "def_r_shoulderTwist" "notsolid"
$jointcontents "def_r_elbowB" "notsolid"
$jointcontents "def_r_shoulderMid" "notsolid"
$jointcontents "def_r_elbow" "notsolid"
$jointcontents "def_r_forearm" "notsolid"
$jointcontents "def_r_wrist" "notsolid"
$jointcontents "def_r_finIndexA" "notsolid"
$jointcontents "def_r_finIndexB" "notsolid"
$jointcontents "def_r_finIndexC" "notsolid"
$jointcontents "def_r_finMidA" "notsolid"
$jointcontents "def_r_finMidB" "notsolid"
$jointcontents "def_r_finMidC" "notsolid"
$jointcontents "def_r_finThumbA" "notsolid"
$jointcontents "def_r_finThumbB" "notsolid"
$jointcontents "def_r_finThumbC" "notsolid"
$jointcontents "def_r_finRingCarpal" "notsolid"
$jointcontents "def_r_finRingA" "notsolid"
$jointcontents "def_r_finRingB" "notsolid"
$jointcontents "def_r_finRingC" "notsolid"
$jointcontents "def_r_finPinkyA" "notsolid"
$jointcontents "def_r_finPinkyB" "notsolid"
$jointcontents "def_r_finPinkyC" "notsolid"
$jointcontents "def_l_thigh" "notsolid"
$jointcontents "def_l_knee" "notsolid"
$jointcontents "def_l_ankle" "notsolid"
$jointcontents "def_l_ball" "notsolid"
$jointcontents "def_l_kneeB" "notsolid"
$jointcontents "def_r_thigh" "notsolid"
$jointcontents "def_r_knee" "notsolid"
$jointcontents "def_r_ankle" "notsolid"
$jointcontents "def_r_ball" "notsolid"
$jointcontents "def_r_kneeB" "notsolid"
$jointcontents "ja_l_propHand" "notsolid"
$jointcontents "ja_r_propHand" "notsolid"
$jointcontents "def_fc_c_jaw_1" "notsolid"
$jointcontents "def_fc_c_jaw_2" "notsolid"
$jointcontents "def_fc_c_nose_1" "notsolid"
$jointcontents "def_fc_c_nose_2" "notsolid"
$jointcontents "def_fc_c_tongue_1" "notsolid"
$jointcontents "def_fc_c_tongue_2" "notsolid"
$jointcontents "def_fc_c_tongue_3" "notsolid"
$jointcontents "def_fc_l_botlip_1" "notsolid"
$jointcontents "def_fc_l_botlip_2" "notsolid"
$jointcontents "def_fc_l_botlip_3" "notsolid"
$jointcontents "def_fc_l_botlip_4" "notsolid"
$jointcontents "def_fc_l_brow_1" "notsolid"
$jointcontents "def_fc_l_brow_2" "notsolid"
$jointcontents "def_fc_l_brow_3" "notsolid"
$jointcontents "def_fc_l_brow_4" "notsolid"
$jointcontents "def_fc_l_cheek_1" "notsolid"
$jointcontents "def_fc_l_cheek_2" "notsolid"
$jointcontents "def_fc_l_cheek_3" "notsolid"
$jointcontents "def_fc_l_cheek_4" "notsolid"
$jointcontents "def_fc_l_cheek_5" "notsolid"
$jointcontents "def_fc_l_cheek_6" "notsolid"
$jointcontents "def_fc_l_eye_1" "notsolid"
$jointcontents "def_fc_l_eye_2" "notsolid"
$jointcontents "def_fc_l_eye_3" "notsolid"
$jointcontents "def_fc_l_forehead_1" "notsolid"
$jointcontents "def_fc_l_forehead_2" "notsolid"
$jointcontents "def_fc_l_jaw_1" "notsolid"
$jointcontents "def_fc_l_jaw_2" "notsolid"
$jointcontents "def_fc_l_jaw_3" "notsolid"
$jointcontents "def_fc_l_mustache_1" "notsolid"
$jointcontents "def_fc_l_mustache_2" "notsolid"
$jointcontents "def_fc_l_neck_1" "notsolid"
$jointcontents "def_fc_l_neck_2" "notsolid"
$jointcontents "def_fc_l_nose_1" "notsolid"
$jointcontents "def_fc_l_nose_2" "notsolid"
$jointcontents "def_fc_l_nose_3" "notsolid"
$jointcontents "def_fc_l_nose_4" "notsolid"
$jointcontents "def_fc_l_nose_5" "notsolid"
$jointcontents "def_fc_l_toplip_1" "notsolid"
$jointcontents "def_fc_l_toplip_2" "notsolid"
$jointcontents "def_fc_l_toplip_3" "notsolid"
$jointcontents "def_fc_l_toplip_4" "notsolid"
$jointcontents "def_fc_r_botlip_1" "notsolid"
$jointcontents "def_fc_r_botlip_2" "notsolid"
$jointcontents "def_fc_r_botlip_3" "notsolid"
$jointcontents "def_fc_r_botlip_4" "notsolid"
$jointcontents "def_fc_r_brow_1" "notsolid"
$jointcontents "def_fc_r_brow_2" "notsolid"
$jointcontents "def_fc_r_brow_3" "notsolid"
$jointcontents "def_fc_r_brow_4" "notsolid"
$jointcontents "def_fc_r_cheek_1" "notsolid"
$jointcontents "def_fc_r_cheek_2" "notsolid"
$jointcontents "def_fc_r_cheek_3" "notsolid"
$jointcontents "def_fc_r_cheek_4" "notsolid"
$jointcontents "def_fc_r_cheek_5" "notsolid"
$jointcontents "def_fc_r_cheek_6" "notsolid"
$jointcontents "def_fc_r_eye_1" "notsolid"
$jointcontents "def_fc_r_eye_2" "notsolid"
$jointcontents "def_fc_r_eye_3" "notsolid"
$jointcontents "def_fc_r_forehead_1" "notsolid"
$jointcontents "def_fc_r_forehead_2" "notsolid"
$jointcontents "def_fc_r_jaw_1" "notsolid"
$jointcontents "def_fc_r_jaw_2" "notsolid"
$jointcontents "def_fc_r_jaw_3" "notsolid"
$jointcontents "def_fc_r_mustache_1" "notsolid"
$jointcontents "def_fc_r_mustache_2" "notsolid"
$jointcontents "def_fc_r_neck_1" "notsolid"
$jointcontents "def_fc_r_neck_2" "notsolid"
$jointcontents "def_fc_r_nose_1" "notsolid"
$jointcontents "def_fc_r_nose_2" "notsolid"
$jointcontents "def_fc_r_nose_3" "notsolid"
$jointcontents "def_fc_r_nose_4" "notsolid"
$jointcontents "def_fc_r_nose_5" "notsolid"
$jointcontents "def_fc_r_toplip_1" "notsolid"
$jointcontents "def_fc_r_toplip_2" "notsolid"
$jointcontents "def_fc_r_toplip_3" "notsolid"
$jointcontents "def_fc_r_toplip_4" "notsolid"

$illumposition 0 0.596 53.032

$eyeposition 0 0 64

$cdmaterials ""

$attachment "OFFSET" "jx_c_delta" 0 0 0 rotate -90 -90 0
$attachment "REF" "jx_c_start" 0 0 0 rotate -90 -90 0
$attachment "HEADFOCUS" "def_c_neckB" 0 0 0 rotate -90 -90 0
$attachment "HEADSHOT" "def_c_head" 0 0 0 rotate -90 -90 0
$attachment "CHESTFOCUS" "def_c_spineC" 0 0 0 rotate -90 -90 0
$attachment "PROPGUN" "ja_c_propGun" 0 0 0 rotate -90 -90 0
$attachment "VDU" "jx_c_camera" 0 0 0 rotate -90 -90 0
$attachment "L_HAND" "ja_l_propHand" 0 0 0 rotate 0 0 0
$attachment "R_HAND" "ja_r_propHand" 0 0 0 rotate 0 0 0
$attachment "ORIGIN" "jx_c_delta" 0 0 0 rotate -90 -90 0
$attachment "foot_L_sole" "def_l_ankle" 0 0 0 rotate 0 0 0
$attachment "foot_R_sole" "def_r_ankle" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -12.273 -24.091 -3.159 11.081 24.091 73.868

$hboxset "default"
$hbox 3 "def_c_hip" -8.487779 -7.432269 -6.419672 8.487779 -0.259842 6.419672 ""
$hbox 2 "def_c_neckA" -5.93109 0.125984 -6.546837 5.93109 3.253537 4.463771 ""
$hbox 1 "def_c_neckB" -4.197236 -3.048813 3.509442 4.197236 6.814553 5.775185 ""
$hbox 1 "def_c_neckB" -5.198021 -1.115746 -5.868098 5.198021 8.319275 4.448023 ""
$hbox 3 "def_c_spineA" -8.098409 0 -6.561404 8.098409 5.59054 6.561404 ""
$hbox 3 "def_c_spineB" -8.098409 0 -6.561404 8.098409 5.55117 6.561404 ""
$hbox 2 "def_c_spineC" -8.45707 -0.112992 -8.436991 8.45707 8.860218 7.276757 ""
$hbox 6 "def_l_ankle" -2.683853 -2.82401 -2.818498 2.607869 2.82401 2.818498 ""
$hbox 6 "def_l_ball" -2.101177 -0.120079 -2.818498 4.225582 3.787788 2.818498 ""
$hbox 4 "def_l_elbow" -2.082673 -3.08149 -1.983461 10.077932 3.08149 1.983461 ""
$hbox 6 "def_l_knee" 0 -4.383456 -3.50393 17.311777 4.383456 3.50393 ""
$hbox 4 "def_l_shoulder" -1.976768 -3.457867 -2.64094 11.110608 3.457867 2.64094 ""
$hbox 6 "def_l_thigh" 0 -4.23385 -3.842906 18.172012 5.373218 3.842906 ""
$hbox 4 "def_l_wrist" -0.281102 -1.56732 -1.558658 4.255109 0.825983 1.862201 ""
$hbox 7 "def_r_ankle" -2.607869 -2.82401 -2.818498 2.683853 2.82401 2.818498 ""
$hbox 7 "def_r_ball" -4.225582 -3.804323 -2.818498 2.101177 0.103543 2.818498 ""
$hbox 5 "def_r_elbow" -10.078327 -3.08149 -1.983461 2.082673 3.081884 1.983461 ""
$hbox 7 "def_r_knee" -17.311777 -4.383456 -3.50393 0 4.383456 3.50393 ""
$hbox 5 "def_r_shoulder" -11.100765 -3.457867 -2.64094 1.986217 3.457867 2.64094 ""
$hbox 7 "def_r_thigh" -18.172012 -5.373218 -3.842906 0 4.23385 3.842906 ""
$hbox 5 "def_r_wrist" -4.255503 -0.825983 -1.862201 0.281102 1.567713 1.558658 ""
$hbox 1 "def_c_head" -2.389365 -6.197625 0.915353 2.389365 -0.738975 4.97125 ""
$hbox 1 "def_c_head" -2.191334 -1.288186 3.938969 2.191334 2.88149 6.08109 ""
$hbox 1 "def_c_head" -2.443696 -3.336608 -5.300383 2.443696 2.54842 -3.845268 ""
$hbox 1 "def_c_head" -2.804325 1.687792 -2.713381 2.804325 4.177157 3.911803 ""
$hbox 1 "def_c_head" -3.917709 -3.348025 -3.852355 3.917709 2.550782 3.933457 ""
$hbox 1 "def_c_head" -2.069287 -6.102744 4.963376 2.069287 -2.68779 6.2055 ""
$hbox 2 "def_c_neckA" -3.599599 0.33307 -4.669676 3.599599 4.963769 3.804717 ""
$hbox 2 "def_c_spineC" -7.513371 0.003543 -6.315342 7.513371 8.838566 6.079122 ""
$hbox 3 "def_c_hip" -7.513371 -7.049199 -6.197232 7.513371 0.000394 6.197232 ""
$hbox 3 "def_c_spineA" -7.513371 0 -6.197232 7.513371 5.59054 6.197232 ""
$hbox 3 "def_c_spineB" -7.513371 0 -6.197232 7.513371 5.55117 6.197232 ""
$hbox 4 "def_l_shoulder" -2.066138 -2.014563 -2.835034 11.231867 2.014563 2.835034 ""
$hbox 4 "def_l_elbow" -1.651965 -1.791335 -1.64606 9.750375 1.791335 1.64606 ""
$hbox 4 "def_l_wrist" -0.291732 -1.342123 -1.670075 3.675583 0.581495 1.894484 ""
$hbox 5 "def_r_shoulder" -11.215726 -2.014563 -2.835034 2.081886 2.014563 2.835034 ""
$hbox 5 "def_r_elbow" -9.74998 -1.791335 -1.64606 1.651965 1.791335 1.64606 ""
$hbox 5 "def_r_wrist" -3.675583 -0.581495 -1.894484 0.291732 1.342123 1.670075 ""
$hbox 6 "def_l_thigh" 0 -2.208657 -3.148813 18.097996 4.371645 3.148813 ""
$hbox 6 "def_l_knee" 0 -2.686215 -3.148813 17.311777 2.686215 3.148813 ""
$hbox 6 "def_l_ankle" -2.103145 -1.918107 -2.531885 3.188576 1.918107 2.531885 ""
$hbox 6 "def_l_ball" -1.637005 -0.124016 -2.520074 3.419285 2.612987 2.520074 ""
$hbox 7 "def_r_thigh" -18.097996 -4.371251 -3.148813 0 2.208657 3.148813 ""
$hbox 7 "def_r_knee" -17.311777 -2.686215 -3.148813 0 2.686215 3.148813 ""
$hbox 7 "def_r_ankle" -3.188576 -1.918107 -2.531885 2.103145 1.918107 2.531885 ""
$hbox 7 "def_r_ball" -3.418891 -2.615349 -2.520074 1.636611 0.121653 2.520074 ""
$hbox 1 "def_c_head" -2.389365 -6.197625 0.915353 2.389365 -0.738975 4.97125 ""
$hbox 1 "def_c_head" -2.191334 -1.288186 3.938969 2.191334 2.88149 6.08109 ""
$hbox 1 "def_c_head" -2.443696 -3.336608 -5.300383 2.443696 2.54842 -3.845268 ""
$hbox 1 "def_c_head" -2.804325 1.687792 -2.713381 2.804325 4.177157 3.911803 ""
$hbox 1 "def_c_head" -3.917315 -3.350387 -5.350383 3.917315 2.551176 5.43306 ""
$hbox 1 "def_c_head" -2.069287 -6.102744 4.963376 2.069287 -2.68779 6.2055 ""
$hbox 1 "def_c_head" -3.598418 -7.515733 -6.2992 3.598418 -2.885821 2.299208 ""
$hbox 2 "def_c_spineC" -7.511796 -0.496062 -6.314949 7.511796 7.338568 6.078728 ""
$hbox 3 "def_c_hip" -7.513371 -7.049199 -6.197232 7.513371 0.000394 6.197232 ""
$hbox 3 "def_c_spineA" -7.513371 0 -6.197232 7.513371 5.59054 6.197232 ""
$hbox 3 "def_c_spineB" -7.513371 0 -6.197232 7.513371 5.55117 6.197232 ""
$hbox 4 "def_l_shoulder" -2.066138 -2.014563 -2.835034 11.231867 2.014563 2.835034 ""
$hbox 4 "def_l_elbow" -1.651965 -1.791335 -1.64606 9.750375 1.791335 1.64606 ""
$hbox 4 "def_l_wrist" -0.291732 -1.342123 -1.670075 3.675583 0.581495 1.894484 ""
$hbox 5 "def_r_shoulder" -11.215726 -2.014563 -2.835034 2.081886 2.014563 2.835034 ""
$hbox 5 "def_r_elbow" -9.74998 -1.791335 -1.64606 1.651965 1.791335 1.64606 ""
$hbox 5 "def_r_wrist" -3.675583 -0.581495 -1.894484 0.291732 1.342123 1.670075 ""
$hbox 6 "def_l_thigh" 0 -2.208657 -3.148813 18.097996 4.371645 3.148813 ""
$hbox 6 "def_l_knee" 0 -2.686215 -3.148813 17.311777 2.686215 3.148813 ""
$hbox 6 "def_l_ankle" -2.103145 -1.918107 -2.531885 3.188576 1.918107 2.531885 ""
$hbox 6 "def_l_ball" -1.637005 -0.124016 -2.520074 3.419285 2.612987 2.520074 ""
$hbox 7 "def_r_thigh" -18.097996 -4.371251 -3.148813 0 2.208657 3.148813 ""
$hbox 7 "def_r_knee" -17.311777 -2.686215 -3.148813 0 2.686215 3.148813 ""
$hbox 7 "def_r_ankle" -3.188576 -1.918107 -2.531885 2.103145 1.918107 2.531885 ""
$hbox 7 "def_r_ball" -3.418891 -2.615349 -2.520074 1.636611 0.121653 2.520074 ""
$hbox 1 "def_c_head" -3.982669 -3.10708 -5.731091 3.982669 6.545656 4.677943 ""
$hbox 2 "def_c_neckA" -2.537003 -0.029134 -2.432672 2.537003 1.337005 3.101568 ""
$hbox 2 "def_c_spineC" -6.705893 0 -5.230305 6.705893 9.785808 5.049202 ""
$hbox 3 "def_c_hip" -7.545654 -3.373222 -5.146446 7.545654 0.889368 5.146446 ""
$hbox 3 "def_c_spineA" -6.924789 0 -5.146446 6.924789 7.326757 5.146446 ""
$hbox 3 "def_c_spineB" -6.705893 0 -5.104714 6.705893 5.08503 5.104714 ""
$hbox 4 "def_l_shoulder" -1.968894 -1.592517 -1.661808 11.015332 1.592517 1.661808 ""
$hbox 4 "def_l_elbow" 0 -1.592517 -1.670469 8.980691 1.592517 1.653146 ""
$hbox 4 "def_l_wrist" -0.312598 -1.597241 -1.648816 5.555107 0.635826 1.704327 ""
$hbox 5 "def_r_shoulder" -10.927931 -1.592517 -1.661808 2.056295 1.592517 1.661808 ""
$hbox 5 "def_r_elbow" -8.980297 -1.592517 -1.653146 0 1.592123 1.670469 ""
$hbox 5 "def_r_wrist" -5.555501 -0.635826 -1.704327 0.312991 1.597635 1.648422 ""
$hbox 6 "def_l_thigh" 0 -3.081884 -2.94527 15.393669 3.081884 2.94527 ""
$hbox 6 "def_l_knee" 0 -2.875585 -3.064955 16.67477 2.875585 3.064955 ""
$hbox 6 "def_l_ankle" -2.515743 -2.058657 -1.977555 3.28897 2.058657 1.977555 ""
$hbox 6 "def_l_ball" -1.376769 -0.181889 -1.977555 3.501174 3.935031 1.977555 ""
$hbox 7 "def_r_thigh" -15.393669 -3.081884 -2.94527 0 3.081884 2.94527 ""
$hbox 7 "def_r_knee" -16.67477 -2.875585 -3.064955 0 2.875585 3.064955 ""
$hbox 7 "def_r_ankle" -3.28897 -2.058657 -1.977555 2.515743 2.058657 1.977555 ""
$hbox 7 "def_r_ball" -3.501174 -3.938181 -1.977555 1.376769 0.179134 1.977555 ""
$hboxset "default"
$hbox 3 "def_c_hip" -8.24644 -7.823213 -6.693688 8.24644 0.085433 6.693688 ""
$hbox 2 "def_c_neckA" -3.961016 0.075984 -3.683457 3.961016 3.80078 4.722826 ""
$hbox 1 "def_c_neckB" -3.576371 -1.004329 -7.018096 3.576371 5.824398 8.120063 ""
$hbox 3 "def_c_spineA" -8.389354 0 -6.687388 8.389354 6.149594 6.687388 ""
$hbox 3 "def_c_spineB" -8.389354 0 -6.687388 8.389354 6.106287 6.687388 ""
$hbox 2 "def_c_spineC" -8.725574 0.118897 -6.686995 8.725574 9.777539 6.686995 ""
$hbox 6 "def_l_ankle" -1.201966 -2.641333 -2.641333 7.023608 2.641333 2.641333 ""
$hbox 6 "def_l_ball" -3.191332 -2.660231 -2.660231 5.527942 2.660231 2.660231 ""
$hbox 4 "def_l_elbow" -3.894874 -1.635824 -1.635824 10.914545 1.635824 1.635824 ""
$hbox 6 "def_l_knee" 0.392519 -3.368891 -3.368891 18.649961 3.368891 3.368891 ""
$hbox 4 "def_l_shoulder" -2.76968 -2.424798 -2.424798 12.63462 2.424798 2.424798 ""
$hbox 6 "def_l_thigh" -0.684251 -1.917319 -4.054323 20.673582 3.170466 4.054323 ""
$hbox 4 "def_l_wrist" -0.598424 -1.367714 -1.755508 4.02322 0.551967 2.089366 ""
$hbox 7 "def_r_ankle" -7.023608 -2.641333 -2.641333 1.201966 2.641333 2.641333 ""
$hbox 7 "def_r_ball" -5.527942 -2.660231 -2.660231 3.191332 2.660231 2.660231 ""
$hbox 5 "def_r_elbow" -10.914545 -1.635824 -1.635824 3.894874 1.635824 1.635824 ""
$hbox 7 "def_r_knee" -18.649961 -3.368891 -3.368891 -0.392519 3.368891 3.368891 ""
$hbox 5 "def_r_shoulder" -12.623203 -2.424798 -2.424798 2.780703 2.424798 2.424798 ""
$hbox 7 "def_r_thigh" -20.673582 -3.170466 -4.054323 0.684251 1.917319 4.054323 ""
$hbox 5 "def_r_wrist" -4.023614 -0.551967 -2.089366 0.598424 1.368107 1.755508 ""
$hbox 8 "def_c_spineC" -5.62676 -4.834636 -12.27281 5.62676 6.736994 -6.911404 ""
$skipboneinbbox

$screenalign def_l_clav "sphere"
$screenalign def_l_shoulderTwist "sphere"
$screenalign def_l_elbowB "sphere"
$screenalign def_l_shoulderMid "sphere"
$screenalign def_l_elbow "cylinder"
$screenalign def_l_wrist "sphere"
$screenalign def_l_finIndexA "cylinder"
$screenalign def_l_finIndexB "sphere"
$screenalign def_l_finMidA "sphere"
$screenalign def_l_finMidB "cylinder"
$screenalign def_l_finMidC "cylinder"
$screenalign def_l_finThumbA "cylinder"
$screenalign def_l_finThumbC "sphere"
$screenalign def_l_finRingCarpal "sphere"
$screenalign def_l_finRingB "sphere"
$screenalign def_l_finRingC "sphere"
$screenalign def_l_finPinkyA "cylinder"
$screenalign def_l_finPinkyB "cylinder"
$screenalign def_l_finPinkyC "cylinder"
$screenalign def_r_clav "sphere"
$screenalign def_r_shoulderMid "sphere"
$screenalign def_r_elbow "sphere"
$screenalign def_r_wrist "sphere"
$screenalign def_r_finIndexA "sphere"
$screenalign def_r_finIndexB "sphere"
$screenalign def_r_finIndexC "cylinder"
$screenalign def_r_finMidA "sphere"
$screenalign def_r_finMidB "sphere"
$screenalign def_r_finMidC "sphere"
$screenalign def_r_finThumbA "cylinder"
$screenalign def_r_finThumbC "cylinder"
$screenalign def_r_finRingCarpal "cylinder"
$screenalign def_r_finRingA "sphere"
$screenalign def_r_finPinkyA "sphere"
$screenalign def_r_finPinkyB "sphere"
$screenalign def_r_finPinkyC "sphere"
$screenalign def_l_thigh "sphere"
$screenalign def_l_knee "sphere"
$screenalign def_l_ankle "sphere"
$screenalign def_l_ball "sphere"
$screenalign def_l_kneeB "sphere"
$screenalign def_r_thigh "sphere"
$screenalign def_r_ankle "cylinder"
$screenalign def_r_kneeB "sphere"
$screenalign ja_l_propHand "cylinder"
$screenalign ja_r_propHand "sphere"

$definebone "jx_c_delta" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_pov" "jx_c_delta" 0 62.992001 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_camera" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hip" "jx_c_delta" 0 39.369999 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_start" "jx_c_delta" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineA" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineB" "def_c_spineA" 0 5.590542 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineC" "def_c_spineB" 0 5.55117 0 0 0 0 0 0 0 0 0 0
$definebone "ja_c_propGun" "def_c_spineC" 0 -7.204712 9.8425 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckA" "def_c_spineC" 0 8.503922 -0.23622 0 0 0 0 0 0 0 0 0
$definebone "jx_c_neckB" "def_c_neckA" 0 4.370071 0.94488 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckB" "jx_c_neckB" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_head" "def_c_neckB" 0 3.936996 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_clav" "def_c_spineC" 1.176218 6.023808 -0.588109 6.983374 3.661928 0.44582 0 0 0 0 0 0
$definebone "def_l_shoulder" "def_l_clav" 5.448854 0.000011 0 -4.860232 -48.915267 4.890265 0 0 0 0 0 0
$definebone "def_l_shoulderTwist" "def_l_shoulder" 0 0 0 0 0.000002 0 0 0 0 0 0 0
$definebone "def_l_elbowB" "def_l_shoulder" 11.630213 -0.000008 0.000027 -44.997331 -0.027096 0.877916 0 0 0 0 0 0
$definebone "def_l_shoulderMid" "def_l_shoulder" 4.890762 0.000004 0 -2.688722 -0.057131 0.006099 0 0 0 0 0 0
$definebone "def_l_elbow" "def_l_shoulderMid" 6.444214 -0.000004 0 -37.014561 0.164812 0.006865 0 0 0 0 0 0
$definebone "def_l_forearm" "def_l_elbow" 4.63045 0.000011 0.000002 -5.291108 -0.116958 0.007797 0 0 0 0 0 0
$definebone "def_l_wrist" "def_l_elbow" 9.956749 -0.010864 0.493276 -5.403714 -0.039456 -0.000075 0 0 0 0 0 0
$definebone "def_l_finIndexA" "def_l_wrist" 3.077315 -0.138939 1.24732 -3.532782 -45.109219 3.539624 0 0 0 0 0 0
$definebone "def_l_finIndexB" "def_l_finIndexA" 1.748371 0 0.000002 -0.001187 -45.000005 0.001192 0 0 0 0 0 0
$definebone "def_l_finIndexC" "def_l_finIndexB" 1.19545 -0.000003 0.000002 0.000615 -45.000008 -0.000614 0 0 0 0 0 0
$definebone "def_l_finMidA" "def_l_wrist" 3.080781 -0.067951 0.349253 6.351203 -45.354918 -6.390478 0 0 0 0 0 0
$definebone "def_l_finMidB" "def_l_finMidA" 1.836349 0.000002 0.000002 0.000002 -45.000005 0.000002 0 0 0 0 0 0
$definebone "def_l_finMidC" "def_l_finMidB" 1.309196 -0.000001 0.000008 -0.002988 -45.000008 0.00298 0 0 0 0 0 0
$definebone "def_l_finThumbA" "def_l_wrist" 0.504171 -0.563503 0.770155 -42.349748 -57.483275 126.990511 0 0 0 0 0 0
$definebone "def_l_finThumbB" "def_l_finThumbA" 2.132282 0.000006 0.000004 3.259416 -22.647167 2.460338 0 0 0 0 0 0
$definebone "def_l_finThumbC" "def_l_finThumbB" 1.240841 -0.000003 0 0.074487 -45.185656 0.008913 0 0 0 0 0 0
$definebone "def_l_finRingCarpal" "def_l_wrist" 2.513066 -0.138184 -0.333538 17.995868 0.000025 0.000075 0 0 0 0 0 0
$definebone "def_l_finRingA" "def_l_finRingCarpal" 0.316793 0.000004 -0.000001 0.003163 -44.999994 -0.003168 0 0 0 0 0 0
$definebone "def_l_finRingB" "def_l_finRingA" 1.966316 0.000002 -0.000002 0.000002 -45.000001 0.000001 0 0 0 0 0 0
$definebone "def_l_finRingC" "def_l_finRingB" 1.00687 0.000001 0.000008 0.000598 -45.000008 -0.000594 0 0 0 0 0 0
$definebone "def_l_finPinkyA" "def_l_finRingCarpal" -0.030562 -0.172359 -0.590865 18.727351 -48.299806 -19.816788 0 0 0 0 0 0
$definebone "def_l_finPinkyB" "def_l_finPinkyA" 1.644444 -0.000002 0 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_l_finPinkyC" "def_l_finPinkyB" 0.763287 -0.000002 0 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_r_clav" "def_c_spineC" -1.176218 6.024002 -0.588109 -6.983374 -3.661928 -179.554171 0 0 0 0 0 0
$definebone "def_r_shoulder" "def_r_clav" -5.448845 0.000145 0 -4.860235 -48.915264 4.890268 0 0 0 0 0 0
$definebone "def_r_shoulderTwist" "def_r_shoulder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_elbowB" "def_r_shoulder" -11.630196 0.000011 -0.000028 -44.997327 -0.027091 0.877916 0 0 0 0 0 0
$definebone "def_r_shoulderMid" "def_r_shoulder" -4.890709 -0.000069 -0.000002 -2.688722 -0.057138 0.006099 0 0 0 0 0 0
$definebone "def_r_elbow" "def_r_shoulderMid" -6.444286 0.00013 0.000005 -37.014561 0.164812 0.006865 0 0 0 0 0 0
$definebone "def_r_forearm" "def_r_elbow" -4.630386 -0.000137 -0.000053 -5.291104 -0.116958 0.007796 0 0 0 0 0 0
$definebone "def_r_wrist" "def_r_elbow" -9.956816 0.010937 -0.493216 -5.403711 -0.039457 -0.000077 0 0 0 0 0 0
$definebone "def_r_finIndexA" "def_r_wrist" -3.077376 0.138977 -1.247286 -3.532781 -45.109219 3.539621 0 0 0 0 0 0
$definebone "def_r_finIndexB" "def_r_finIndexA" -1.748192 0.000002 -0.000114 -0.001197 -45.000001 0.001184 0 0 0 0 0 0
$definebone "def_r_finIndexC" "def_r_finIndexB" -1.195347 0.00008 -0.000078 0.000611 -45.000005 -0.000613 0 0 0 0 0 0
$definebone "def_r_finMidA" "def_r_wrist" -3.08066 0.067764 -0.349348 6.351203 -45.354908 -6.390478 0 0 0 0 0 0
$definebone "def_r_finMidB" "def_r_finMidA" -1.836304 -0.000002 -0.00005 -0.000003 -44.999994 0.000005 0 0 0 0 0 0
$definebone "def_r_finMidC" "def_r_finMidB" -1.309258 -0.000061 0.000052 -0.002987 -45.000008 0.002984 0 0 0 0 0 0
$definebone "def_r_finThumbA" "def_r_wrist" -0.504133 0.563412 -0.770212 -42.349741 -57.483255 126.990511 0 0 0 0 0 0
$definebone "def_r_finThumbB" "def_r_finThumbA" -2.132332 0.000069 -0.00008 3.25942 -22.647166 2.460342 0 0 0 0 0 0
$definebone "def_r_finThumbC" "def_r_finThumbB" -1.240768 -0.000023 0.00005 0.074482 -45.185656 0.008905 0 0 0 0 0 0
$definebone "def_r_finRingCarpal" "def_r_wrist" -2.513052 0.138145 0.333541 17.995867 0.000031 0.000083 0 0 0 0 0 0
$definebone "def_r_finRingA" "def_r_finRingCarpal" -0.316674 -0.000145 -0.000084 0.003161 -45.000001 -0.003161 0 0 0 0 0 0
$definebone "def_r_finRingB" "def_r_finRingA" -1.966396 0.000031 0.000019 0.000002 -45.000005 0.000004 0 0 0 0 0 0
$definebone "def_r_finRingC" "def_r_finRingB" -1.006874 -0.000014 -0.000002 0.000599 -45.000005 -0.000595 0 0 0 0 0 0
$definebone "def_r_finPinkyA" "def_r_finRingCarpal" 0.030523 0.172421 0.590875 18.727346 -48.299795 -19.816788 0 0 0 0 0 0
$definebone "def_r_finPinkyB" "def_r_finPinkyA" -1.644104 -0.000021 0.00001 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_r_finPinkyC" "def_r_finPinkyB" -0.763535 -0.000238 -0.000006 0 -45.000001 0 0 0 0 0 0 0
$definebone "def_l_thigh" "def_c_hip" 5.219006 -1.00618 -0.600196 -0.050695 -90.000003 90.000003 0 0 0 0 0 0
$definebone "def_l_knee" "def_l_thigh" 18.098003 0 0 0 -3.72269 0 0 0 0 0 0 0
$definebone "def_l_ankle" "def_l_knee" 17.311804 0 0 -3.795738 61.268573 0 0 0 0 0 0 0
$definebone "def_l_ball" "def_l_ankle" 5.292377 0 0 0.427673 29.592491 1.875762 0 0 0 0 0 0
$definebone "def_l_kneeB" "def_l_thigh" 18.246761 1.130153 0 0 -7.498168 0 0 0 0 0 0 0
$definebone "def_r_thigh" "def_c_hip" -5.219006 -1.00618 -0.600196 0.050695 90.000003 -90.000003 0 0 0 0 0 0
$definebone "def_r_knee" "def_r_thigh" -18.098003 0 0 0 -3.72269 0 0 0 0 0 0 0
$definebone "def_r_ankle" "def_r_knee" -17.311804 0 0 -3.795738 61.268573 0 0 0 0 0 0 0
$definebone "def_r_ball" "def_r_ankle" -5.292377 0 0 0.427673 29.592491 1.875761 0 0 0 0 0 0
$definebone "def_r_kneeB" "def_r_thigh" -18.246761 -1.130153 0 0 -7.498168 -0.000001 0 0 0 0 0 0
$definebone "ja_l_propHand" "def_l_wrist" 4.441361 -1.883156 0.77133 0.000002 0 -0.000002 0 0 0 0 0 0
$definebone "ja_r_propHand" "def_r_wrist" -4.441751 1.88372 -0.770998 0.000002 0 0.000003 0 0 0 0 0 0
$definebone "def_fc_c_jaw_1" "def_c_head" 0.000008 -3.528931 1.714772 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_jaw_2" "def_c_head" -0.002348 -5.904533 4.421052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_nose_1" "def_c_head" -0.000222 -1.906204 5.126512 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_nose_2" "def_c_head" -0.000014 -2.56337 5.497591 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_1" "def_c_head" 0.000008 -3.896217 1.86384 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_2" "def_c_head" 0.000008 -3.781494 3.033485 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_3" "def_c_head" 0.000008 -4.107208 4.160108 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_1" "def_c_head" 0.187538 -4.486393 4.876977 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_2" "def_c_head" 0.714897 -4.453117 4.719345 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_3" "def_c_head" 1.01442 -4.33876 4.225265 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_4" "def_c_head" 1.217984 -5.240444 4.107803 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_1" "def_c_head" 0.316672 -0.401428 4.700243 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_2" "def_c_head" 0.729493 -0.26873 4.664347 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_3" "def_c_head" 1.52846 -0.217766 4.366918 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_4" "def_c_head" 2.391509 -0.44352 3.275908 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_1" "def_c_head" 0.281779 -1.435074 4.650091 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_2" "def_c_head" 0.554045 -1.595055 4.504138 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_3" "def_c_head" 1.314057 -2.258446 4.347957 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_4" "def_c_head" 1.849152 -2.377121 4.039434 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_5" "def_c_head" 2.300972 -1.677475 3.350968 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_6" "def_c_head" 2.839564 -1.334602 2.411699 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_1" "def_c_head" 1.26353 -1.073029 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_2" "def_c_head" 1.26353 -1.073418 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_3" "def_c_head" 1.26353 -1.073814 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_forehead_1" "def_c_head" 0.565769 0.634354 4.519776 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_forehead_2" "def_c_head" 1.638682 1.018105 3.771194 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_1" "def_c_head" 2.086407 -3.40559 3.642359 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_2" "def_c_head" 2.6396 -2.433846 0.748599 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_3" "def_c_head" 3.312682 -1.020157 -0.649023 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_mustache_1" "def_c_head" 0.295735 -3.25177 4.951944 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_mustache_2" "def_c_head" 0.865967 -3.347313 4.613052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_neck_1" "def_c_head" 0.508073 -7.319633 1.372036 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_neck_2" "def_c_head" 1.413078 -5.992386 1.191715 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_1" "def_c_head" 0.812187 -2.579361 4.895335 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_2" "def_c_head" 0.662534 -2.266006 4.638642 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_3" "def_c_head" 1.249506 -2.995415 4.387953 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_4" "def_c_head" 1.564873 -3.679466 4.16363 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_5" "def_c_head" 1.514009 -4.425018 4.054327 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_1" "def_c_head" 0.224988 -3.668037 5.156847 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_2" "def_c_head" 0.731265 -3.800255 4.86531 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_3" "def_c_head" 1.048409 -3.885151 4.371408 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_4" "def_c_head" 1.217984 -4.143848 4.08142 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_1" "def_c_head" -0.187538 -4.486393 4.876977 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_2" "def_c_head" -0.714897 -4.453117 4.719345 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_3" "def_c_head" -1.01442 -4.33876 4.225265 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_4" "def_c_head" -1.217984 -5.240444 4.107803 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_1" "def_c_head" -0.316672 -0.401428 4.700243 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_2" "def_c_head" -0.729493 -0.26873 4.664347 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_3" "def_c_head" -1.52846 -0.217766 4.366918 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_4" "def_c_head" -2.391509 -0.44352 3.275908 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_1" "def_c_head" -0.281779 -1.435074 4.650091 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_2" "def_c_head" -0.554045 -1.595055 4.504138 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_3" "def_c_head" -1.314057 -2.258446 4.347957 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_4" "def_c_head" -1.849152 -2.377121 4.039434 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_5" "def_c_head" -2.300972 -1.677475 3.350968 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_6" "def_c_head" -2.839564 -1.334602 2.411699 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_1" "def_c_head" -1.26353 -1.073029 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_2" "def_c_head" -1.26353 -1.073418 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_3" "def_c_head" -1.26353 -1.073814 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_forehead_1" "def_c_head" -0.565769 0.634354 4.519776 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_forehead_2" "def_c_head" -1.638682 1.018105 3.771194 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_1" "def_c_head" -2.086407 -3.40559 3.642359 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_2" "def_c_head" -2.6396 -2.433846 0.748599 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_3" "def_c_head" -3.312682 -1.020157 -0.649023 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_mustache_1" "def_c_head" -0.295735 -3.25177 4.951944 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_mustache_2" "def_c_head" -0.865967 -3.347313 4.613052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_neck_1" "def_c_head" -0.508073 -7.319633 1.372036 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_neck_2" "def_c_head" -1.413078 -5.992386 1.191715 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_1" "def_c_head" -0.812187 -2.579361 4.895335 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_2" "def_c_head" -0.662534 -2.266006 4.638642 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_3" "def_c_head" -1.249506 -2.995415 4.387953 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_4" "def_c_head" -1.564873 -3.679466 4.16363 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_5" "def_c_head" -1.514009 -4.425018 4.054327 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_1" "def_c_head" -0.224988 -3.668037 5.156847 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_2" "def_c_head" -0.731265 -3.800255 4.86531 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_3" "def_c_head" -1.048409 -3.885151 4.371408 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_4" "def_c_head" -1.217984 -4.143848 4.08142 0 0 0 0 0 0 0 0 0

$bonemerge "def_l_clav"
$bonemerge "def_l_shoulder"
$bonemerge "def_l_shoulderTwist"
$bonemerge "def_l_elbowB"
$bonemerge "def_l_shoulderMid"
$bonemerge "def_l_elbow"
$bonemerge "def_l_forearm"
$bonemerge "def_l_wrist"
$bonemerge "def_l_finIndexA"
$bonemerge "def_l_finIndexB"
$bonemerge "def_l_finIndexC"
$bonemerge "def_l_finMidA"
$bonemerge "def_l_finMidB"
$bonemerge "def_l_finMidC"
$bonemerge "def_l_finRingCarpal"
$bonemerge "def_l_finRingA"
$bonemerge "def_l_finRingB"
$bonemerge "def_l_finRingC"
$bonemerge "def_l_finPinkyA"
$bonemerge "def_l_finPinkyB"
$bonemerge "def_l_finPinkyC"
$bonemerge "def_r_clav"
$bonemerge "def_r_shoulder"
$bonemerge "def_r_shoulderTwist"
$bonemerge "def_r_elbowB"
$bonemerge "def_r_shoulderMid"
$bonemerge "def_r_elbow"
$bonemerge "def_r_forearm"
$bonemerge "def_r_wrist"
$bonemerge "def_r_finIndexA"
$bonemerge "def_r_finIndexB"
$bonemerge "def_r_finIndexC"
$bonemerge "def_r_finMidA"
$bonemerge "def_r_finMidB"
$bonemerge "def_r_finMidC"
$bonemerge "def_r_finRingCarpal"
$bonemerge "def_r_finRingA"
$bonemerge "def_r_finRingB"
$bonemerge "def_r_finRingC"
$bonemerge "def_r_finPinkyA"
$bonemerge "def_r_finPinkyB"
$bonemerge "def_r_finPinkyC"
$bonemerge "def_l_ankle"
$bonemerge "def_l_ball"
$bonemerge "def_r_ankle"
$bonemerge "def_r_ball"
$bonemerge "ja_l_propHand"
$bonemerge "ja_r_propHand"


$bonesaveframe "def_l_clav" position rotation
$bonesaveframe "def_l_shoulder" position rotation
$bonesaveframe "def_l_shoulderTwist" position rotation
$bonesaveframe "def_l_elbowB" position
$bonesaveframe "def_l_shoulderMid" position rotation
$bonesaveframe "def_l_elbow" rotation
$bonesaveframe "def_l_forearm" position
$bonesaveframe "def_l_wrist" position
$bonesaveframe "def_l_finIndexA" position
$bonesaveframe "def_l_finIndexB" position
$bonesaveframe "def_l_finIndexC" position
$bonesaveframe "def_l_finMidA" rotation
$bonesaveframe "def_l_finMidB" rotation
$bonesaveframe "def_l_finMidC" rotation
$bonesaveframe "def_l_finThumbA" position
$bonesaveframe "def_l_finRingCarpal" position rotation
$bonesaveframe "def_l_finRingA" position rotation
$bonesaveframe "def_l_finRingB" position rotation
$bonesaveframe "def_l_finRingC" position rotation
$bonesaveframe "def_l_finPinkyA" position rotation
$bonesaveframe "def_l_finPinkyB" position rotation
$bonesaveframe "def_l_finPinkyC" position rotation
$bonesaveframe "def_r_clav" position rotation
$bonesaveframe "def_r_shoulder" position rotation
$bonesaveframe "def_r_shoulderTwist" position rotation
$bonesaveframe "def_r_elbowB" position
$bonesaveframe "def_r_shoulderMid" position rotation
$bonesaveframe "def_r_elbow" rotation
$bonesaveframe "def_r_forearm" position
$bonesaveframe "def_r_wrist" position
$bonesaveframe "def_r_finIndexA" position
$bonesaveframe "def_r_finIndexB" position
$bonesaveframe "def_r_finIndexC" position
$bonesaveframe "def_r_finMidA" rotation
$bonesaveframe "def_r_finMidB" rotation
$bonesaveframe "def_r_finMidC" rotation
$bonesaveframe "def_r_finThumbA" position
$bonesaveframe "def_r_finRingCarpal" position rotation
$bonesaveframe "def_r_finRingA" position rotation
$bonesaveframe "def_r_finRingB" position rotation
$bonesaveframe "def_r_finRingC" position rotation
$bonesaveframe "def_r_finPinkyA" position rotation
$bonesaveframe "def_r_finPinkyB" position rotation
$bonesaveframe "def_r_finPinkyC" position rotation
$bonesaveframe "def_l_thigh" position
$bonesaveframe "def_l_knee" position
$bonesaveframe "def_l_ankle" position rotation
$bonesaveframe "def_l_ball" rotation
$bonesaveframe "def_l_kneeB" position
$bonesaveframe "def_r_thigh" position
$bonesaveframe "def_r_knee" position
$bonesaveframe "def_r_ankle" position rotation
$bonesaveframe "def_r_ball" rotation
$bonesaveframe "ja_l_propHand" position
$bonesaveframe "ja_r_propHand" position

$weightlist "weights_add_face_melee_charge_skit" {
	 "jx_c_delta" 0
	 "jx_c_pov" 0
	 "jx_c_camera" 0
	 "def_c_hip" 0
	 "jx_c_start" 0
	 "def_c_spineA" 0
	 "def_c_spineB" 0
	 "def_c_spineC" 0
	 "ja_c_propGun" 0
	 "def_c_neckA" 0
	 "jx_c_neckB" 0
	 "def_c_neckB" 0
	 "def_c_head" 1
	 "def_l_clav" 0
	 "def_l_shoulder" 0
	 "def_l_shoulderTwist" 0
	 "def_l_elbowB" 0
	 "def_l_shoulderMid" 0
	 "def_l_elbow" 0
	 "def_l_forearm" 0
	 "def_l_wrist" 0
	 "def_l_finIndexA" 0
	 "def_l_finIndexB" 0
	 "def_l_finIndexC" 0
	 "def_l_finMidA" 0
	 "def_l_finMidB" 0
	 "def_l_finMidC" 0
	 "def_l_finThumbA" 0
	 "def_l_finThumbB" 0
	 "def_l_finThumbC" 0
	 "def_l_finRingCarpal" 0
	 "def_l_finRingA" 0
	 "def_l_finRingB" 0
	 "def_l_finRingC" 0
	 "def_l_finPinkyA" 0
	 "def_l_finPinkyB" 0
	 "def_l_finPinkyC" 0
	 "def_r_clav" 0
	 "def_r_shoulder" 0
	 "def_r_shoulderTwist" 0
	 "def_r_elbowB" 0
	 "def_r_shoulderMid" 0
	 "def_r_elbow" 0
	 "def_r_forearm" 0
	 "def_r_wrist" 0
	 "def_r_finIndexA" 0
	 "def_r_finIndexB" 0
	 "def_r_finIndexC" 0
	 "def_r_finMidA" 0
	 "def_r_finMidB" 0
	 "def_r_finMidC" 0
	 "def_r_finThumbA" 0
	 "def_r_finThumbB" 0
	 "def_r_finThumbC" 0
	 "def_r_finRingCarpal" 0
	 "def_r_finRingA" 0
	 "def_r_finRingB" 0
	 "def_r_finRingC" 0
	 "def_r_finPinkyA" 0
	 "def_r_finPinkyB" 0
	 "def_r_finPinkyC" 0
	 "def_l_thigh" 0
	 "def_l_knee" 0
	 "def_l_ankle" 0
	 "def_l_ball" 0
	 "def_l_kneeB" 0
	 "def_r_thigh" 0
	 "def_r_knee" 0
	 "def_r_ankle" 0
	 "def_r_ball" 0
	 "def_r_kneeB" 0
	 "ja_l_propHand" 0
	 "ja_r_propHand" 0
	 "def_fc_c_jaw_1" 1
	 "def_fc_c_jaw_2" 1
	 "def_fc_c_nose_1" 1
	 "def_fc_c_nose_2" 1
	 "def_fc_c_tongue_1" 1
	 "def_fc_c_tongue_2" 1
	 "def_fc_c_tongue_3" 1
	 "def_fc_l_botlip_1" 1
	 "def_fc_l_botlip_2" 1
	 "def_fc_l_botlip_3" 1
	 "def_fc_l_botlip_4" 1
	 "def_fc_l_brow_1" 1
	 "def_fc_l_brow_2" 1
	 "def_fc_l_brow_3" 1
	 "def_fc_l_brow_4" 1
	 "def_fc_l_cheek_1" 1
	 "def_fc_l_cheek_2" 1
	 "def_fc_l_cheek_3" 1
	 "def_fc_l_cheek_4" 1
	 "def_fc_l_cheek_5" 1
	 "def_fc_l_cheek_6" 1
	 "def_fc_l_eye_1" 1
	 "def_fc_l_eye_2" 1
	 "def_fc_l_eye_3" 1
	 "def_fc_l_forehead_1" 1
	 "def_fc_l_forehead_2" 1
	 "def_fc_l_jaw_1" 1
	 "def_fc_l_jaw_2" 1
	 "def_fc_l_jaw_3" 1
	 "def_fc_l_mustache_1" 1
	 "def_fc_l_mustache_2" 1
	 "def_fc_l_neck_1" 1
	 "def_fc_l_neck_2" 1
	 "def_fc_l_nose_1" 1
	 "def_fc_l_nose_2" 1
	 "def_fc_l_nose_3" 1
	 "def_fc_l_nose_4" 1
	 "def_fc_l_nose_5" 1
	 "def_fc_l_toplip_1" 1
	 "def_fc_l_toplip_2" 1
	 "def_fc_l_toplip_3" 1
	 "def_fc_l_toplip_4" 1
	 "def_fc_r_botlip_1" 1
	 "def_fc_r_botlip_2" 1
	 "def_fc_r_botlip_3" 1
	 "def_fc_r_botlip_4" 1
	 "def_fc_r_brow_1" 1
	 "def_fc_r_brow_2" 1
	 "def_fc_r_brow_3" 1
	 "def_fc_r_brow_4" 1
	 "def_fc_r_cheek_1" 1
	 "def_fc_r_cheek_2" 1
	 "def_fc_r_cheek_3" 1
	 "def_fc_r_cheek_4" 1
	 "def_fc_r_cheek_5" 1
	 "def_fc_r_cheek_6" 1
	 "def_fc_r_eye_1" 1
	 "def_fc_r_eye_2" 1
	 "def_fc_r_eye_3" 1
	 "def_fc_r_forehead_1" 1
	 "def_fc_r_forehead_2" 1
	 "def_fc_r_jaw_1" 1
	 "def_fc_r_jaw_2" 1
	 "def_fc_r_jaw_3" 1
	 "def_fc_r_mustache_1" 1
	 "def_fc_r_mustache_2" 1
	 "def_fc_r_neck_1" 1
	 "def_fc_r_neck_2" 1
	 "def_fc_r_nose_1" 1
	 "def_fc_r_nose_2" 1
	 "def_fc_r_nose_3" 1
	 "def_fc_r_nose_4" 1
	 "def_fc_r_nose_5" 1
	 "def_fc_r_toplip_1" 1
	 "def_fc_r_toplip_2" 1
	 "def_fc_r_toplip_3" 1
	 "def_fc_r_toplip_4" 1
}

$animation "face_neutral_skit" "pete_skits_anims\face_neutral_skit.smd" {
	fps 30
}

$sequence "add_face_idle_casual_skit" {
	"pete_skits_anims\add_face_idle_casual_skit.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_focused_skit" {
	"pete_skits_anims\add_face_focused_skit.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_fierce_skit" {
	"pete_skits_anims\add_face_fierce_skit.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_Poised_skit" {
	"pete_skits_anims\add_face_Poised_skit.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_pain_skit" {
	"pete_skits_anims\add_face_pain_skit.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_surprise_skit" {
	"pete_skits_anims\add_face_surprise_skit.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_melee_charge_skit" {
	"pete_skits_anims\add_face_melee_charge_skit.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_add_face_melee_charge_skit"
}

$sequence "pt_fight_knockback_zinger_A" {
	"pete_skits_anims\pt_fight_knockback_zinger_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 64 "signal:aiskit_doomed" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 83 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_SV_VSCRIPT_CALLBACK 84 "kill" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_fight_knockback_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_dying_knockback_diag_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_fight_knockback_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_dying_knockback_diag_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 42 "ai_skit_pt_dying_knockback_diag_Loser_Pt3" }
	{ event AE_CL_PLAYSOUND 51 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_fight_knockback_zinger_A_idle" {
	"pete_skits_anims\pt_fight_knockback_zinger_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_fight_knockback_zinger_B" {
	"pete_skits_anims\pt_fight_knockback_zinger_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 120 "signal:aiskit_alertbreakout" }
	{ event AE_CL_PLAYSOUND 14 "ai_skit_pt_dying_knockback_diag_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 15 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_pt_dying_knockback_diag_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 58 "ai_skit_pt_fight_knockback_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 64 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_fight_knockback_zinger_B_idle" {
	"pete_skits_anims\pt_fight_knockback_zinger_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_wounded_drag_zinger_A" {
	"pete_skits_anims\pt_wounded_drag_zinger_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_dontbreakout" }
	{ event AE_SV_VSCRIPT_CALLBACK 290 "kill" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_wounded_drag_diag_Victim_Pt1" }
	{ event AE_CL_PLAYSOUND 23 "ai_skit_pt_wounded_drag_Pt2" }
	{ event AE_CL_PLAYSOUND 30 "ai_skit_pt_wounded_drag_diag_Victim_Pt2" }
	{ event AE_CL_PLAYSOUND 61 "ai_skit_pt_wounded_drag_diag_Victim_Pt3" }
	{ event AE_CL_PLAYSOUND 69 "ai_skit_pt_wounded_drag_Pt3" }
	{ event AE_CL_PLAYSOUND 91 "ai_skit_pt_wounded_drag_diag_Victim_Pt4" }
	{ event AE_CL_PLAYSOUND 105 "ai_skit_pt_wounded_drag_Pt4" }
	{ event AE_CL_PLAYSOUND 129 "ai_skit_pt_wounded_drag_diag_Victim_Pt5" }
	{ event AE_CL_PLAYSOUND 147 "ai_skit_pt_wounded_drag_Pt5" }
	{ event AE_CL_PLAYSOUND 154 "ai_skit_pt_wounded_drag_diag_Victim_Pt6" }
	{ event AE_CL_PLAYSOUND 186 "ai_skit_pt_wounded_drag_diag_Victim_Pt7" }
	{ event AE_CL_PLAYSOUND 193 "ai_skit_pt_wounded_drag_Pt6" }
	{ event AE_CL_PLAYSOUND 217 "ai_skit_pt_wounded_drag_diag_Victim_Pt8" }
	{ event AE_CL_PLAYSOUND 238 "ai_skit_pt_wounded_drag_Pt7" }
	{ event AE_CL_PLAYSOUND 246 "ai_skit_pt_wounded_drag_diag_Victim_Pt9" }
	{ event AE_CL_PLAYSOUND 270 "ai_skit_pt_wounded_drag_Pt8" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_wounded_drag_zinger_A_idle" {
	"pete_skits_anims\pt_wounded_drag_zinger_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_wounded_drag_zinger_B" {
	"pete_skits_anims\pt_wounded_drag_zinger_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 115 "signal:aiskit_alertbreakout" }
	{ event AE_NPC_SET_STANCE 19 "crouch" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_wounded_drag_Pt1" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_wounded_drag_zinger_B_idle" {
	"pete_skits_anims\pt_wounded_drag_zinger_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_dying_wallslide_zinger" {
	"pete_skits_anims\pt_dying_wallslide_zinger.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 63 "kill" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_dying_wallslide_zinger_Pt1" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_dying_wallslide_zinger_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 31 "ai_skit_pt_dying_wallslide_zinger_Pt2" }
	{ event AE_CL_PLAYSOUND 45 "ai_skit_pt_dying_wallslide_zinger_diag_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 62 "ai_skit_pt_dying_wallslide_zinger_diag_Grunt_Pt3" }
	{ event AE_CL_PLAYSOUND 65 "Phys_Imp_Bodyfall_Human_Hard_Default" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_dying_wallslide_zinger_idle" {
	"pete_skits_anims\pt_dying_wallslide_zinger_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_wounded_carry_zinger_A" {
	"pete_skits_anims\pt_wounded_carry_zinger_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_dontbreakout" }
	{ event AE_SV_VSCRIPT_CALLBACK 50 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 81 "kill" }
	{ event AE_CL_PLAYSOUND 51 "ai_skit_pt_wounded_carry_zinger_Victim_Pt1" }
	{ event AE_CL_PLAYSOUND 70 "ai_skit_pt_wounded_carry_zinger_Victim_Pt2" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_wounded_carry_zinger_A_idle" {
	"pete_skits_anims\pt_wounded_carry_zinger_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_wounded_carry_zinger_B" {
	"pete_skits_anims\pt_wounded_carry_zinger_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 68 "signal:aiskit_alertbreakout" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_wounded_carry_zinger_Pt1" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_wounded_carry_zinger_diag_Carrier_Pt1" }
	{ event AE_CL_PLAYSOUND 29 "ai_skit_pt_wounded_carry_zinger_diag_Carrier_Pt2" }
	{ event AE_CL_PLAYSOUND 47 "ai_skit_pt_wounded_carry_zinger_diag_Carrier_Pt3" }
	{ event AE_CL_PLAYSOUND 73 "ai_skit_pt_wounded_carry_zinger_diag_Carrier_Pt4" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_wounded_carry_zinger_B_idle" {
	"pete_skits_anims\pt_wounded_carry_zinger_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_prisoner_kill_zinger_A" {
	"pete_skits_anims\pt_prisoner_kill_zinger_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_dontbreakout" }
	{ event AE_SV_VSCRIPT_CALLBACK 2 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "kill" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_prisoner_kill_zinger_A_idle" {
	"pete_skits_anims\pt_prisoner_kill_zinger_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_prisoner_kill_zinger_B" {
	"pete_skits_anims\pt_prisoner_kill_zinger_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_alertbreakout" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_prisoner_kill_zinger_Pt1" }
	{ event AE_CL_PLAYSOUND 31 "ai_skit_pt_prisoner_kill_zinger_Pt2" }
	{ event AE_CL_PLAYSOUND 65 "ai_skit_pt_prisoner_kill_zinger_Pt3" }
	{ event AE_CL_PLAYSOUND 75 "ai_skit_pt_prisoner_kill_zinger_Pt4" }
	{ event AE_CL_PLAYSOUND 93 "ai_skit_pt_prisoner_kill_zinger_Pt5" }
	{ event AE_FOOTSTEP_L 146 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_prisoner_kill_zinger_B_idle" {
	"pete_skits_anims\pt_prisoner_kill_zinger_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_shotgun_wallslam_skit_A" {
	"pete_skits_anims\pt_shotgun_wallslam_skit_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 14 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "signal:aiskit_forcedeathonskitend" }
	{ event AE_SV_VSCRIPT_CALLBACK 52 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_shotgun_wallslam_skit_A_idle" {
	"pete_skits_anims\pt_shotgun_wallslam_skit_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_shotgun_wallslam_skit_B" {
	"pete_skits_anims\pt_shotgun_wallslam_skit_B.smd"
	{ event AE_NPC_WEAPON_FIRE 12 "" }
	{ event AE_SV_VSCRIPT_CALLBACK 12 "shotgunfired" }
	{ event AE_SV_VSCRIPT_CALLBACK 35 "signal:aiskit_alertbreakout" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_shotgun_wallslam_skit_B_idle" {
	"pete_skits_anims\pt_shotgun_wallslam_skit_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "sp_spectre_speedkill_skit" {
	"pete_skits_anims\sp_spectre_speedkill_skit.smd"
	{ event AE_NPC_WEAPON_FIRE 37 "" }
	{ event AE_NPC_WEAPON_FIRE 49 "" }
	{ event AE_NPC_WEAPON_FIRE 41 "" }
	{ event AE_NPC_WEAPON_FIRE 42 "" }
	{ event AE_NPC_WEAPON_FIRE 43 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_spectre_speedkill_skit_idle" {
	"pete_skits_anims\sp_spectre_speedkill_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_speedkill_skit_A" {
	"pete_skits_anims\pt_spectre_speedkill_skit_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 45 "signal:aiskit_doomed" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 78 "P_skit_blood_punch follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 84 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_SV_VSCRIPT_CALLBACK 94 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_spectre_speedkill_skit_A_idle" {
	"pete_skits_anims\pt_spectre_speedkill_skit_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_speedkill_skit_B" {
	"pete_skits_anims\pt_spectre_speedkill_skit_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 42 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 59 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_spectre_speedkill_skit_B_idle" {
	"pete_skits_anims\pt_spectre_speedkill_skit_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "sp_spectre_kill_skit" {
	"pete_skits_anims\sp_spectre_kill_skit.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 40 "signal:aiskit_alertbreakout" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_spectre_kill_skit_idle" {
	"pete_skits_anims\sp_spectre_kill_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_kill_skit" {
	"pete_skits_anims\pt_spectre_kill_skit.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "signal:aiskit_doomed" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 38 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_SV_VSCRIPT_CALLBACK 38 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_spectre_kill_skit_idle" {
	"pete_skits_anims\pt_spectre_kill_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "sp_barslam_skit_loop" {
	"pete_skits_anims\sp_barslam_skit_loop.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_barslam_skit_loop" {
	"pete_skits_anims\pt_barslam_skit_loop.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_barslam_skit_end" {
	"pete_skits_anims\sp_barslam_skit_end.smd"
	{ event AE_CL_PLAYSOUND 0 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 19 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 28 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 26 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_sp_tablesmash_skit_Spectre_Throw" }
	{ event AE_CL_PLAYSOUND 49 "ai_skit_sp_barslam_skit_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 65 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 72 "Spectre.Servo.HeadPivot.Long" }
	{ event AE_CL_PLAYSOUND 79 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 86 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 86 "ai_skit_sp_barslam_skit_BodyGrab" }
	{ event AE_CL_PLAYSOUND 91 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_L 102 "" }
	{ event AE_CL_PLAYSOUND 105 "ai_skit_sp_spectre_railing_smash_Spectre_LastSmash" }
	{ event AE_CL_PLAYSOUND 130 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 138 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_R 147 "" }
	{ event AE_CL_PLAYSOUND 149 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 162 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_L 168 "" }
	{ event AE_CL_PLAYSOUND 175 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 182 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 190 "Spectre.Servo.Light.Short" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_barslam_skit_end" {
	"pete_skits_anims\pt_barslam_skit_end.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_forcedeathonskitend" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 47 "P_skit_bar_hit follow_attachment ORIGIN" }
	{ event AE_SV_VSCRIPT_CALLBACK 106 "signal:aiskit_doomed" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 132 "P_skit_bar_land follow_attachment CHESTFOCUS" }
	{ event AE_SV_VSCRIPT_CALLBACK 134 "kill" }
	{ event AE_CL_PLAYSOUND 46 "ai_skit_sp_barslam_skit_BodyImpact" }
	{ event AE_CL_PLAYSOUND 106 "ai_skit_sp_barslam_skit_BodySlide" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "sp_tablesmash_skit_loop" {
	"pete_skits_anims\sp_tablesmash_skit_loop.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_tablesmash_skit_loop" {
	"pete_skits_anims\pt_tablesmash_skit_loop.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_tablesmash_skit_end" {
	"pete_skits_anims\sp_tablesmash_skit_end.smd"
	{ event AE_CL_PLAYSOUND 0 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 9 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 18 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 30 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 41 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_sp_tablesmash_skit_Spectre_Throw" }
	{ event AE_CL_PLAYSOUND 48 "ai_skit_sp_tablesmash_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 59 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 66 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 70 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 79 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 93 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 105 "Spectre.Servo.Light.Short" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_tablesmash_skit_end" {
	"pete_skits_anims\pt_tablesmash_skit_end.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_forcedeathonskitend" }
	{ event AE_SV_VSCRIPT_CALLBACK 42 "signal:aiskit_doomed" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 51 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_SV_VSCRIPT_CALLBACK 56 "kill" }
	{ event AE_CL_PLAYSOUND 49 "ai_skit_sp_tablesmash_skit_Bodyfall" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_loot_corpse_skit" {
	"pete_skits_anims\pt_loot_corpse_skit.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "kill" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_loot_corpse_skit_idle" {
	"pete_skits_anims\pt_loot_corpse_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_loot_corpse_skit_A" {
	"pete_skits_anims\pt_loot_corpse_skit_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 124 "signal:aiskit_alertbreakout" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_loot_corpse_skit_Looter_Pt1" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_pt_loot_corpse_skit_Looter_Pt2" }
	{ event AE_CL_PLAYSOUND 88 "ai_skit_pt_loot_corpse_skit_Looter_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_skit" 0 0 0 0
	fps 30
}

$sequence "pt_loot_corpse_skit_A_idle" {
	"pete_skits_anims\pt_loot_corpse_skit_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_loot_corpse_skit_B" {
	"pete_skits_anims\pt_loot_corpse_skit_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_alertbreakout" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_FOOTSTEP_L 42 "" }
	{ event AE_FOOTSTEP_R 97 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_skit" 0 0 0 0
	fps 30
}

$sequence "pt_loot_corpse_skit_B_idle" {
	"pete_skits_anims\pt_loot_corpse_skit_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_brawl_A_skit" {
	"pete_skits_anims\pt_brawl_A_skit.smd"
	{ event AE_NPC_SET_STANCE 267 "crouch" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 280 "P_skit_blood_sm follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 283 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_SV_VSCRIPT_CALLBACK 284 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_brawl_A_skit_idle" {
	"pete_skits_anims\pt_brawl_A_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_brawl_B_skit" {
	"pete_skits_anims\pt_brawl_B_skit.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 113 "P_skit_blood_punch follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 117 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_brawl_B_skit_idle" {
	"pete_skits_anims\pt_brawl_B_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_brawl_C_skit" {
	"pete_skits_anims\pt_brawl_C_skit.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 7 "P_skit_blood_punch follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 12 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_NPC_SET_STANCE 73 "crouch" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 70 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_NPC_SET_STANCE 149 "stand" }
	{ event AE_SV_VSCRIPT_CALLBACK 176 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 177 "signal:aiskit_dontbreakout" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 205 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_SV_VSCRIPT_CALLBACK 212 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_brawl_C_skit_idle" {
	"pete_skits_anims\pt_brawl_C_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "sp_blindfire_idle_skit" {
	"pete_skits_anims\sp_blindfire_idle_skit.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_blindfire_idle_skit" {
	"pete_skits_anims\pt_blindfire_idle_skit.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_blindfire_skit" {
	"pete_skits_anims\sp_blindfire_skit.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 140 "signal:aiskit_dontbreakout" }
	{ event AE_NPC_WEAPON_FIRE 154 "" }
	{ event AE_NPC_WEAPON_FIRE 159 "" }
	{ event AE_NPC_WEAPON_FIRE 162 "" }
	{ event AE_CL_PLAYSOUND 0 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 34 "Spectre.Servo.Walk" }
	{ event AE_FOOTSTEP_L 59 "" }
	{ event AE_FOOTSTEP_L 94 "" }
	{ event AE_FOOTSTEP_L 117 "" }
	{ event AE_CL_PLAYSOUND 138 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 169 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 186 "Spectre.Servo.HeadPivot.Short" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_blindfire_skit" {
	"pete_skits_anims\pt_blindfire_skit.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 2 "signal:aiskit_dontbreakout" }
	{ event AE_SV_VSCRIPT_CALLBACK 161 "kill" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_sp_blindfire_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_sp_blindfire_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 45 "ai_skit_sp_blindfire_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 92 "ai_skit_sp_blindfire_diag_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 93 "ai_skit_sp_blindfire_Grunt_Pt3" }
	{ event AE_CL_PLAYSOUND 126 "ai_skit_sp_blindfire_Grunt_Pt4" }
	{ event AE_CL_PLAYSOUND 134 "ai_skit_sp_blindfire_diag_Grunt_Pt3" }
	{ event AE_CL_PLAYSOUND 165 "ai_skit_sp_blindfire_Grunt_Pt5" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "sp_spectre_chestpunch_idle" {
	"pete_skits_anims\sp_spectre_chestpunch_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_chestpunch_idle" {
	"pete_skits_anims\pt_spectre_chestpunch_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_spectre_chestpunch" {
	"pete_skits_anims\sp_spectre_chestpunch.smd"
	{ event AE_CL_PLAYSOUND 0 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 3 "ai_skit_sp_spectre_chestpunch_Spectre_Pt1" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_sp_spectre_chestpunch_Spectre_Pt2" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 34 "P_skit_blood_md follow_attachment R_HAND" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 40 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_PLAYSOUND 50 "ai_skit_sp_spectre_chestpunch_Spectre_Pt3" }
	{ event AE_CL_PLAYSOUND 77 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 111 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 127 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 140 "Spectre.Step.Light.Default" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_spectre_chestpunch" {
	"pete_skits_anims\pt_spectre_chestpunch.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 33 "signal:aiskit_forcedeathonskitend" }
	{ event AE_SV_VSCRIPT_CALLBACK 33 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 34 "signal:aiskit_dontbreakout" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 34 "P_skit_blood_loop follow_attachment CHESTFOCUS" }
	{ event AE_SV_VSCRIPT_CALLBACK 72 "kill" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_sp_spectre_chestpunch_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 72 "ai_skit_sp_spectre_chestpunch_Grunt_Pt2" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "sp_street_execution" {
	"pete_skits_anims\sp_street_execution.smd"
	{ event AE_NPC_WEAPON_FIRE 25 "" }
	{ event AE_NPC_WEAPON_FIRE 27 "" }
	{ event AE_NPC_WEAPON_FIRE 29 "" }
	{ event AE_CL_PLAYSOUND 3 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 34 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 38 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 61 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 93 "Spectre.Servo.Walk" }
	{ event AE_CL_PLAYSOUND 97 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_R 111 "" }
	{ event AE_FOOTSTEP_L 129 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_street_execution_idle" {
	"pete_skits_anims\sp_street_execution_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_street_execution_A" {
	"pete_skits_anims\pt_street_execution_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_forcedeathonskitend" }
	{ event AE_SV_VSCRIPT_CALLBACK 68 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 69 "signal:aiskit_dontbreakout" }
	{ event AE_SV_VSCRIPT_CALLBACK 86 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_street_execution_idle_A" {
	"pete_skits_anims\pt_street_execution_idle_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_street_execution_B" {
	"pete_skits_anims\pt_street_execution_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "signal:aiskit_forcedeathonskitend" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 34 "impact_flesh start_at_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 36 "impact_flesh start_at_attachment CHESTFOCUS" }
	{ event AE_SV_VSCRIPT_CALLBACK 34 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 35 "signal:aiskit_dontbreakout" }
	{ event AE_SV_VSCRIPT_CALLBACK 59 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_street_execution_idle_B" {
	"pete_skits_anims\pt_street_execution_idle_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "sp_spectre_dumpbody_skit" {
	"pete_skits_anims\sp_spectre_dumpbody_skit.smd"
	{ event AE_CL_PLAYSOUND 3 "Spectre.Servo.Walk" }
	{ event AE_FOOTSTEP_L 14 "" }
	{ event AE_FOOTSTEP_R 36 "" }
	{ event AE_FOOTSTEP_L 56 "" }
	{ event AE_CL_PLAYSOUND 60 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 71 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 82 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 98 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 112 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 126 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 140 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 148 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 163 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 180 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 197 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_L 180 "" }
	{ event AE_FOOTSTEP_L 229 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_spectre_dumpbody_skit_idle" {
	"pete_skits_anims\sp_spectre_dumpbody_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_dumpbody_skit" {
	"pete_skits_anims\pt_spectre_dumpbody_skit.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 113 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_spectre_dumpbody_skit_idle" {
	"pete_skits_anims\pt_spectre_dumpbody_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "sp_spectre_windowtoss" {
	"pete_skits_anims\sp_spectre_windowtoss.smd"
	{ event AE_CL_PLAYSOUND 0 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 12 "Spectre.Servo.Walk" }
	{ event AE_CL_PLAYSOUND 20 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 21 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 22 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 24 "ai_skit_sp_spectre_windowtoss_Headbutt" }
	{ event AE_CL_PLAYSOUND 26 "ai_skit_sp_spectre_windowtoss_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 31 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 48 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 62 "ai_skit_sp_tablesmash_skit_Spectre_Throw" }
	{ event AE_CL_PLAYSOUND 62 "Spectre.Servo.Walk" }
	{ event AE_FOOTSTEP_L 65 "" }
	{ event AE_CL_PLAYSOUND 77 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 80 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 87 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 97 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 105 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 117 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 135 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 144 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 144 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 159 "Spectre.Servo.Walk" }
	{ event AE_CL_PLAYSOUND 151 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_L 166 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_spectre_windowtoss_idle" {
	"pete_skits_anims\sp_spectre_windowtoss_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_windowtoss" {
	"pete_skits_anims\pt_spectre_windowtoss.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 26 "signal:aiskit_forcedeathonskitend" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 28 "P_skit_blood_punch follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 34 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_SV_VSCRIPT_CALLBACK 62 "geo_intersect_begin" }
	{ event AE_SV_VSCRIPT_CALLBACK 64 "signal:aiskit_doomed" }
	{ event AE_CL_PLAYSOUND 68 "corporate_dropshiprodeo_pilotscream" }
	{ event AE_SV_VSCRIPT_CALLBACK 82 "geo_intersect_end" }
	{ event AE_SV_VSCRIPT_CALLBACK 85 "scripted_death_to_ragdoll" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_spectre_windowtoss_idle" {
	"pete_skits_anims\pt_spectre_windowtoss_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_spectre_railing_smash" {
	"pete_skits_anims\sp_spectre_railing_smash.smd"
	{ event AE_CL_PLAYSOUND 0 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 2 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 5 "ai_skit_sp_spectre_railing_smash_Impact1" }
	{ event AE_CL_PLAYSOUND 6 "ai_skit_sp_spectre_railing_smash_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 19 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 40 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 43 "ai_skit_sp_spectre_railing_smash_Impact2" }
	{ event AE_CL_PLAYSOUND 45 "ai_skit_sp_spectre_railing_smash_diag_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 52 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 53 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 71 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 87 "ai_skit_sp_spectre_railing_smash_Spectre_LastSmash" }
	{ event AE_CL_PLAYSOUND 90 "ai_skit_sp_spectre_railing_smash_Impact3" }
	{ event AE_CL_PLAYSOUND 104 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 116 "Spectre.Servo.Walk" }
	{ event AE_CL_PLAYSOUND 120 "Spectre.Servo.HeadPivot.Long" }
	{ event AE_CL_PLAYSOUND 128 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_R 137 "" }
	{ event AE_CL_PLAYSOUND 144 "Spectre.Servo.HeadPivot.Short" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_spectre_railing_smash_idle" {
	"pete_skits_anims\sp_spectre_railing_smash_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_railing_smash" {
	"pete_skits_anims\pt_spectre_railing_smash.smd"
	{ event AE_NPC_SET_STANCE 1 "crouch" }
	{ event AE_SV_VSCRIPT_CALLBACK 8 "signal:aiskit_forcedeathonskitend" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 8 "P_skit_blood_sm follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 12 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 45 "P_skit_blood_sm follow_attachment HEADFOCUS" }
	{ event AE_SV_VSCRIPT_CALLBACK 91 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 92 "signal:aiskit_dontbreakout" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 92 "P_skit_blood_sm follow_attachment HEADFOCUS" }
	{ event AE_SV_VSCRIPT_CALLBACK 141 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_spectre_railing_smash_idle" {
	"pete_skits_anims\pt_spectre_railing_smash_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_curbstomp_idle_skit" {
	"pete_skits_anims\sp_curbstomp_idle_skit.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_curbstomp_idle_skit" {
	"pete_skits_anims\pt_curbstomp_idle_skit.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_curbstomp_skit" {
	"pete_skits_anims\sp_curbstomp_skit.smd"
	{ event AE_CL_PLAYSOUND 1 "ai_skit_sp_curbstomp_Spectre_Pt1" }
	{ event AE_CL_PLAYSOUND 49 "ai_skit_sp_curbstomp_Spectre_Pt2" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 80 "P_skit_spark_curb follow_attachment foot_L_sole" }
	{ event AE_CL_PLAYSOUND 101 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 102 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 98 "ai_skit_sp_curbstomp_Spectre_Pt3" }
	{ event AE_FOOTSTEP_R 118 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_curbstomp_skit" {
	"pete_skits_anims\pt_curbstomp_skit.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 2 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 3 "signal:aiskit_dontbreakout" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 31 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_SV_VSCRIPT_CALLBACK 73 "kill" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_sp_curbstomp_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 14 "ai_skit_sp_curbstomp_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 29 "ai_skit_sp_curbstomp_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 57 "ai_skit_sp_curbstomp_Grunt_Pt3" }
	{ event AE_CL_PLAYSOUND 58 "ai_skit_sp_curbstomp_diag_Grunt_Pt2" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 74 "P_skit_blood_curb follow_attachment headfocus" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 78 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_PLAYSOUND 86 "ai_skit_sp_curbstomp_Grunt_Pt4" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "sp_spectre_crawl_idle" {
	"pete_skits_anims\sp_spectre_crawl_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_crawl_idle" {
	"pete_skits_anims\pt_spectre_crawl_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_spectre_crawl" {
	"pete_skits_anims\sp_spectre_crawl.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 2 "signal:aiskit_dontbreakout" }
	{ event AE_SV_VSCRIPT_CALLBACK 182 "kill" }
	{ event AE_CL_PLAYSOUND 0 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 0 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 10 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 22 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 28 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 29 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 33 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 39 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 48 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 50 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 10 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 53 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 59 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 63 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 67 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 69 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 79 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 81 "Spectre.Servo.Light.Short" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 98 "P_skit_spark_curb follow_attachment R_HAND" }
	{ event AE_CL_PLAYSOUND 97 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 104 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 120 "DataKnife_Hack_Spectre_ArmorRattle" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 122 "P_skit_spark_curb follow_attachment HEADFOCUS" }
	{ event AE_CL_PLAYSOUND 149 "DataKnife_Hack_Spectre_ArmorRattle" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 151 "P_skit_spark_curb follow_attachment HEADFOCUS" }
	{ event AE_CL_PLAYSOUND 178 "DataKnife_Hack_Spectre_ArmorRattle" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 180 "P_skit_spark_curb follow_attachment HEADFOCUS" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_spectre_crawl" {
	"pete_skits_anims\pt_spectre_crawl.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 174 "signal:aiskit_dontbreakout" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_sp_spectre_crawl_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 35 "ai_skit_sp_spectre_crawl_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 46 "ai_skit_sp_spectre_crawl_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 85 "ai_skit_sp_spectre_crawl_diag_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 92 "ai_skit_sp_spectre_crawl_Grunt_Pt3" }
	{ event AE_CL_PLAYSOUND 116 "ai_skit_sp_spectre_crawl_Grunt_Pt4" }
	{ event AE_CL_PLAYSOUND 117 "ai_skit_sp_spectre_crawl_diag_Grunt_Pt3" }
	{ event AE_CL_PLAYSOUND 141 "ai_skit_sp_spectre_crawl_diag_Grunt_Pt4" }
	{ event AE_CL_PLAYSOUND 144 "ai_skit_sp_spectre_crawl_Grunt_Pt5" }
	{ event AE_CL_PLAYSOUND 167 "ai_skit_sp_spectre_crawl_diag_Grunt_Pt5" }
	{ event AE_CL_PLAYSOUND 173 "ai_skit_sp_spectre_crawl_Grunt_Pt6" }
	{ event AE_CL_PLAYSOUND 208 "ai_skit_sp_spectre_crawl_diag_Grunt_Pt6" }
	{ event AE_CL_PLAYSOUND 212 "ai_skit_sp_spectre_crawl_Grunt_Pt7" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_spectre_zombiedrag_idle" {
	"pete_skits_anims\pt_spectre_zombiedrag_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
	loop
}

$sequence "sp_spectre_zombiedrag_idle" {
	"pete_skits_anims\sp_spectre_zombiedrag_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_spectre_zombiedrag" {
	"pete_skits_anims\pt_spectre_zombiedrag.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 58 "signal:aiskit_dontbreakout" }
	{ event AE_NPC_SET_STANCE 73 "crouch" }
	{ event AE_NPC_WEAPON_FIRE 80 "" }
	{ event AE_NPC_SET_STANCE 190 "stand" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_sp_spectre_zombiedrag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 26 "ai_skit_sp_spectre_zombiedrag_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 54 "ai_skit_sp_spectre_zombiedrag_Grunt_Pt3" }
	{ event AE_CL_PLAYSOUND 72 "ai_skit_sp_spectre_zombiedrag_Grunt_Pt4" }
	{ event AE_CL_PLAYSOUND 73 "ai_skit_sp_spectre_zombiedrag_diag_Grunt_Pt1" }
	{ event AE_CL_PLAYSOUND 107 "ai_skit_sp_spectre_zombiedrag_Grunt_Pt5" }
	{ event AE_CL_PLAYSOUND 113 "ai_skit_sp_spectre_zombiedrag_diag_Grunt_Pt2" }
	{ event AE_CL_PLAYSOUND 129 "ai_skit_sp_spectre_zombiedrag_Grunt_Pt6" }
	{ event AE_CL_PLAYSOUND 160 "ai_skit_sp_spectre_zombiedrag_diag_Grunt_Pt3" }
	{ event AE_FOOTSTEP_R 170 "" }
	{ event AE_FOOTSTEP_R 186 "" }
	{ event AE_CL_PLAYSOUND 186 "ai_skit_sp_spectre_zombiedrag_Grunt_Pt7" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "sp_spectre_zombiedrag" {
	"pete_skits_anims\sp_spectre_zombiedrag.smd"
	{ event AE_NPC_SET_STANCE 1 "crouch" }
	{ event AE_NPC_SET_STANCE 38 "stand" }
	{ event AE_SV_VSCRIPT_CALLBACK 80 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 81 "signal:aiskit_dontbreakout" }
	{ event AE_SV_VSCRIPT_CALLBACK 90 "kill" }
	{ event AE_CL_PLAYSOUND 1 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 3 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 19 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 21 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 36 "Spectre.Servo.Walk" }
	{ event AE_CL_PLAYSOUND 42 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 43 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_L 51 "" }
	{ event AE_CL_PLAYSOUND 69 "Spectre.Step.Light.Default" }
	{ event AE_FOOTSTEP_L 77 "" }
	{ event AE_CL_PLAYSOUND 75 "ai_skit_sp_spectre_zombiedrag_Spectre_Pt2" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_fight_flip_skit_A_idle" {
	"pete_skits_anims\pt_fight_flip_skit_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_fight_flip_skit_B_idle" {
	"pete_skits_anims\pt_fight_flip_skit_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_fight_flip_skit_A" {
	"pete_skits_anims\pt_fight_flip_skit_A.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 23 "P_skit_blood_punch follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 27 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 78 "" }
	{ event AE_SV_VSCRIPT_CALLBACK 78 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 79 "signal:aiskit_dontbreakout" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 110 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 157 "" }
	{ event AE_CL_PLAYSOUND 109 "ai_skit_pt_fight_flip_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_fight_flip_diag_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 39 "ai_skit_pt_fight_flip_diag_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 84 "ai_skit_pt_fight_flip_diag_Loser_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_fight_flip_skit_B" {
	"pete_skits_anims\pt_fight_flip_skit_B.smd"
	{ event AE_NPC_WEAPON_FIRE 149 "" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_fight_flip_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 20 "ai_skit_pt_fight_flip_diag_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 20 "ai_skit_pt_fight_flip_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 39 "ai_skit_pt_fight_flip_diag_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 50 "ai_skit_pt_fight_flip_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 58 "ai_skit_pt_fight_flip_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 73 "ai_skit_pt_fight_flip_diag_Winner_Pt4" }
	{ event AE_CL_PLAYSOUND 124 "ai_skit_pt_fight_flip_Winner_Pt4" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_prisoner_drag_zinger_A" {
	"pete_skits_anims\pt_prisoner_drag_zinger_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_prisoner_drag_zinger_B" {
	"pete_skits_anims\pt_prisoner_drag_zinger_B.smd"
	{ event AE_NPC_WEAPON_FIRE 118 "" }
	{ event AE_NPC_WEAPON_FIRE 119 "" }
	{ event AE_NPC_WEAPON_FIRE 120 "" }
	{ event AE_NPC_WEAPON_FIRE 121 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_skit" 0 0 0 0
	fps 30
}

$sequence "pt_prisoner_drag_zinger_C" {
	"pete_skits_anims\pt_prisoner_drag_zinger_C.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_skit" 0 0 0 0
	fps 30
}

$sequence "pt_prisoner_drag_zinger_A_idle" {
	"pete_skits_anims\pt_prisoner_drag_zinger_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_prisoner_drag_zinger_B_idle" {
	"pete_skits_anims\pt_prisoner_drag_zinger_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_prisoner_drag_zinger_C_idle" {
	"pete_skits_anims\pt_prisoner_drag_zinger_C_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "sp_spectre_salvage_skit_B" {
	"pete_skits_anims\sp_spectre_salvage_skit_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_spectre_salvage_skit_A" {
	"pete_skits_anims\sp_spectre_salvage_skit_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_spectre_salvage_skit_B_idle" {
	"pete_skits_anims\sp_spectre_salvage_skit_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_marvin_dragbody_skit_A" {
	"pete_skits_anims\pt_marvin_dragbody_skit_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_marvin_dragbody_skit_B" {
	"pete_skits_anims\pt_marvin_dragbody_skit_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_marvin_dragbody_skit_A_idle" {
	"pete_skits_anims\pt_marvin_dragbody_skit_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_marvin_dragbody_skit_B_idle" {
	"pete_skits_anims\pt_marvin_dragbody_skit_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_marvin_CPR_skit" {
	"pete_skits_anims\pt_marvin_CPR_skit.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_marvin_CPRkill_skit" {
	"pete_skits_anims\pt_marvin_CPRkill_skit.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_skit" 0 0 0 0
	fps 30
}

$sequence "pt_marvin_CPR_skit_idle" {
	"pete_skits_anims\pt_marvin_CPR_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_marvin_CPRkill_skit_idle" {
	"pete_skits_anims\pt_marvin_CPRkill_skit_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_roomcheck_X_left" {
	"pete_skits_anims\pt_roomcheck_X_left.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_roomcheck_X_right" {
	"pete_skits_anims\pt_roomcheck_X_right.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_roomcheck_left" {
	"pete_skits_anims\pt_roomcheck_left.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_roomcheck_right" {
	"pete_skits_anims\pt_roomcheck_right.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_cover2cover_left" {
	"pete_skits_anims\pt_cover2cover_left.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_cover2cover_right" {
	"pete_skits_anims\pt_cover2cover_right.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_cornercheck_signal_left" {
	"pete_skits_anims\pt_cornercheck_signal_left.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_cornercheck_signal_right" {
	"pete_skits_anims\pt_cornercheck_signal_right.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_cornercheck_pause_left" {
	"pete_skits_anims\pt_cornercheck_pause_left.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_cornercheck_pause_right" {
	"pete_skits_anims\pt_cornercheck_pause_right.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_knife_kick_A" {
	"pete_skits_anims\pt_synced_melee_knife_kick_A.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 62 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 65 "P_skit_blood_loop" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 82 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_fight_knockback_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_dying_knockback_diag_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_fight_knockback_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_dying_knockback_diag_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 42 "ai_skit_pt_dying_knockback_diag_Loser_Pt3" }
	{ event AE_CL_PLAYSOUND 51 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_knife_kick_D" {
	"pete_skits_anims\pt_synced_melee_knife_kick_D.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 14 "ai_skit_pt_dying_knockback_diag_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 15 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_pt_dying_knockback_diag_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 58 "ai_skit_pt_fight_knockback_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 64 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 61 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 100 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_knife_struggle_A" {
	"pete_skits_anims\pt_synced_melee_knife_struggle_A.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 62 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 65 "P_skit_blood_loop" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 82 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_fight_knockback_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_dying_knockback_diag_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_fight_knockback_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_dying_knockback_diag_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 42 "ai_skit_pt_dying_knockback_diag_Loser_Pt3" }
	{ event AE_CL_PLAYSOUND 51 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_knife_struggle_D" {
	"pete_skits_anims\pt_synced_melee_knife_struggle_D.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 14 "ai_skit_pt_dying_knockback_diag_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 15 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_pt_dying_knockback_diag_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 58 "ai_skit_pt_fight_knockback_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 64 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 61 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 80 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_F_punch_A" {
	"pete_skits_anims\pt_synced_melee_F_punch_A.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 62 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 65 "P_skit_blood_loop" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 82 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 84 "" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_fight_knockback_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_dying_knockback_diag_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_fight_knockback_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 22 "ai_skit_pt_dying_knockback_diag_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 42 "ai_skit_pt_dying_knockback_diag_Loser_Pt3" }
	{ event AE_CL_PLAYSOUND 51 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_F_punch_D" {
	"pete_skits_anims\pt_synced_melee_F_punch_D.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 14 "ai_skit_pt_dying_knockback_diag_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 15 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_pt_dying_knockback_diag_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 58 "ai_skit_pt_fight_knockback_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 64 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 61 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_F_throw_A" {
	"pete_skits_anims\pt_synced_melee_F_throw_A.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 27 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_NPC_WEAPON_FIRE 130 "" }
	{ event AE_CL_PLAYSOUND 0 "ai_skit_pt_fight_flip_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 14 "ai_skit_pt_fight_flip_diag_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 18 "ai_skit_pt_fight_flip_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 32 "ai_skit_pt_fight_flip_diag_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 46 "ai_skit_pt_fight_flip_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 48 "ai_skit_pt_fight_flip_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 63 "ai_skit_pt_fight_flip_diag_Winner_Pt4" }
	{ event AE_CL_PLAYSOUND 108 "ai_skit_pt_fight_flip_Winner_Pt4" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_F_throw_D" {
	"pete_skits_anims\pt_synced_melee_F_throw_D.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 23 "P_skit_blood_punch follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 27 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 131 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 130 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 137 "P_skit_blood_loop" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 75 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 92 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 145 "" }
	{ event AE_CL_PLAYSOUND 18 "ai_skit_pt_fight_flip_diag_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 33 "ai_skit_pt_fight_flip_diag_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 73 "ai_skit_pt_fight_flip_diag_Loser_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_L_tackle_A" {
	"pete_skits_anims\pt_synced_melee_L_tackle_A.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 25 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 32 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_PLAYSOUND 14 "ai_skit_pt_dying_knockback_diag_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 65 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 58 "ai_skit_pt_fight_knockback_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 64 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 83 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 111 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 123 "ai_skit_pt_dying_knockback_diag_Winner_Pt2" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_L_tackle_D" {
	"pete_skits_anims\pt_synced_melee_L_tackle_D.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 18 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 30 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 141 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 67 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 83 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 112 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 115 "P_skit_blood_loop" }
	{ event AE_CL_PLAYSOUND 17 "ai_skit_pt_fight_knockback_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 17 "ai_skit_pt_dying_knockback_diag_Loser_Pt1" }
	{ event AE_CL_PLAYSOUND 28 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_PLAYSOUND 62 "ai_skit_pt_fight_knockback_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 62 "ai_skit_pt_dying_knockback_diag_Loser_Pt2" }
	{ event AE_CL_PLAYSOUND 88 "ai_skit_pt_dying_knockback_diag_Loser_Pt3" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_R_disarm_A" {
	"pete_skits_anims\pt_synced_melee_R_disarm_A.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 6 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 28 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_pt_dying_knockback_diag_Winner_Pt2" }
	{ event AE_CL_PLAYSOUND 58 "ai_skit_pt_fight_knockback_Winner_Pt2" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_R_disarm_D" {
	"pete_skits_anims\pt_synced_melee_R_disarm_D.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 26 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_PLAYSOUND 65 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 68 "ai_skit_pt_fight_knockback_Loser_Pt1" }
	{ event AE_NPC_WEAPON_FIRE 75 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 77 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 75 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 80 "P_skit_blood_loop" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 84 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 120 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_B_disarm_A" {
	"pete_skits_anims\pt_synced_melee_B_disarm_A.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 6 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 41 "ai_skit_pt_dying_knockback_diag_Winner_Pt2" }
	fadein 0
	fadeout 0
	blendlayer "add_face_fierce_skit" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_synced_melee_B_disarm_D" {
	"pete_skits_anims\pt_synced_melee_B_disarm_D.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 23 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 26 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 55 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_PLAYSOUND 40 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 44 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 84 "" }
	fadein 0
	fadeout 0
	blendlayer "add_face_melee_charge_skit" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_synced_melee_B_neckstab_V" {
	"pete_skits_anims\pt_synced_melee_B_neckstab_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 20 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 28 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 105 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 65 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 95 "P_skit_blood_loop" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 20 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 125 "" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_synced_melee_R_chestleap_V" {
	"pete_skits_anims\pt_synced_melee_R_chestleap_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 10 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 43 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 32 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 45 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 51 "P_skit_blood_loop" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 75 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 2 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 94 "" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_synced_melee_F_chestslam_V" {
	"pete_skits_anims\pt_synced_melee_F_chestslam_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 10 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 43 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 12 "P_skit_land_fx follow_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 36 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 42 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 41 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 50 "P_skit_blood_loop" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 11 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 58 "" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_synced_melee_F_chestkick_V" {
	"pete_skits_anims\pt_synced_melee_F_chestkick_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 6 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_PLAYSOUND 8 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 18 "P_skit_land_fx follow_attachment CHESTFOCUS" }
	{ event AE_CL_PLAYSOUND 28 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 48 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 48 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 48 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 52 "P_skit_blood_loop" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 25 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 73 "" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_synced_melee_L_headcut_V" {
	"pete_skits_anims\pt_synced_melee_L_headcut_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 8 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 7 "P_skit_land_fx follow_attachment L_HAND" }
	{ event AE_CL_PLAYSOUND 8 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_PLAYSOUND 33 "ai_skit_pt_fight_knockback_Winner_Pt1" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 27 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 48 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 48 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 52 "P_skit_blood_loop" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 57 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 25 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 73 "" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_synced_melee_F_toss_V" {
	"pete_skits_anims\pt_synced_melee_F_toss_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 8 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 14 "P_skit_land_fx follow_attachment L_HAND" }
	{ event AE_CL_PLAYSOUND 8 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 27 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 48 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 48 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 52 "P_skit_blood_loop" }
	{ event AE_WPN_DROP 13 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 14 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 93 "" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_synced_melee_B_toss_V" {
	"pete_skits_anims\pt_synced_melee_B_toss_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 8 "ai_skit_pt_fight_knockback_Loser_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 14 "P_skit_land_fx follow_attachment L_HAND" }
	{ event AE_CL_PLAYSOUND 8 "ai_skit_pt_dying_knockback_diag_Winner_Pt3" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 27 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 9 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 65 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 70 "P_skit_blood_loop" }
	{ event AE_WPN_DROP 16 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 33 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 93 "" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_synced_melee_F_grunt_crawl" {
	"pete_skits_anims\pt_synced_melee_F_grunt_crawl.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NO_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 4 "P_skit_land_fx follow_attachment L_HAND" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 5 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 70 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 70 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 80 "P_skit_blood_loop" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 24 "" }
	{ event AE_WPN_DROP 25 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 84 "" }
	{ event AE_CL_PLAYSOUND 16 "grunt_StalkerSyncedMelee_F_grunt_crawl_footsweep" }
	{ event AE_CL_PLAYSOUND 19 "diag_StalkerSyncedMelee_grunt_ThrowPunch" }
	{ event AE_GROUND_CONTACT_L 23 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 42 "diag_StalkerSyncedMelee_grunt_pain" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_F_chestpunch_D" {
	"pete_skits_anims\pt_synced_melee_F_chestpunch_D.smd"
	{ event AE_NO_PAIN 0 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 96 "" }
	{ event AE_WPN_DROP 115 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 118 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_melee_charge_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_B_chestpunch_D" {
	"pete_skits_anims\pt_synced_melee_B_chestpunch_D.smd"
	{ event AE_NO_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 21 "ai_skit_sp_spectre_chestpunch_diag_Grunt_Pt1" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 20 "skit_blood_decal_LG follow_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 21 "P_skit_blood_loop follow_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 22 "skit_blood_decal_LG follow_attachment CHESTFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 25 "P_skit_blood_loop" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 68 "skit_blood_decal_LG follow_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 70 "skit_blood_decal_LG follow_attachment CHESTFOCUS" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 24 "" }
	{ event AE_WPN_DROP 25 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 78 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_F_facepunch" {
	"pete_skits_anims\pt_synced_melee_F_facepunch.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NO_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 11 "diag_StalkerSyncedMelee_grunt_ThrowPunch" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 43 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 43 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 47 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 50 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 53 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 65 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 67 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 68 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 72 "P_skit_blood_loop" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 130 "" }
	{ event AE_WPN_DROP 155 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 160 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_melee_charge_skit" 0 0 0 0
	fps 30
}

$sequence "pt_synced_melee_B_spinepunch" {
	"pete_skits_anims\pt_synced_melee_B_spinepunch.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NO_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 8 "skit_blood_decal_LG follow_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 12 "skit_blood_decal_LG follow_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 35 "P_skit_blood_loop follow_attachment CHESTFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 41 "P_skit_blood_loop" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 40 "" }
	{ event AE_WPN_DROP 6 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 48 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_melee_charge_skit" 0 0 0 0
	fps 30
}

$sequence "pt_stand_melee_V" {
	"pete_skits_anims\pt_stand_melee_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 4 "P_skit_land_fx follow_attachment L_HAND" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 5 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 43 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 43 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 81 "P_skit_blood_loop" }
	{ event AE_CL_PLAYSOUND 0 "stalker_SyncedMelee_F_Chestpunch_D_NeckGrab" }
	{ event AE_CL_PLAYSOUND 0 "stalker_SyncedMelee_F_FacePunch_Punch2" }
	{ event AE_CL_PLAYSOUND 0 "grunt_mvmt_fol_loud_med" }
	{ event AE_CL_PLAYSOUND 0 "diag_StalkerSyncedMelee_grunt_ThrowPunch" }
	{ event AE_CL_PLAYSOUND 19 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 23 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 34 "grunt_mvmt_fol_loud_short" }
	{ event AE_CL_PLAYSOUND 41 "diag_StalkerSyncedMelee_grunt_pain" }
	{ event AE_CL_PLAYSOUND 41 "stalker_SyncedMelee_F_ChestPunch_D_Extract" }
	{ event AE_CL_PLAYSOUND 52 "grunt_mvmt_fol_loud_short" }
	{ event AE_CL_PLAYSOUND 58 "stalker_SyncedMelee_B_Chestpunch_D_Extract" }
	{ event AE_CL_PLAYSOUND 58 "diag_StalkerSyncedMelee_grunt_gutted" }
	{ event AE_CL_PLAYSOUND 66 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 74 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_L 88 "mvmt_fol_bodyfall" }
	{ event AE_WPN_DROP 8 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 9 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 86 "" }
	fadein 0
	fadeout 0
	blendlayer "add_face_melee_charge_skit" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_stand_melee_headrip_V" {
	"pete_skits_anims\pt_stand_melee_headrip_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 9 "P_skit_land_fx follow_attachment L_HAND" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 15 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 57 "skit_blood_decal_LG follow_attachment HEADFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 57 "P_skit_blood_loop follow_attachment HEADFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 67 "P_skit_blood_loop" }
	{ event AE_CL_PLAYSOUND 4 "stalker_SyncedMelee_F_Chestpunch_D_NeckGrab" }
	{ event AE_CL_PLAYSOUND 4 "stalker_SyncedMelee_F_FacePunch_Punch2" }
	{ event AE_CL_PLAYSOUND 4 "grunt_mvmt_fol_loud_med" }
	{ event AE_CL_PLAYSOUND 4 "diag_StalkerSyncedMelee_grunt_ThrowPunch" }
	{ event AE_CL_PLAYSOUND 19 "grunt_mvmt_fol_gear_run" }
	{ event AE_CL_PLAYSOUND 23 "grunt_mvmt_fol_soft_med" }
	{ event AE_CL_PLAYSOUND 34 "grunt_mvmt_fol_loud_short" }
	{ event AE_CL_PLAYSOUND 52 "grunt_mvmt_fol_loud_short" }
	{ event AE_CL_PLAYSOUND 54 "stalker_SyncedMelee_B_Chestpunch_D_Extract" }
	{ event AE_CL_PLAYSOUND 54 "diag_StalkerSyncedMelee_grunt_gutted" }
	{ event AE_CL_PLAYSOUND 55 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_L 67 "mvmt_fol_bodyfall" }
	{ event AE_WPN_DROP 8 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 30 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 76 "" }
	fadein 0
	fadeout 0
	blendlayer "add_face_melee_charge_skit" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_stand_melee_behind_V" {
	"pete_skits_anims\pt_stand_melee_behind_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 17 "P_skit_land_fx follow_attachment L_HAND" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 42 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 73 "skit_blood_decal_LG follow_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 100 "P_skit_blood_loop follow_attachment CHESTFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 101 "P_skit_blood_loop" }
	{ event AE_CL_PLAYSOUND 5 "stalker_SyncedMelee_F_FacePunch_Punch3" }
	{ event AE_CL_PLAYSOUND 5 "diag_StalkerSyncedMelee_grunt_ThrowPunch" }
	{ event AE_CL_PLAYSOUND 5 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_R 13 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 23 "grunt_mvmt_fol_loud_med" }
	{ event AE_CL_PLAYSOUND 23 "diag_StalkerSyncedMelee_grunt_ThrowPunch" }
	{ event AE_GROUND_CONTACT_R 35 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 63 "grunt_mvmt_fol_soft_short" }
	{ event AE_CL_PLAYSOUND 69 "stalker_SyncedMelee_F_ChestPunch_D_Impact" }
	{ event AE_CL_PLAYSOUND 69 "diag_StalkerSyncedMelee_grunt_pain" }
	{ event AE_CL_PLAYSOUND 69 "grunt_mvmt_fol_loud_short" }
	{ event AE_CL_PLAYSOUND 98 "stalker_SyncedMelee_F_ChestPunch_D_Extract" }
	{ event AE_CL_PLAYSOUND 98 "diag_StalkerSyncedMelee_grunt_gutted" }
	{ event AE_CL_PLAYSOUND 98 "grunt_mvmt_fol_loud_med" }
	{ event AE_CL_PLAYSOUND 110 "grunt_mvmt_fol_loud_long" }
	{ event AE_CL_PLAYSOUND 136 "grunt_mvmt_fol_soft_slow_cloth" }
	{ event AE_CL_PLAYSOUND 144 "grunt_mvmt_fol_soft_short" }
	{ event AE_WPN_DROP 11 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 11 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 127 "" }
	fadein 0
	fadeout 0
	blendlayer "add_face_melee_charge_skit" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_stand_melee_left_V" {
	"pete_skits_anims\pt_stand_melee_left_V.smd"
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 18 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 88 "P_skit_land_fx follow_attachment ORIGIN" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 83 "skit_blood_decal_LG follow_attachment CHESTFOCUS" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 84 "P_skit_blood_loop follow_attachment CHESTFOCUS" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 90 "P_skit_blood_loop" }
	{ event AE_CL_PLAYSOUND 6 "stalker_SyncedMelee_F_FacePunch_Punch3" }
	{ event AE_CL_PLAYSOUND 6 "diag_StalkerSyncedMelee_grunt_ThrowPunch" }
	{ event AE_CL_PLAYSOUND 6 "grunt_mvmt_fol_loud_med" }
	{ event AE_GROUND_CONTACT_R 13 "mvmt_fol_bodyfall" }
	{ event AE_CL_PLAYSOUND 52 "stalker_SyncedMelee_F_ChestPunch_D_Impact" }
	{ event AE_CL_PLAYSOUND 52 "diag_StalkerSyncedMelee_grunt_gutted" }
	{ event AE_CL_PLAYSOUND 52 "grunt_mvmt_fol_loud_short" }
	{ event AE_CL_PLAYSOUND 82 "stalker_SyncedMelee_F_ChestPunch_D_Extract" }
	{ event AE_CL_PLAYSOUND 82 "grunt_mvmt_fol_loud_med" }
	{ event AE_WPN_DROP 16 "" }
	{ event AE_NPC_SYNCED_MELEE_RAGDOLL_ON_INTERRUPT 9 "" }
	{ event AE_NPC_SYNCED_MELEE_DEATH 98 "" }
	fadein 0
	fadeout 0
	blendlayer "add_face_melee_charge_skit" 0 0 0 0
	snap
	fps 30
}
