// Created by Crowbar 0.71

$modelname "humans/pete/pete_scripted_r1.mdl"

$surfaceprop "default"

$jointsurfaceprop "jx_c_delta" ""
$jointsurfaceprop "jx_c_pov" ""
$jointsurfaceprop "jx_c_camera" ""
$jointsurfaceprop "def_c_hip" ""
$jointsurfaceprop "jx_c_start" ""
$jointsurfaceprop "def_c_spineA" ""
$jointsurfaceprop "def_c_spineB" ""
$jointsurfaceprop "def_c_spineC" ""
$jointsurfaceprop "ja_c_propGun" ""
$jointsurfaceprop "def_c_neckA" ""
$jointsurfaceprop "jx_c_neckB" ""
$jointsurfaceprop "def_c_neckB" ""
$jointsurfaceprop "def_c_head" ""
$jointsurfaceprop "def_l_clav" ""
$jointsurfaceprop "def_l_shoulder" ""
$jointsurfaceprop "def_l_shoulderTwist" ""
$jointsurfaceprop "def_l_elbowB" ""
$jointsurfaceprop "def_l_shoulderMid" ""
$jointsurfaceprop "def_l_elbow" ""
$jointsurfaceprop "def_l_forearm" ""
$jointsurfaceprop "def_l_wrist" ""
$jointsurfaceprop "def_l_finIndexA" ""
$jointsurfaceprop "def_l_finIndexB" ""
$jointsurfaceprop "def_l_finIndexC" ""
$jointsurfaceprop "def_l_finMidA" ""
$jointsurfaceprop "def_l_finMidB" ""
$jointsurfaceprop "def_l_finMidC" ""
$jointsurfaceprop "def_l_finThumbA" ""
$jointsurfaceprop "def_l_finThumbB" ""
$jointsurfaceprop "def_l_finThumbC" ""
$jointsurfaceprop "def_l_finRingCarpal" ""
$jointsurfaceprop "def_l_finRingA" ""
$jointsurfaceprop "def_l_finRingB" ""
$jointsurfaceprop "def_l_finRingC" ""
$jointsurfaceprop "def_l_finPinkyA" ""
$jointsurfaceprop "def_l_finPinkyB" ""
$jointsurfaceprop "def_l_finPinkyC" ""
$jointsurfaceprop "def_r_clav" ""
$jointsurfaceprop "def_r_shoulder" ""
$jointsurfaceprop "def_r_shoulderTwist" ""
$jointsurfaceprop "def_r_elbowB" ""
$jointsurfaceprop "def_r_shoulderMid" ""
$jointsurfaceprop "def_r_elbow" ""
$jointsurfaceprop "def_r_forearm" ""
$jointsurfaceprop "def_r_wrist" ""
$jointsurfaceprop "def_r_finIndexA" ""
$jointsurfaceprop "def_r_finIndexB" ""
$jointsurfaceprop "def_r_finIndexC" ""
$jointsurfaceprop "def_r_finMidA" ""
$jointsurfaceprop "def_r_finMidB" ""
$jointsurfaceprop "def_r_finMidC" ""
$jointsurfaceprop "def_r_finThumbA" ""
$jointsurfaceprop "def_r_finThumbB" ""
$jointsurfaceprop "def_r_finThumbC" ""
$jointsurfaceprop "def_r_finRingCarpal" ""
$jointsurfaceprop "def_r_finRingA" ""
$jointsurfaceprop "def_r_finRingB" ""
$jointsurfaceprop "def_r_finRingC" ""
$jointsurfaceprop "def_r_finPinkyA" ""
$jointsurfaceprop "def_r_finPinkyB" ""
$jointsurfaceprop "def_r_finPinkyC" ""
$jointsurfaceprop "def_l_thigh" ""
$jointsurfaceprop "def_l_knee" ""
$jointsurfaceprop "def_l_ankle" ""
$jointsurfaceprop "def_l_ball" ""
$jointsurfaceprop "def_l_kneeB" ""
$jointsurfaceprop "def_r_thigh" ""
$jointsurfaceprop "def_r_knee" ""
$jointsurfaceprop "def_r_ankle" ""
$jointsurfaceprop "def_r_ball" ""
$jointsurfaceprop "def_r_kneeB" ""
$jointsurfaceprop "ja_l_propHand" ""
$jointsurfaceprop "ja_r_propHand" ""
$jointsurfaceprop "def_fc_c_jaw_1" ""
$jointsurfaceprop "def_fc_c_jaw_2" ""
$jointsurfaceprop "def_fc_c_nose_1" ""
$jointsurfaceprop "def_fc_c_nose_2" ""
$jointsurfaceprop "def_fc_c_tongue_1" ""
$jointsurfaceprop "def_fc_c_tongue_2" ""
$jointsurfaceprop "def_fc_c_tongue_3" ""
$jointsurfaceprop "def_fc_l_botlip_1" ""
$jointsurfaceprop "def_fc_l_botlip_2" ""
$jointsurfaceprop "def_fc_l_botlip_3" ""
$jointsurfaceprop "def_fc_l_botlip_4" ""
$jointsurfaceprop "def_fc_l_brow_1" ""
$jointsurfaceprop "def_fc_l_brow_2" ""
$jointsurfaceprop "def_fc_l_brow_3" ""
$jointsurfaceprop "def_fc_l_brow_4" ""
$jointsurfaceprop "def_fc_l_cheek_1" ""
$jointsurfaceprop "def_fc_l_cheek_2" ""
$jointsurfaceprop "def_fc_l_cheek_3" ""
$jointsurfaceprop "def_fc_l_cheek_4" ""
$jointsurfaceprop "def_fc_l_cheek_5" ""
$jointsurfaceprop "def_fc_l_cheek_6" ""
$jointsurfaceprop "def_fc_l_eye_1" ""
$jointsurfaceprop "def_fc_l_eye_2" ""
$jointsurfaceprop "def_fc_l_eye_3" ""
$jointsurfaceprop "def_fc_l_forehead_1" ""
$jointsurfaceprop "def_fc_l_forehead_2" ""
$jointsurfaceprop "def_fc_l_jaw_1" ""
$jointsurfaceprop "def_fc_l_jaw_2" ""
$jointsurfaceprop "def_fc_l_jaw_3" ""
$jointsurfaceprop "def_fc_l_mustache_1" ""
$jointsurfaceprop "def_fc_l_mustache_2" ""
$jointsurfaceprop "def_fc_l_neck_1" ""
$jointsurfaceprop "def_fc_l_neck_2" ""
$jointsurfaceprop "def_fc_l_nose_1" ""
$jointsurfaceprop "def_fc_l_nose_2" ""
$jointsurfaceprop "def_fc_l_nose_3" ""
$jointsurfaceprop "def_fc_l_nose_4" ""
$jointsurfaceprop "def_fc_l_nose_5" ""
$jointsurfaceprop "def_fc_l_toplip_1" ""
$jointsurfaceprop "def_fc_l_toplip_2" ""
$jointsurfaceprop "def_fc_l_toplip_3" ""
$jointsurfaceprop "def_fc_l_toplip_4" ""
$jointsurfaceprop "def_fc_r_botlip_1" ""
$jointsurfaceprop "def_fc_r_botlip_2" ""
$jointsurfaceprop "def_fc_r_botlip_3" ""
$jointsurfaceprop "def_fc_r_botlip_4" ""
$jointsurfaceprop "def_fc_r_brow_1" ""
$jointsurfaceprop "def_fc_r_brow_2" ""
$jointsurfaceprop "def_fc_r_brow_3" ""
$jointsurfaceprop "def_fc_r_brow_4" ""
$jointsurfaceprop "def_fc_r_cheek_1" ""
$jointsurfaceprop "def_fc_r_cheek_2" ""
$jointsurfaceprop "def_fc_r_cheek_3" ""
$jointsurfaceprop "def_fc_r_cheek_4" ""
$jointsurfaceprop "def_fc_r_cheek_5" ""
$jointsurfaceprop "def_fc_r_cheek_6" ""
$jointsurfaceprop "def_fc_r_eye_1" ""
$jointsurfaceprop "def_fc_r_eye_2" ""
$jointsurfaceprop "def_fc_r_eye_3" ""
$jointsurfaceprop "def_fc_r_forehead_1" ""
$jointsurfaceprop "def_fc_r_forehead_2" ""
$jointsurfaceprop "def_fc_r_jaw_1" ""
$jointsurfaceprop "def_fc_r_jaw_2" ""
$jointsurfaceprop "def_fc_r_jaw_3" ""
$jointsurfaceprop "def_fc_r_mustache_1" ""
$jointsurfaceprop "def_fc_r_mustache_2" ""
$jointsurfaceprop "def_fc_r_neck_1" ""
$jointsurfaceprop "def_fc_r_neck_2" ""
$jointsurfaceprop "def_fc_r_nose_1" ""
$jointsurfaceprop "def_fc_r_nose_2" ""
$jointsurfaceprop "def_fc_r_nose_3" ""
$jointsurfaceprop "def_fc_r_nose_4" ""
$jointsurfaceprop "def_fc_r_nose_5" ""
$jointsurfaceprop "def_fc_r_toplip_1" ""
$jointsurfaceprop "def_fc_r_toplip_2" ""
$jointsurfaceprop "def_fc_r_toplip_3" ""
$jointsurfaceprop "def_fc_r_toplip_4" ""
$jointsurfaceprop "jx_c_origin" ""

$contents "solid"

$jointcontents "jx_c_delta" "notsolid"
$jointcontents "jx_c_pov" "notsolid"
$jointcontents "jx_c_camera" "notsolid"
$jointcontents "def_c_hip" "notsolid"
$jointcontents "jx_c_start" "notsolid"
$jointcontents "def_c_spineA" "notsolid"
$jointcontents "def_c_spineB" "notsolid"
$jointcontents "def_c_spineC" "notsolid"
$jointcontents "ja_c_propGun" "notsolid"
$jointcontents "def_c_neckA" "notsolid"
$jointcontents "jx_c_neckB" "notsolid"
$jointcontents "def_c_neckB" "notsolid"
$jointcontents "def_c_head" "notsolid"
$jointcontents "def_l_clav" "notsolid"
$jointcontents "def_l_shoulder" "notsolid"
$jointcontents "def_l_shoulderTwist" "notsolid"
$jointcontents "def_l_elbowB" "notsolid"
$jointcontents "def_l_shoulderMid" "notsolid"
$jointcontents "def_l_elbow" "notsolid"
$jointcontents "def_l_forearm" "notsolid"
$jointcontents "def_l_wrist" "notsolid"
$jointcontents "def_l_finIndexA" "notsolid"
$jointcontents "def_l_finIndexB" "notsolid"
$jointcontents "def_l_finIndexC" "notsolid"
$jointcontents "def_l_finMidA" "notsolid"
$jointcontents "def_l_finMidB" "notsolid"
$jointcontents "def_l_finMidC" "notsolid"
$jointcontents "def_l_finThumbA" "notsolid"
$jointcontents "def_l_finThumbB" "notsolid"
$jointcontents "def_l_finThumbC" "notsolid"
$jointcontents "def_l_finRingCarpal" "notsolid"
$jointcontents "def_l_finRingA" "notsolid"
$jointcontents "def_l_finRingB" "notsolid"
$jointcontents "def_l_finRingC" "notsolid"
$jointcontents "def_l_finPinkyA" "notsolid"
$jointcontents "def_l_finPinkyB" "notsolid"
$jointcontents "def_l_finPinkyC" "notsolid"
$jointcontents "def_r_clav" "notsolid"
$jointcontents "def_r_shoulder" "notsolid"
$jointcontents "def_r_shoulderTwist" "notsolid"
$jointcontents "def_r_elbowB" "notsolid"
$jointcontents "def_r_shoulderMid" "notsolid"
$jointcontents "def_r_elbow" "notsolid"
$jointcontents "def_r_forearm" "notsolid"
$jointcontents "def_r_wrist" "notsolid"
$jointcontents "def_r_finIndexA" "notsolid"
$jointcontents "def_r_finIndexB" "notsolid"
$jointcontents "def_r_finIndexC" "notsolid"
$jointcontents "def_r_finMidA" "notsolid"
$jointcontents "def_r_finMidB" "notsolid"
$jointcontents "def_r_finMidC" "notsolid"
$jointcontents "def_r_finThumbA" "notsolid"
$jointcontents "def_r_finThumbB" "notsolid"
$jointcontents "def_r_finThumbC" "notsolid"
$jointcontents "def_r_finRingCarpal" "notsolid"
$jointcontents "def_r_finRingA" "notsolid"
$jointcontents "def_r_finRingB" "notsolid"
$jointcontents "def_r_finRingC" "notsolid"
$jointcontents "def_r_finPinkyA" "notsolid"
$jointcontents "def_r_finPinkyB" "notsolid"
$jointcontents "def_r_finPinkyC" "notsolid"
$jointcontents "def_l_thigh" "notsolid"
$jointcontents "def_l_knee" "notsolid"
$jointcontents "def_l_ankle" "notsolid"
$jointcontents "def_l_ball" "notsolid"
$jointcontents "def_l_kneeB" "notsolid"
$jointcontents "def_r_thigh" "notsolid"
$jointcontents "def_r_knee" "notsolid"
$jointcontents "def_r_ankle" "notsolid"
$jointcontents "def_r_ball" "notsolid"
$jointcontents "def_r_kneeB" "notsolid"
$jointcontents "ja_l_propHand" "notsolid"
$jointcontents "ja_r_propHand" "notsolid"
$jointcontents "def_fc_c_jaw_1" "notsolid"
$jointcontents "def_fc_c_jaw_2" "notsolid"
$jointcontents "def_fc_c_nose_1" "notsolid"
$jointcontents "def_fc_c_nose_2" "notsolid"
$jointcontents "def_fc_c_tongue_1" "notsolid"
$jointcontents "def_fc_c_tongue_2" "notsolid"
$jointcontents "def_fc_c_tongue_3" "notsolid"
$jointcontents "def_fc_l_botlip_1" "notsolid"
$jointcontents "def_fc_l_botlip_2" "notsolid"
$jointcontents "def_fc_l_botlip_3" "notsolid"
$jointcontents "def_fc_l_botlip_4" "notsolid"
$jointcontents "def_fc_l_brow_1" "notsolid"
$jointcontents "def_fc_l_brow_2" "notsolid"
$jointcontents "def_fc_l_brow_3" "notsolid"
$jointcontents "def_fc_l_brow_4" "notsolid"
$jointcontents "def_fc_l_cheek_1" "notsolid"
$jointcontents "def_fc_l_cheek_2" "notsolid"
$jointcontents "def_fc_l_cheek_3" "notsolid"
$jointcontents "def_fc_l_cheek_4" "notsolid"
$jointcontents "def_fc_l_cheek_5" "notsolid"
$jointcontents "def_fc_l_cheek_6" "notsolid"
$jointcontents "def_fc_l_eye_1" "notsolid"
$jointcontents "def_fc_l_eye_2" "notsolid"
$jointcontents "def_fc_l_eye_3" "notsolid"
$jointcontents "def_fc_l_forehead_1" "notsolid"
$jointcontents "def_fc_l_forehead_2" "notsolid"
$jointcontents "def_fc_l_jaw_1" "notsolid"
$jointcontents "def_fc_l_jaw_2" "notsolid"
$jointcontents "def_fc_l_jaw_3" "notsolid"
$jointcontents "def_fc_l_mustache_1" "notsolid"
$jointcontents "def_fc_l_mustache_2" "notsolid"
$jointcontents "def_fc_l_neck_1" "notsolid"
$jointcontents "def_fc_l_neck_2" "notsolid"
$jointcontents "def_fc_l_nose_1" "notsolid"
$jointcontents "def_fc_l_nose_2" "notsolid"
$jointcontents "def_fc_l_nose_3" "notsolid"
$jointcontents "def_fc_l_nose_4" "notsolid"
$jointcontents "def_fc_l_nose_5" "notsolid"
$jointcontents "def_fc_l_toplip_1" "notsolid"
$jointcontents "def_fc_l_toplip_2" "notsolid"
$jointcontents "def_fc_l_toplip_3" "notsolid"
$jointcontents "def_fc_l_toplip_4" "notsolid"
$jointcontents "def_fc_r_botlip_1" "notsolid"
$jointcontents "def_fc_r_botlip_2" "notsolid"
$jointcontents "def_fc_r_botlip_3" "notsolid"
$jointcontents "def_fc_r_botlip_4" "notsolid"
$jointcontents "def_fc_r_brow_1" "notsolid"
$jointcontents "def_fc_r_brow_2" "notsolid"
$jointcontents "def_fc_r_brow_3" "notsolid"
$jointcontents "def_fc_r_brow_4" "notsolid"
$jointcontents "def_fc_r_cheek_1" "notsolid"
$jointcontents "def_fc_r_cheek_2" "notsolid"
$jointcontents "def_fc_r_cheek_3" "notsolid"
$jointcontents "def_fc_r_cheek_4" "notsolid"
$jointcontents "def_fc_r_cheek_5" "notsolid"
$jointcontents "def_fc_r_cheek_6" "notsolid"
$jointcontents "def_fc_r_eye_1" "notsolid"
$jointcontents "def_fc_r_eye_2" "notsolid"
$jointcontents "def_fc_r_eye_3" "notsolid"
$jointcontents "def_fc_r_forehead_1" "notsolid"
$jointcontents "def_fc_r_forehead_2" "notsolid"
$jointcontents "def_fc_r_jaw_1" "notsolid"
$jointcontents "def_fc_r_jaw_2" "notsolid"
$jointcontents "def_fc_r_jaw_3" "notsolid"
$jointcontents "def_fc_r_mustache_1" "notsolid"
$jointcontents "def_fc_r_mustache_2" "notsolid"
$jointcontents "def_fc_r_neck_1" "notsolid"
$jointcontents "def_fc_r_neck_2" "notsolid"
$jointcontents "def_fc_r_nose_1" "notsolid"
$jointcontents "def_fc_r_nose_2" "notsolid"
$jointcontents "def_fc_r_nose_3" "notsolid"
$jointcontents "def_fc_r_nose_4" "notsolid"
$jointcontents "def_fc_r_nose_5" "notsolid"
$jointcontents "def_fc_r_toplip_1" "notsolid"
$jointcontents "def_fc_r_toplip_2" "notsolid"
$jointcontents "def_fc_r_toplip_3" "notsolid"
$jointcontents "def_fc_r_toplip_4" "notsolid"
$jointcontents "jx_c_origin" "notsolid"

$illumposition 0 0.596 53.032

$eyeposition 0 0 64

$cdmaterials ""

$attachment "OFFSET" "jx_c_delta" 0 0 0 rotate -90 -90 0
$attachment "REF" "jx_c_start" 0 0 0 rotate -90 -90 0
$attachment "HEADFOCUS" "def_c_neckB" 0 0 0 rotate -90 -90 0
$attachment "HEADSHOT" "def_c_head" 0 0 0 rotate -90 -90 0
$attachment "CHESTFOCUS" "def_c_spineC" 0 0 0 rotate -90 -90 0
$attachment "PROPGUN" "ja_c_propGun" 0 0 0 rotate -90 -90 0
$attachment "VDU" "jx_c_camera" 0 0 0 rotate -90 -90 0
$attachment "L_HAND" "ja_l_propHand" 0 0 0 rotate 0 0 0
$attachment "R_HAND" "ja_r_propHand" 0 0 0 rotate 0 0 0
$attachment "ORIGIN" "jx_c_delta" 0 0 0 rotate -90 -90 0
$attachment "foot_L_sole" "def_l_ankle" 0 0 0 rotate 0 0 0
$attachment "foot_R_sole" "def_r_ankle" 0 0 0 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -12.273 -24.091 -3.159 11.081 24.091 73.868

$hboxset "default"
$hbox 3 "def_c_hip" -8.487779 -7.432269 -6.419672 8.487779 -0.259842 6.419672 ""
$hbox 2 "def_c_neckA" -5.93109 0.125984 -6.546837 5.93109 3.253537 4.463771 ""
$hbox 1 "def_c_neckB" -4.197236 -3.048813 3.509442 4.197236 6.814553 5.775185 ""
$hbox 1 "def_c_neckB" -5.198021 -1.115746 -5.868098 5.198021 8.319275 4.448023 ""
$hbox 3 "def_c_spineA" -8.098409 0 -6.561404 8.098409 5.59054 6.561404 ""
$hbox 3 "def_c_spineB" -8.098409 0 -6.561404 8.098409 5.55117 6.561404 ""
$hbox 2 "def_c_spineC" -8.45707 -0.112992 -8.436991 8.45707 8.860218 7.276757 ""
$hbox 6 "def_l_ankle" -2.683853 -2.82401 -2.818498 2.607869 2.82401 2.818498 ""
$hbox 6 "def_l_ball" -2.101177 -0.120079 -2.818498 4.225582 3.787788 2.818498 ""
$hbox 4 "def_l_elbow" -2.082673 -3.08149 -1.983461 10.077932 3.08149 1.983461 ""
$hbox 6 "def_l_knee" 0 -4.383456 -3.50393 17.311777 4.383456 3.50393 ""
$hbox 4 "def_l_shoulder" -1.976768 -3.457867 -2.64094 11.110608 3.457867 2.64094 ""
$hbox 6 "def_l_thigh" 0 -4.23385 -3.842906 18.172012 5.373218 3.842906 ""
$hbox 4 "def_l_wrist" -0.281102 -1.56732 -1.558658 4.255109 0.825983 1.862201 ""
$hbox 7 "def_r_ankle" -2.607869 -2.82401 -2.818498 2.683853 2.82401 2.818498 ""
$hbox 7 "def_r_ball" -4.225582 -3.804323 -2.818498 2.101177 0.103543 2.818498 ""
$hbox 5 "def_r_elbow" -10.078327 -3.08149 -1.983461 2.082673 3.081884 1.983461 ""
$hbox 7 "def_r_knee" -17.311777 -4.383456 -3.50393 0 4.383456 3.50393 ""
$hbox 5 "def_r_shoulder" -11.100765 -3.457867 -2.64094 1.986217 3.457867 2.64094 ""
$hbox 7 "def_r_thigh" -18.172012 -5.373218 -3.842906 0 4.23385 3.842906 ""
$hbox 5 "def_r_wrist" -4.255503 -0.825983 -1.862201 0.281102 1.567713 1.558658 ""
$hbox 1 "def_c_head" -2.389365 -6.197625 0.915353 2.389365 -0.738975 4.97125 ""
$hbox 1 "def_c_head" -2.191334 -1.288186 3.938969 2.191334 2.88149 6.08109 ""
$hbox 1 "def_c_head" -2.443696 -3.336608 -5.300383 2.443696 2.54842 -3.845268 ""
$hbox 1 "def_c_head" -2.804325 1.687792 -2.713381 2.804325 4.177157 3.911803 ""
$hbox 1 "def_c_head" -3.917709 -3.348025 -3.852355 3.917709 2.550782 3.933457 ""
$hbox 1 "def_c_head" -2.069287 -6.102744 4.963376 2.069287 -2.68779 6.2055 ""
$hbox 2 "def_c_neckA" -3.599599 0.33307 -4.669676 3.599599 4.963769 3.804717 ""
$hbox 2 "def_c_spineC" -7.513371 0.003543 -6.315342 7.513371 8.838566 6.079122 ""
$hbox 3 "def_c_hip" -7.513371 -7.049199 -6.197232 7.513371 0.000394 6.197232 ""
$hbox 3 "def_c_spineA" -7.513371 0 -6.197232 7.513371 5.59054 6.197232 ""
$hbox 3 "def_c_spineB" -7.513371 0 -6.197232 7.513371 5.55117 6.197232 ""
$hbox 4 "def_l_shoulder" -2.066138 -2.014563 -2.835034 11.231867 2.014563 2.835034 ""
$hbox 4 "def_l_elbow" -1.651965 -1.791335 -1.64606 9.750375 1.791335 1.64606 ""
$hbox 4 "def_l_wrist" -0.291732 -1.342123 -1.670075 3.675583 0.581495 1.894484 ""
$hbox 5 "def_r_shoulder" -11.215726 -2.014563 -2.835034 2.081886 2.014563 2.835034 ""
$hbox 5 "def_r_elbow" -9.74998 -1.791335 -1.64606 1.651965 1.791335 1.64606 ""
$hbox 5 "def_r_wrist" -3.675583 -0.581495 -1.894484 0.291732 1.342123 1.670075 ""
$hbox 6 "def_l_thigh" 0 -2.208657 -3.148813 18.097996 4.371645 3.148813 ""
$hbox 6 "def_l_knee" 0 -2.686215 -3.148813 17.311777 2.686215 3.148813 ""
$hbox 6 "def_l_ankle" -2.103145 -1.918107 -2.531885 3.188576 1.918107 2.531885 ""
$hbox 6 "def_l_ball" -1.637005 -0.124016 -2.520074 3.419285 2.612987 2.520074 ""
$hbox 7 "def_r_thigh" -18.097996 -4.371251 -3.148813 0 2.208657 3.148813 ""
$hbox 7 "def_r_knee" -17.311777 -2.686215 -3.148813 0 2.686215 3.148813 ""
$hbox 7 "def_r_ankle" -3.188576 -1.918107 -2.531885 2.103145 1.918107 2.531885 ""
$hbox 7 "def_r_ball" -3.418891 -2.615349 -2.520074 1.636611 0.121653 2.520074 ""
$hbox 1 "def_c_head" -2.389365 -6.197625 0.915353 2.389365 -0.738975 4.97125 ""
$hbox 1 "def_c_head" -2.191334 -1.288186 3.938969 2.191334 2.88149 6.08109 ""
$hbox 1 "def_c_head" -2.443696 -3.336608 -5.300383 2.443696 2.54842 -3.845268 ""
$hbox 1 "def_c_head" -2.804325 1.687792 -2.713381 2.804325 4.177157 3.911803 ""
$hbox 1 "def_c_head" -3.917315 -3.350387 -5.350383 3.917315 2.551176 5.43306 ""
$hbox 1 "def_c_head" -2.069287 -6.102744 4.963376 2.069287 -2.68779 6.2055 ""
$hbox 1 "def_c_head" -3.598418 -7.515733 -6.2992 3.598418 -2.885821 2.299208 ""
$hbox 2 "def_c_spineC" -7.511796 -0.496062 -6.314949 7.511796 7.338568 6.078728 ""
$hbox 3 "def_c_hip" -7.513371 -7.049199 -6.197232 7.513371 0.000394 6.197232 ""
$hbox 3 "def_c_spineA" -7.513371 0 -6.197232 7.513371 5.59054 6.197232 ""
$hbox 3 "def_c_spineB" -7.513371 0 -6.197232 7.513371 5.55117 6.197232 ""
$hbox 4 "def_l_shoulder" -2.066138 -2.014563 -2.835034 11.231867 2.014563 2.835034 ""
$hbox 4 "def_l_elbow" -1.651965 -1.791335 -1.64606 9.750375 1.791335 1.64606 ""
$hbox 4 "def_l_wrist" -0.291732 -1.342123 -1.670075 3.675583 0.581495 1.894484 ""
$hbox 5 "def_r_shoulder" -11.215726 -2.014563 -2.835034 2.081886 2.014563 2.835034 ""
$hbox 5 "def_r_elbow" -9.74998 -1.791335 -1.64606 1.651965 1.791335 1.64606 ""
$hbox 5 "def_r_wrist" -3.675583 -0.581495 -1.894484 0.291732 1.342123 1.670075 ""
$hbox 6 "def_l_thigh" 0 -2.208657 -3.148813 18.097996 4.371645 3.148813 ""
$hbox 6 "def_l_knee" 0 -2.686215 -3.148813 17.311777 2.686215 3.148813 ""
$hbox 6 "def_l_ankle" -2.103145 -1.918107 -2.531885 3.188576 1.918107 2.531885 ""
$hbox 6 "def_l_ball" -1.637005 -0.124016 -2.520074 3.419285 2.612987 2.520074 ""
$hbox 7 "def_r_thigh" -18.097996 -4.371251 -3.148813 0 2.208657 3.148813 ""
$hbox 7 "def_r_knee" -17.311777 -2.686215 -3.148813 0 2.686215 3.148813 ""
$hbox 7 "def_r_ankle" -3.188576 -1.918107 -2.531885 2.103145 1.918107 2.531885 ""
$hbox 7 "def_r_ball" -3.418891 -2.615349 -2.520074 1.636611 0.121653 2.520074 ""
$hbox 1 "def_c_head" -3.982669 -3.10708 -5.731091 3.982669 6.545656 4.677943 ""
$hbox 2 "def_c_neckA" -2.537003 -0.029134 -2.432672 2.537003 1.337005 3.101568 ""
$hbox 2 "def_c_spineC" -6.705893 0 -5.230305 6.705893 9.785808 5.049202 ""
$hbox 3 "def_c_hip" -7.545654 -3.373222 -5.146446 7.545654 0.889368 5.146446 ""
$hbox 3 "def_c_spineA" -6.924789 0 -5.146446 6.924789 7.326757 5.146446 ""
$hbox 3 "def_c_spineB" -6.705893 0 -5.104714 6.705893 5.08503 5.104714 ""
$hbox 4 "def_l_shoulder" -1.968894 -1.592517 -1.661808 11.015332 1.592517 1.661808 ""
$hbox 4 "def_l_elbow" 0 -1.592517 -1.670469 8.980691 1.592517 1.653146 ""
$hbox 4 "def_l_wrist" -0.312598 -1.597241 -1.648816 5.555107 0.635826 1.704327 ""
$hbox 5 "def_r_shoulder" -10.927931 -1.592517 -1.661808 2.056295 1.592517 1.661808 ""
$hbox 5 "def_r_elbow" -8.980297 -1.592517 -1.653146 0 1.592123 1.670469 ""
$hbox 5 "def_r_wrist" -5.555501 -0.635826 -1.704327 0.312991 1.597635 1.648422 ""
$hbox 6 "def_l_thigh" 0 -3.081884 -2.94527 15.393669 3.081884 2.94527 ""
$hbox 6 "def_l_knee" 0 -2.875585 -3.064955 16.67477 2.875585 3.064955 ""
$hbox 6 "def_l_ankle" -2.515743 -2.058657 -1.977555 3.28897 2.058657 1.977555 ""
$hbox 6 "def_l_ball" -1.376769 -0.181889 -1.977555 3.501174 3.935031 1.977555 ""
$hbox 7 "def_r_thigh" -15.393669 -3.081884 -2.94527 0 3.081884 2.94527 ""
$hbox 7 "def_r_knee" -16.67477 -2.875585 -3.064955 0 2.875585 3.064955 ""
$hbox 7 "def_r_ankle" -3.28897 -2.058657 -1.977555 2.515743 2.058657 1.977555 ""
$hbox 7 "def_r_ball" -3.501174 -3.938181 -1.977555 1.376769 0.179134 1.977555 ""
$hboxset "default"
$hbox 3 "def_c_hip" -8.24644 -7.823213 -6.693688 8.24644 0.085433 6.693688 ""
$hbox 2 "def_c_neckA" -3.961016 0.075984 -3.683457 3.961016 3.80078 4.722826 ""
$hbox 1 "def_c_neckB" -3.576371 -1.004329 -7.018096 3.576371 5.824398 8.120063 ""
$hbox 3 "def_c_spineA" -8.389354 0 -6.687388 8.389354 6.149594 6.687388 ""
$hbox 3 "def_c_spineB" -8.389354 0 -6.687388 8.389354 6.106287 6.687388 ""
$hbox 2 "def_c_spineC" -8.725574 0.118897 -6.686995 8.725574 9.777539 6.686995 ""
$hbox 6 "def_l_ankle" -1.201966 -2.641333 -2.641333 7.023608 2.641333 2.641333 ""
$hbox 6 "def_l_ball" -3.191332 -2.660231 -2.660231 5.527942 2.660231 2.660231 ""
$hbox 4 "def_l_elbow" -3.894874 -1.635824 -1.635824 10.914545 1.635824 1.635824 ""
$hbox 6 "def_l_knee" 0.392519 -3.368891 -3.368891 18.649961 3.368891 3.368891 ""
$hbox 4 "def_l_shoulder" -2.76968 -2.424798 -2.424798 12.63462 2.424798 2.424798 ""
$hbox 6 "def_l_thigh" -0.684251 -1.917319 -4.054323 20.673582 3.170466 4.054323 ""
$hbox 4 "def_l_wrist" -0.598424 -1.367714 -1.755508 4.02322 0.551967 2.089366 ""
$hbox 7 "def_r_ankle" -7.023608 -2.641333 -2.641333 1.201966 2.641333 2.641333 ""
$hbox 7 "def_r_ball" -5.527942 -2.660231 -2.660231 3.191332 2.660231 2.660231 ""
$hbox 5 "def_r_elbow" -10.914545 -1.635824 -1.635824 3.894874 1.635824 1.635824 ""
$hbox 7 "def_r_knee" -18.649961 -3.368891 -3.368891 -0.392519 3.368891 3.368891 ""
$hbox 5 "def_r_shoulder" -12.623203 -2.424798 -2.424798 2.780703 2.424798 2.424798 ""
$hbox 7 "def_r_thigh" -20.673582 -3.170466 -4.054323 0.684251 1.917319 4.054323 ""
$hbox 5 "def_r_wrist" -4.023614 -0.551967 -2.089366 0.598424 1.368107 1.755508 ""
$hbox 8 "def_c_spineC" -5.62676 -4.834636 -12.27281 5.62676 6.736994 -6.911404 ""
$skipboneinbbox

$screenalign def_l_clav "sphere"
$screenalign def_l_shoulderTwist "sphere"
$screenalign def_l_elbowB "sphere"
$screenalign def_l_shoulderMid "sphere"
$screenalign def_l_elbow "cylinder"
$screenalign def_l_wrist "sphere"
$screenalign def_l_finIndexA "cylinder"
$screenalign def_l_finIndexB "sphere"
$screenalign def_l_finMidA "sphere"
$screenalign def_l_finMidB "cylinder"
$screenalign def_l_finMidC "cylinder"
$screenalign def_l_finThumbA "cylinder"
$screenalign def_l_finThumbC "sphere"
$screenalign def_l_finRingCarpal "sphere"
$screenalign def_l_finRingB "sphere"
$screenalign def_l_finRingC "sphere"
$screenalign def_l_finPinkyA "cylinder"
$screenalign def_l_finPinkyB "cylinder"
$screenalign def_l_finPinkyC "cylinder"
$screenalign def_r_clav "sphere"
$screenalign def_r_shoulderMid "sphere"
$screenalign def_r_elbow "sphere"
$screenalign def_r_wrist "sphere"
$screenalign def_r_finIndexA "sphere"
$screenalign def_r_finIndexB "sphere"
$screenalign def_r_finIndexC "cylinder"
$screenalign def_r_finMidA "sphere"
$screenalign def_r_finMidB "sphere"
$screenalign def_r_finMidC "sphere"
$screenalign def_r_finThumbA "cylinder"
$screenalign def_r_finThumbC "cylinder"
$screenalign def_r_finRingCarpal "cylinder"
$screenalign def_r_finRingA "sphere"
$screenalign def_r_finPinkyA "sphere"
$screenalign def_r_finPinkyB "sphere"
$screenalign def_r_finPinkyC "sphere"
$screenalign def_l_thigh "sphere"
$screenalign def_l_knee "sphere"
$screenalign def_l_ankle "sphere"
$screenalign def_l_ball "sphere"
$screenalign def_l_kneeB "sphere"
$screenalign def_r_thigh "sphere"
$screenalign def_r_ankle "cylinder"
$screenalign def_r_kneeB "sphere"
$screenalign ja_l_propHand "cylinder"
$screenalign ja_r_propHand "sphere"

$definebone "jx_c_delta" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_pov" "jx_c_delta" 0 62.992001 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_camera" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hip" "jx_c_delta" 0 39.369999 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_start" "jx_c_delta" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineA" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineB" "def_c_spineA" 0 5.590542 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineC" "def_c_spineB" 0 5.55117 0 0 0 0 0 0 0 0 0 0
$definebone "ja_c_propGun" "def_c_spineC" 0 -7.204712 9.8425 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckA" "def_c_spineC" 0 8.503922 -0.23622 0 0 0 0 0 0 0 0 0
$definebone "jx_c_neckB" "def_c_neckA" 0 4.370071 0.94488 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckB" "jx_c_neckB" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_head" "def_c_neckB" 0 3.936996 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_clav" "def_c_spineC" 1.176218 6.023808 -0.588109 6.983374 3.661928 0.44582 0 0 0 0 0 0
$definebone "def_l_shoulder" "def_l_clav" 5.448854 0.000011 0 -4.860232 -48.915267 4.890265 0 0 0 0 0 0
$definebone "def_l_shoulderTwist" "def_l_shoulder" 0 0 0 0 0.000002 0 0 0 0 0 0 0
$definebone "def_l_elbowB" "def_l_shoulder" 11.630213 -0.000008 0.000027 -44.997331 -0.027096 0.877916 0 0 0 0 0 0
$definebone "def_l_shoulderMid" "def_l_shoulder" 4.890762 0.000004 0 -2.688722 -0.057131 0.006099 0 0 0 0 0 0
$definebone "def_l_elbow" "def_l_shoulderMid" 6.444214 -0.000004 0 -37.014561 0.164812 0.006865 0 0 0 0 0 0
$definebone "def_l_forearm" "def_l_elbow" 4.63045 0.000011 0.000002 -5.291108 -0.116958 0.007797 0 0 0 0 0 0
$definebone "def_l_wrist" "def_l_elbow" 9.956749 -0.010864 0.493276 -5.403714 -0.039456 -0.000075 0 0 0 0 0 0
$definebone "def_l_finIndexA" "def_l_wrist" 3.077315 -0.138939 1.24732 -3.532782 -45.109219 3.539624 0 0 0 0 0 0
$definebone "def_l_finIndexB" "def_l_finIndexA" 1.748371 0 0.000002 -0.001187 -45.000005 0.001192 0 0 0 0 0 0
$definebone "def_l_finIndexC" "def_l_finIndexB" 1.19545 -0.000003 0.000002 0.000615 -45.000008 -0.000614 0 0 0 0 0 0
$definebone "def_l_finMidA" "def_l_wrist" 3.080781 -0.067951 0.349253 6.351203 -45.354918 -6.390478 0 0 0 0 0 0
$definebone "def_l_finMidB" "def_l_finMidA" 1.836349 0.000002 0.000002 0.000002 -45.000005 0.000002 0 0 0 0 0 0
$definebone "def_l_finMidC" "def_l_finMidB" 1.309196 -0.000001 0.000008 -0.002988 -45.000008 0.00298 0 0 0 0 0 0
$definebone "def_l_finThumbA" "def_l_wrist" 0.504171 -0.563503 0.770155 -42.349748 -57.483275 126.990511 0 0 0 0 0 0
$definebone "def_l_finThumbB" "def_l_finThumbA" 2.132282 0.000006 0.000004 3.259416 -22.647167 2.460338 0 0 0 0 0 0
$definebone "def_l_finThumbC" "def_l_finThumbB" 1.240841 -0.000003 0 0.074487 -45.185656 0.008913 0 0 0 0 0 0
$definebone "def_l_finRingCarpal" "def_l_wrist" 2.513066 -0.138184 -0.333538 17.995868 0.000025 0.000075 0 0 0 0 0 0
$definebone "def_l_finRingA" "def_l_finRingCarpal" 0.316793 0.000004 -0.000001 0.003163 -44.999994 -0.003168 0 0 0 0 0 0
$definebone "def_l_finRingB" "def_l_finRingA" 1.966316 0.000002 -0.000002 0.000002 -45.000001 0.000001 0 0 0 0 0 0
$definebone "def_l_finRingC" "def_l_finRingB" 1.00687 0.000001 0.000008 0.000598 -45.000008 -0.000594 0 0 0 0 0 0
$definebone "def_l_finPinkyA" "def_l_finRingCarpal" -0.030562 -0.172359 -0.590865 18.727351 -48.299806 -19.816788 0 0 0 0 0 0
$definebone "def_l_finPinkyB" "def_l_finPinkyA" 1.644444 -0.000002 0 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_l_finPinkyC" "def_l_finPinkyB" 0.763287 -0.000002 0 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_r_clav" "def_c_spineC" -1.176218 6.024002 -0.588109 -6.983374 -3.661928 -179.554171 0 0 0 0 0 0
$definebone "def_r_shoulder" "def_r_clav" -5.448845 0.000145 0 -4.860235 -48.915264 4.890268 0 0 0 0 0 0
$definebone "def_r_shoulderTwist" "def_r_shoulder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_elbowB" "def_r_shoulder" -11.630196 0.000011 -0.000028 -44.997327 -0.027091 0.877916 0 0 0 0 0 0
$definebone "def_r_shoulderMid" "def_r_shoulder" -4.890709 -0.000069 -0.000002 -2.688722 -0.057138 0.006099 0 0 0 0 0 0
$definebone "def_r_elbow" "def_r_shoulderMid" -6.444286 0.00013 0.000005 -37.014561 0.164812 0.006865 0 0 0 0 0 0
$definebone "def_r_forearm" "def_r_elbow" -4.630386 -0.000137 -0.000053 -5.291104 -0.116958 0.007796 0 0 0 0 0 0
$definebone "def_r_wrist" "def_r_elbow" -9.956816 0.010937 -0.493216 -5.403711 -0.039457 -0.000077 0 0 0 0 0 0
$definebone "def_r_finIndexA" "def_r_wrist" -3.077376 0.138977 -1.247286 -3.532781 -45.109219 3.539621 0 0 0 0 0 0
$definebone "def_r_finIndexB" "def_r_finIndexA" -1.748192 0.000002 -0.000114 -0.001197 -45.000001 0.001184 0 0 0 0 0 0
$definebone "def_r_finIndexC" "def_r_finIndexB" -1.195347 0.00008 -0.000078 0.000611 -45.000005 -0.000613 0 0 0 0 0 0
$definebone "def_r_finMidA" "def_r_wrist" -3.08066 0.067764 -0.349348 6.351203 -45.354908 -6.390478 0 0 0 0 0 0
$definebone "def_r_finMidB" "def_r_finMidA" -1.836304 -0.000002 -0.00005 -0.000003 -44.999994 0.000005 0 0 0 0 0 0
$definebone "def_r_finMidC" "def_r_finMidB" -1.309258 -0.000061 0.000052 -0.002987 -45.000008 0.002984 0 0 0 0 0 0
$definebone "def_r_finThumbA" "def_r_wrist" -0.504133 0.563412 -0.770212 -42.349741 -57.483255 126.990511 0 0 0 0 0 0
$definebone "def_r_finThumbB" "def_r_finThumbA" -2.132332 0.000069 -0.00008 3.25942 -22.647166 2.460342 0 0 0 0 0 0
$definebone "def_r_finThumbC" "def_r_finThumbB" -1.240768 -0.000023 0.00005 0.074482 -45.185656 0.008905 0 0 0 0 0 0
$definebone "def_r_finRingCarpal" "def_r_wrist" -2.513052 0.138145 0.333541 17.995867 0.000031 0.000083 0 0 0 0 0 0
$definebone "def_r_finRingA" "def_r_finRingCarpal" -0.316674 -0.000145 -0.000084 0.003161 -45.000001 -0.003161 0 0 0 0 0 0
$definebone "def_r_finRingB" "def_r_finRingA" -1.966396 0.000031 0.000019 0.000002 -45.000005 0.000004 0 0 0 0 0 0
$definebone "def_r_finRingC" "def_r_finRingB" -1.006874 -0.000014 -0.000002 0.000599 -45.000005 -0.000595 0 0 0 0 0 0
$definebone "def_r_finPinkyA" "def_r_finRingCarpal" 0.030523 0.172421 0.590875 18.727346 -48.299795 -19.816788 0 0 0 0 0 0
$definebone "def_r_finPinkyB" "def_r_finPinkyA" -1.644104 -0.000021 0.00001 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_r_finPinkyC" "def_r_finPinkyB" -0.763535 -0.000238 -0.000006 0 -45.000001 0 0 0 0 0 0 0
$definebone "def_l_thigh" "def_c_hip" 5.219006 -1.00618 -0.600196 -0.050695 -90.000003 90.000003 0 0 0 0 0 0
$definebone "def_l_knee" "def_l_thigh" 18.098003 0 0 0 -3.72269 0 0 0 0 0 0 0
$definebone "def_l_ankle" "def_l_knee" 17.311804 0 0 -3.795738 61.268573 0 0 0 0 0 0 0
$definebone "def_l_ball" "def_l_ankle" 5.292377 0 0 0.427673 29.592491 1.875762 0 0 0 0 0 0
$definebone "def_l_kneeB" "def_l_thigh" 18.246761 1.130153 0 0 -7.498168 0 0 0 0 0 0 0
$definebone "def_r_thigh" "def_c_hip" -5.219006 -1.00618 -0.600196 0.050695 90.000003 -90.000003 0 0 0 0 0 0
$definebone "def_r_knee" "def_r_thigh" -18.098003 0 0 0 -3.72269 0 0 0 0 0 0 0
$definebone "def_r_ankle" "def_r_knee" -17.311804 0 0 -3.795738 61.268573 0 0 0 0 0 0 0
$definebone "def_r_ball" "def_r_ankle" -5.292377 0 0 0.427673 29.592491 1.875761 0 0 0 0 0 0
$definebone "def_r_kneeB" "def_r_thigh" -18.246761 -1.130153 0 0 -7.498168 -0.000001 0 0 0 0 0 0
$definebone "ja_l_propHand" "def_l_wrist" 4.441361 -1.883156 0.77133 0.000002 0 -0.000002 0 0 0 0 0 0
$definebone "ja_r_propHand" "def_r_wrist" -4.441751 1.88372 -0.770998 0.000002 0 0.000003 0 0 0 0 0 0
$definebone "def_fc_c_jaw_1" "def_c_head" 0.000008 -3.528931 1.714772 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_jaw_2" "def_c_head" -0.002348 -5.904533 4.421052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_nose_1" "def_c_head" -0.000222 -1.906204 5.126512 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_nose_2" "def_c_head" -0.000014 -2.56337 5.497591 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_1" "def_c_head" 0.000008 -3.896217 1.86384 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_2" "def_c_head" 0.000008 -3.781494 3.033485 0 0 0 0 0 0 0 0 0
$definebone "def_fc_c_tongue_3" "def_c_head" 0.000008 -4.107208 4.160108 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_1" "def_c_head" 0.187538 -4.486393 4.876977 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_2" "def_c_head" 0.714897 -4.453117 4.719345 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_3" "def_c_head" 1.01442 -4.33876 4.225265 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_botlip_4" "def_c_head" 1.217984 -5.240444 4.107803 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_1" "def_c_head" 0.316672 -0.401428 4.700243 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_2" "def_c_head" 0.729493 -0.26873 4.664347 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_3" "def_c_head" 1.52846 -0.217766 4.366918 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_brow_4" "def_c_head" 2.391509 -0.44352 3.275908 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_1" "def_c_head" 0.281779 -1.435074 4.650091 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_2" "def_c_head" 0.554045 -1.595055 4.504138 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_3" "def_c_head" 1.314057 -2.258446 4.347957 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_4" "def_c_head" 1.849152 -2.377121 4.039434 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_5" "def_c_head" 2.300972 -1.677475 3.350968 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_cheek_6" "def_c_head" 2.839564 -1.334602 2.411699 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_1" "def_c_head" 1.26353 -1.073029 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_2" "def_c_head" 1.26353 -1.073418 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_eye_3" "def_c_head" 1.26353 -1.073814 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_forehead_1" "def_c_head" 0.565769 0.634354 4.519776 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_forehead_2" "def_c_head" 1.638682 1.018105 3.771194 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_1" "def_c_head" 2.086407 -3.40559 3.642359 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_2" "def_c_head" 2.6396 -2.433846 0.748599 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_jaw_3" "def_c_head" 3.312682 -1.020157 -0.649023 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_mustache_1" "def_c_head" 0.295735 -3.25177 4.951944 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_mustache_2" "def_c_head" 0.865967 -3.347313 4.613052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_neck_1" "def_c_head" 0.508073 -7.319633 1.372036 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_neck_2" "def_c_head" 1.413078 -5.992386 1.191715 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_1" "def_c_head" 0.812187 -2.579361 4.895335 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_2" "def_c_head" 0.662534 -2.266006 4.638642 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_3" "def_c_head" 1.249506 -2.995415 4.387953 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_4" "def_c_head" 1.564873 -3.679466 4.16363 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_nose_5" "def_c_head" 1.514009 -4.425018 4.054327 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_1" "def_c_head" 0.224988 -3.668037 5.156847 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_2" "def_c_head" 0.731265 -3.800255 4.86531 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_3" "def_c_head" 1.048409 -3.885151 4.371408 0 0 0 0 0 0 0 0 0
$definebone "def_fc_l_toplip_4" "def_c_head" 1.217984 -4.143848 4.08142 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_1" "def_c_head" -0.187538 -4.486393 4.876977 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_2" "def_c_head" -0.714897 -4.453117 4.719345 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_3" "def_c_head" -1.01442 -4.33876 4.225265 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_botlip_4" "def_c_head" -1.217984 -5.240444 4.107803 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_1" "def_c_head" -0.316672 -0.401428 4.700243 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_2" "def_c_head" -0.729493 -0.26873 4.664347 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_3" "def_c_head" -1.52846 -0.217766 4.366918 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_brow_4" "def_c_head" -2.391509 -0.44352 3.275908 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_1" "def_c_head" -0.281779 -1.435074 4.650091 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_2" "def_c_head" -0.554045 -1.595055 4.504138 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_3" "def_c_head" -1.314057 -2.258446 4.347957 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_4" "def_c_head" -1.849152 -2.377121 4.039434 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_5" "def_c_head" -2.300972 -1.677475 3.350968 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_cheek_6" "def_c_head" -2.839564 -1.334602 2.411699 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_1" "def_c_head" -1.26353 -1.073029 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_2" "def_c_head" -1.26353 -1.073418 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_eye_3" "def_c_head" -1.26353 -1.073814 3.495077 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_forehead_1" "def_c_head" -0.565769 0.634354 4.519776 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_forehead_2" "def_c_head" -1.638682 1.018105 3.771194 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_1" "def_c_head" -2.086407 -3.40559 3.642359 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_2" "def_c_head" -2.6396 -2.433846 0.748599 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_jaw_3" "def_c_head" -3.312682 -1.020157 -0.649023 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_mustache_1" "def_c_head" -0.295735 -3.25177 4.951944 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_mustache_2" "def_c_head" -0.865967 -3.347313 4.613052 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_neck_1" "def_c_head" -0.508073 -7.319633 1.372036 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_neck_2" "def_c_head" -1.413078 -5.992386 1.191715 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_1" "def_c_head" -0.812187 -2.579361 4.895335 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_2" "def_c_head" -0.662534 -2.266006 4.638642 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_3" "def_c_head" -1.249506 -2.995415 4.387953 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_4" "def_c_head" -1.564873 -3.679466 4.16363 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_nose_5" "def_c_head" -1.514009 -4.425018 4.054327 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_1" "def_c_head" -0.224988 -3.668037 5.156847 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_2" "def_c_head" -0.731265 -3.800255 4.86531 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_3" "def_c_head" -1.048409 -3.885151 4.371408 0 0 0 0 0 0 0 0 0
$definebone "def_fc_r_toplip_4" "def_c_head" -1.217984 -4.143848 4.08142 0 0 0 0 0 0 0 0 0
$definebone "jx_c_origin" "" 0 0 0 0 0 0 0 0 0 0 0 0

$bonemerge "def_l_clav"
$bonemerge "def_l_shoulder"
$bonemerge "def_l_shoulderTwist"
$bonemerge "def_l_elbowB"
$bonemerge "def_l_shoulderMid"
$bonemerge "def_l_elbow"
$bonemerge "def_l_forearm"
$bonemerge "def_l_wrist"
$bonemerge "def_l_finIndexA"
$bonemerge "def_l_finIndexB"
$bonemerge "def_l_finIndexC"
$bonemerge "def_l_finMidA"
$bonemerge "def_l_finMidB"
$bonemerge "def_l_finMidC"
$bonemerge "def_l_finRingCarpal"
$bonemerge "def_l_finRingA"
$bonemerge "def_l_finRingB"
$bonemerge "def_l_finRingC"
$bonemerge "def_l_finPinkyA"
$bonemerge "def_l_finPinkyB"
$bonemerge "def_l_finPinkyC"
$bonemerge "def_r_clav"
$bonemerge "def_r_shoulder"
$bonemerge "def_r_shoulderTwist"
$bonemerge "def_r_elbowB"
$bonemerge "def_r_shoulderMid"
$bonemerge "def_r_elbow"
$bonemerge "def_r_forearm"
$bonemerge "def_r_wrist"
$bonemerge "def_r_finIndexA"
$bonemerge "def_r_finIndexB"
$bonemerge "def_r_finIndexC"
$bonemerge "def_r_finMidA"
$bonemerge "def_r_finMidB"
$bonemerge "def_r_finMidC"
$bonemerge "def_r_finRingCarpal"
$bonemerge "def_r_finRingA"
$bonemerge "def_r_finRingB"
$bonemerge "def_r_finRingC"
$bonemerge "def_r_finPinkyA"
$bonemerge "def_r_finPinkyB"
$bonemerge "def_r_finPinkyC"
$bonemerge "def_l_ankle"
$bonemerge "def_l_ball"
$bonemerge "def_r_ankle"
$bonemerge "def_r_ball"
$bonemerge "ja_l_propHand"
$bonemerge "ja_r_propHand"


$bonesaveframe "def_l_clav" position rotation
$bonesaveframe "def_l_shoulder" position rotation
$bonesaveframe "def_l_shoulderTwist" position rotation
$bonesaveframe "def_l_elbowB" position
$bonesaveframe "def_l_shoulderMid" position rotation
$bonesaveframe "def_l_elbow" rotation
$bonesaveframe "def_l_forearm" position
$bonesaveframe "def_l_wrist" position
$bonesaveframe "def_l_finIndexA" position
$bonesaveframe "def_l_finIndexB" position
$bonesaveframe "def_l_finIndexC" position
$bonesaveframe "def_l_finMidA" rotation
$bonesaveframe "def_l_finMidB" rotation
$bonesaveframe "def_l_finMidC" rotation
$bonesaveframe "def_l_finThumbA" position
$bonesaveframe "def_l_finRingCarpal" position rotation
$bonesaveframe "def_l_finRingA" position rotation
$bonesaveframe "def_l_finRingB" position rotation
$bonesaveframe "def_l_finRingC" position rotation
$bonesaveframe "def_l_finPinkyA" position rotation
$bonesaveframe "def_l_finPinkyB" position rotation
$bonesaveframe "def_l_finPinkyC" position rotation
$bonesaveframe "def_r_clav" position rotation
$bonesaveframe "def_r_shoulder" position rotation
$bonesaveframe "def_r_shoulderTwist" position rotation
$bonesaveframe "def_r_elbowB" position
$bonesaveframe "def_r_shoulderMid" position rotation
$bonesaveframe "def_r_elbow" rotation
$bonesaveframe "def_r_forearm" position
$bonesaveframe "def_r_wrist" position
$bonesaveframe "def_r_finIndexA" position
$bonesaveframe "def_r_finIndexB" position
$bonesaveframe "def_r_finIndexC" position
$bonesaveframe "def_r_finMidA" rotation
$bonesaveframe "def_r_finMidB" rotation
$bonesaveframe "def_r_finMidC" rotation
$bonesaveframe "def_r_finThumbA" position
$bonesaveframe "def_r_finRingCarpal" position rotation
$bonesaveframe "def_r_finRingA" position rotation
$bonesaveframe "def_r_finRingB" position rotation
$bonesaveframe "def_r_finRingC" position rotation
$bonesaveframe "def_r_finPinkyA" position rotation
$bonesaveframe "def_r_finPinkyB" position rotation
$bonesaveframe "def_r_finPinkyC" position rotation
$bonesaveframe "def_l_thigh" position
$bonesaveframe "def_l_knee" position
$bonesaveframe "def_l_ankle" position rotation
$bonesaveframe "def_l_ball" rotation
$bonesaveframe "def_l_kneeB" position
$bonesaveframe "def_r_thigh" position
$bonesaveframe "def_r_knee" position
$bonesaveframe "def_r_ankle" position rotation
$bonesaveframe "def_r_ball" rotation
$bonesaveframe "ja_l_propHand" position
$bonesaveframe "ja_r_propHand" position

$weightlist "weights_sr1_face_death_flinch" {
	 "jx_c_delta" 0
	 "jx_c_pov" 0
	 "jx_c_camera" 0
	 "def_c_hip" 0
	 "jx_c_start" 0
	 "def_c_spineA" 0
	 "def_c_spineB" 0
	 "def_c_spineC" 0
	 "ja_c_propGun" 0
	 "def_c_neckA" 0
	 "jx_c_neckB" 0
	 "def_c_neckB" 0
	 "def_c_head" 1
	 "def_l_clav" 0
	 "def_l_shoulder" 0
	 "def_l_shoulderTwist" 0
	 "def_l_elbowB" 0
	 "def_l_shoulderMid" 0
	 "def_l_elbow" 0
	 "def_l_forearm" 0
	 "def_l_wrist" 0
	 "def_l_finIndexA" 0
	 "def_l_finIndexB" 0
	 "def_l_finIndexC" 0
	 "def_l_finMidA" 0
	 "def_l_finMidB" 0
	 "def_l_finMidC" 0
	 "def_l_finThumbA" 0
	 "def_l_finThumbB" 0
	 "def_l_finThumbC" 0
	 "def_l_finRingCarpal" 0
	 "def_l_finRingA" 0
	 "def_l_finRingB" 0
	 "def_l_finRingC" 0
	 "def_l_finPinkyA" 0
	 "def_l_finPinkyB" 0
	 "def_l_finPinkyC" 0
	 "def_r_clav" 0
	 "def_r_shoulder" 0
	 "def_r_shoulderTwist" 0
	 "def_r_elbowB" 0
	 "def_r_shoulderMid" 0
	 "def_r_elbow" 0
	 "def_r_forearm" 0
	 "def_r_wrist" 0
	 "def_r_finIndexA" 0
	 "def_r_finIndexB" 0
	 "def_r_finIndexC" 0
	 "def_r_finMidA" 0
	 "def_r_finMidB" 0
	 "def_r_finMidC" 0
	 "def_r_finThumbA" 0
	 "def_r_finThumbB" 0
	 "def_r_finThumbC" 0
	 "def_r_finRingCarpal" 0
	 "def_r_finRingA" 0
	 "def_r_finRingB" 0
	 "def_r_finRingC" 0
	 "def_r_finPinkyA" 0
	 "def_r_finPinkyB" 0
	 "def_r_finPinkyC" 0
	 "def_l_thigh" 0
	 "def_l_knee" 0
	 "def_l_ankle" 0
	 "def_l_ball" 0
	 "def_l_kneeB" 0
	 "def_r_thigh" 0
	 "def_r_knee" 0
	 "def_r_ankle" 0
	 "def_r_ball" 0
	 "def_r_kneeB" 0
	 "ja_l_propHand" 0
	 "ja_r_propHand" 0
	 "def_fc_c_jaw_1" 1
	 "def_fc_c_jaw_2" 1
	 "def_fc_c_nose_1" 1
	 "def_fc_c_nose_2" 1
	 "def_fc_c_tongue_1" 1
	 "def_fc_c_tongue_2" 1
	 "def_fc_c_tongue_3" 1
	 "def_fc_l_botlip_1" 1
	 "def_fc_l_botlip_2" 1
	 "def_fc_l_botlip_3" 1
	 "def_fc_l_botlip_4" 1
	 "def_fc_l_brow_1" 1
	 "def_fc_l_brow_2" 1
	 "def_fc_l_brow_3" 1
	 "def_fc_l_brow_4" 1
	 "def_fc_l_cheek_1" 1
	 "def_fc_l_cheek_2" 1
	 "def_fc_l_cheek_3" 1
	 "def_fc_l_cheek_4" 1
	 "def_fc_l_cheek_5" 1
	 "def_fc_l_cheek_6" 1
	 "def_fc_l_eye_1" 1
	 "def_fc_l_eye_2" 1
	 "def_fc_l_eye_3" 1
	 "def_fc_l_forehead_1" 1
	 "def_fc_l_forehead_2" 1
	 "def_fc_l_jaw_1" 1
	 "def_fc_l_jaw_2" 1
	 "def_fc_l_jaw_3" 1
	 "def_fc_l_mustache_1" 1
	 "def_fc_l_mustache_2" 1
	 "def_fc_l_neck_1" 1
	 "def_fc_l_neck_2" 1
	 "def_fc_l_nose_1" 1
	 "def_fc_l_nose_2" 1
	 "def_fc_l_nose_3" 1
	 "def_fc_l_nose_4" 1
	 "def_fc_l_nose_5" 1
	 "def_fc_l_toplip_1" 1
	 "def_fc_l_toplip_2" 1
	 "def_fc_l_toplip_3" 1
	 "def_fc_l_toplip_4" 1
	 "def_fc_r_botlip_1" 1
	 "def_fc_r_botlip_2" 1
	 "def_fc_r_botlip_3" 1
	 "def_fc_r_botlip_4" 1
	 "def_fc_r_brow_1" 1
	 "def_fc_r_brow_2" 1
	 "def_fc_r_brow_3" 1
	 "def_fc_r_brow_4" 1
	 "def_fc_r_cheek_1" 1
	 "def_fc_r_cheek_2" 1
	 "def_fc_r_cheek_3" 1
	 "def_fc_r_cheek_4" 1
	 "def_fc_r_cheek_5" 1
	 "def_fc_r_cheek_6" 1
	 "def_fc_r_eye_1" 1
	 "def_fc_r_eye_2" 1
	 "def_fc_r_eye_3" 1
	 "def_fc_r_forehead_1" 1
	 "def_fc_r_forehead_2" 1
	 "def_fc_r_jaw_1" 1
	 "def_fc_r_jaw_2" 1
	 "def_fc_r_jaw_3" 1
	 "def_fc_r_mustache_1" 1
	 "def_fc_r_mustache_2" 1
	 "def_fc_r_neck_1" 1
	 "def_fc_r_neck_2" 1
	 "def_fc_r_nose_1" 1
	 "def_fc_r_nose_2" 1
	 "def_fc_r_nose_3" 1
	 "def_fc_r_nose_4" 1
	 "def_fc_r_nose_5" 1
	 "def_fc_r_toplip_1" 1
	 "def_fc_r_toplip_2" 1
	 "def_fc_r_toplip_3" 1
	 "def_fc_r_toplip_4" 1
	 "jx_c_origin" 0
}

$animation "idle_static_pete_scripted" "pete_scripted_r1_anims\idle_static_pete_scripted.smd" {
	fps 30
}

$animation "face_neutral_scripted" "pete_scripted_r1_anims\face_neutral_scripted.smd" {
	fps 30
}

$animation "a_traverseA" "pete_scripted_r1_anims\a_traverseA.smd" {
	fps 30
}

$animation "a_traverseB" "pete_scripted_r1_anims\a_traverseB.smd" {
	fps 30
}

$animation "a_traverseC" "pete_scripted_r1_anims\a_traverseC.smd" {
	fps 30
}

$animation "a_traverseD" "pete_scripted_r1_anims\a_traverseD.smd" {
	fps 30
}

$animation "a_walldeath" "pete_scripted_r1_anims\a_walldeath.smd" {
	fps 30
}

$animation "a_walldeath_R" "pete_scripted_r1_anims\a_walldeath_R.smd" {
	fps 30
}

$animation "a_walldeath_SL" "pete_scripted_r1_anims\a_walldeath_SL.smd" {
	fps 30
}

$animation "a_walldeath_SR" "pete_scripted_r1_anims\a_walldeath_SR.smd" {
	fps 30
}

$animation "a_Scaletest" "pete_scripted_r1_anims\a_Scaletest.smd" {
	fps 30
}

$animation "idle" "pete_scripted_r1_anims\idle.smd" {
	fps 30
}

$animation "pt_data_knife_console_leech_start_anim" "pete_scripted_r1_anims\pt_data_knife_console_leech_start_anim.smd" {
	fps 30
}

$animation "a_stomped" "pete_scripted_r1_anims\a_stomped.smd" {
	fps 30
}

$animation "a_search_pri" "pete_scripted_r1_anims\a_search_pri.smd" {
	fps 30
}

$animation "a_search_sol" "pete_scripted_r1_anims\a_search_sol.smd" {
	fps 30
}

$animation "a_kill_pri" "pete_scripted_r1_anims\a_kill_pri.smd" {
	fps 30
}

$animation "a_kill_sol" "pete_scripted_r1_anims\a_kill_sol.smd" {
	fps 30
}

$animation "a_CasualA" "pete_scripted_r1_anims\a_CasualA.smd" {
	fps 30
	loop
}

$animation "a_CasualB" "pete_scripted_r1_anims\a_CasualB.smd" {
	fps 30
	loop
}

$animation "a_droppod_exit_A" "pete_scripted_r1_anims\a_droppod_exit_A.smd" {
	fps 30
}

$animation "a_droppod_exit_B" "pete_scripted_r1_anims\a_droppod_exit_B.smd" {
	fps 30
}

$animation "a_pt_dp_idle_a" "pete_scripted_r1_anims\a_pt_dp_idle_a.smd" {
	fps 30
	loop
}

$animation "a_pt_dp_idle_b" "pete_scripted_r1_anims\a_pt_dp_idle_b.smd" {
	fps 30
	loop
}

$animation "a_pt_dp_idle_c" "pete_scripted_r1_anims\a_pt_dp_idle_c.smd" {
	fps 30
	loop
}

$animation "a_pt_dp_idle_d" "pete_scripted_r1_anims\a_pt_dp_idle_d.smd" {
	fps 30
	loop
}

$animation "a_pt_dp_idle_player" "pete_scripted_r1_anims\a_pt_dp_idle_player.smd" {
	fps 30
	loop
}

$animation "a_pt_rodeo_panel" "pete_scripted_r1_anims\a_pt_rodeo_panel.smd" {
	fps 60
	loop
}

$animation "a_pt_rodeo_stryder_panel" "pete_scripted_r1_anims\a_pt_rodeo_stryder_panel.smd" {
	fps 60
	loop
}

$animation "a_aim_ht_rodeo360_neutral" "pete_scripted_r1_anims\a_aim_ht_rodeo360_neutral.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_down_left_far" "pete_scripted_r1_anims\a_aim_ht_rodeo360_down_left_far.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_down_left" "pete_scripted_r1_anims\a_aim_ht_rodeo360_down_left.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_down_center" "pete_scripted_r1_anims\a_aim_ht_rodeo360_down_center.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_down_right" "pete_scripted_r1_anims\a_aim_ht_rodeo360_down_right.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_down_right_far" "pete_scripted_r1_anims\a_aim_ht_rodeo360_down_right_far.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_mid_left_far" "pete_scripted_r1_anims\a_aim_ht_rodeo360_mid_left_far.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_mid_left" "pete_scripted_r1_anims\a_aim_ht_rodeo360_mid_left.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_mid_center" "pete_scripted_r1_anims\a_aim_ht_rodeo360_mid_center.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_mid_right" "pete_scripted_r1_anims\a_aim_ht_rodeo360_mid_right.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_mid_right_far" "pete_scripted_r1_anims\a_aim_ht_rodeo360_mid_right_far.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_up_left_far" "pete_scripted_r1_anims\a_aim_ht_rodeo360_up_left_far.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_up_left" "pete_scripted_r1_anims\a_aim_ht_rodeo360_up_left.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_up_center" "pete_scripted_r1_anims\a_aim_ht_rodeo360_up_center.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_up_right" "pete_scripted_r1_anims\a_aim_ht_rodeo360_up_right.smd" {
	fps 30
}

$animation "a_aim_ht_rodeo360_up_right_far" "pete_scripted_r1_anims\a_aim_ht_rodeo360_up_right_far.smd" {
	fps 30
}

$animation "a_pt_rodeo_ogre_panel" "pete_scripted_r1_anims\a_pt_rodeo_ogre_panel.smd" {
	fps 60
	loop
}

$sequence "add_face_idle_casual_scripted" {
	"pete_scripted_r1_anims\add_face_idle_casual_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_focused_scripted" {
	"pete_scripted_r1_anims\add_face_focused_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_fierce_scripted" {
	"pete_scripted_r1_anims\add_face_fierce_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_Poised_scripted" {
	"pete_scripted_r1_anims\add_face_Poised_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_pain_scripted" {
	"pete_scripted_r1_anims\add_face_pain_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_angryPose_scripted" {
	"pete_scripted_r1_anims\add_face_angryPose_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_surprise_scripted" {
	"pete_scripted_r1_anims\add_face_surprise_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_flyin_short_scripted" {
	"pete_scripted_r1_anims\add_face_flyin_short_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_flyin_medium_scripted" {
	"pete_scripted_r1_anims\add_face_flyin_medium_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "add_face_flyin_long_scripted" {
	"pete_scripted_r1_anims\add_face_flyin_long_scripted.smd"
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sr1_face_death_flinch" {
	"pete_scripted_r1_anims\sr1_face_death_flinch.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_sr1_face_death_flinch"
}

$sequence "sr1_face_death_pant" {
	"pete_scripted_r1_anims\sr1_face_death_pant.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_sr1_face_death_flinch"
}

$sequence "sr1_face_death_scream" {
	"pete_scripted_r1_anims\sr1_face_death_scream.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_sr1_face_death_flinch"
}

$sequence "sr1_face_focused_alt" {
	"pete_scripted_r1_anims\sr1_face_focused_alt.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_sr1_face_death_flinch"
}

$sequence "sr1_face_fearful_alt" {
	"pete_scripted_r1_anims\sr1_face_fearful_alt.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_sr1_face_death_flinch"
}

$sequence "sr1_face_focused" {
	"pete_scripted_r1_anims\sr1_face_focused.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_sr1_face_death_flinch"
}

$sequence "sr1_face_grunt_longidle" {
	"pete_scripted_r1_anims\sr1_face_grunt_longidle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_sr1_face_death_flinch"
}

$sequence "sr1_face_grunt_signal_A" {
	"pete_scripted_r1_anims\sr1_face_grunt_signal_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_sr1_face_death_flinch"
}

$sequence "pt_Mobility_Wallrun_1" {
	"pete_scripted_r1_anims\pt_Mobility_Wallrun_1.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_Mobility_Wallrun_2" {
	"pete_scripted_r1_anims\pt_Mobility_Wallrun_2.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "Traverse_around_carR" {
	"pete_scripted_r1_anims\Traverse_around_carR.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Traverse_around_carL" {
	"pete_scripted_r1_anims\Traverse_around_carL.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "TraverseA" {
	"a_traverseA"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "TraverseB" {
	"a_traverseB"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "TraverseC" {
	"a_traverseC"
	activity "ACT_BUSY_STAND" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "TraverseD" {
	"a_traverseD"
	activity "ACT_BUSY_STAND" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "Walldeath" {
	"a_walldeath"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_scripted" 0 0 0 0
	fps 30
}

$sequence "Walldeath_R" {
	"a_walldeath_R"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_scripted" 0 0 0 0
	fps 30
}

$sequence "Walldeath_SL" {
	"a_walldeath_SL"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_scripted" 0 0 0 0
	fps 30
}

$sequence "Walldeath_SR" {
	"a_walldeath_SR"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_scripted" 0 0 0 0
	fps 30
}

$sequence "Scaletest" {
	"a_Scaletest"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_turn_wave_a" {
	"pete_scripted_r1_anims\pt_generic_commander_turn_wave_a.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_turn_wave_b" {
	"pete_scripted_r1_anims\pt_generic_commander_turn_wave_b.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_wave_short_A" {
	"pete_scripted_r1_anims\pt_generic_commander_wave_short_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_wave_short_B" {
	"pete_scripted_r1_anims\pt_generic_commander_wave_short_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_wave_long_A" {
	"pete_scripted_r1_anims\pt_generic_commander_wave_long_A.smd"
	{ event AE_NPC_SET_MOVING 354 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_wave_long_B" {
	"pete_scripted_r1_anims\pt_generic_commander_wave_long_B.smd"
	{ event AE_NPC_SET_MOVING 365 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_wave_duck_A" {
	"pete_scripted_r1_anims\pt_generic_commander_wave_duck_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_wave_duck_B" {
	"pete_scripted_r1_anims\pt_generic_commander_wave_duck_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_surprise_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_wave_short_C" {
	"pete_scripted_r1_anims\pt_generic_commander_wave_short_C.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_commander_wave_short_C_idle" {
	"pete_scripted_r1_anims\pt_generic_commander_wave_short_C_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_generic_run_N_wave" {
	"pete_scripted_r1_anims\pt_generic_run_N_wave.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_Militia_titan_commander_officer" {
	"pete_scripted_r1_anims\pt_Militia_titan_commander_officer.smd"
	{ event AE_CL_PLAYSOUND 218 "diag_cmp_frac_mcor_tcapn1_squadmove_10" }
	fadein 1
	fadeout 0.2
	fps 30
}

$sequence "pt_IMC_titan_commander_idle" {
	"pete_scripted_r1_anims\pt_IMC_titan_commander_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_IMC_titan_commander" {
	"pete_scripted_r1_anims\pt_IMC_titan_commander.smd"
	{ event AE_CL_PLAYSOUND 28 "diag_imc_captain_cmp_frac_1_1_3a" }
	{ event AE_CL_PLAYSOUND 178 "diag_imc_captain_cmp_frac_1_1_1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_guard_seated_bored" {
	"pete_scripted_r1_anims\pt_guard_seated_bored.smd"
	activity "ACT_IDLE_SITTING" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_guard_seated_drink" {
	"pete_scripted_r1_anims\pt_guard_seated_drink.smd"
	activity "ACT_IDLE_SITTING" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_guard_seated_stand" {
	"pete_scripted_r1_anims\pt_guard_seated_stand.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_guard_seated_death" {
	"pete_scripted_r1_anims\pt_guard_seated_death.smd"
	activity "ACT_DO_NOT_DISTURB" 1
	{ event AE_WPN_DROP 12 "" }
	{ event AE_RAGDOLL 60 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_explosive_breach_A" {
	"pete_scripted_r1_anims\pt_explosive_breach_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_explosive_breach_B" {
	"pete_scripted_r1_anims\pt_explosive_breach_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 137 "signal:wallbreach_explode" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_explosive_breach_idle_A" {
	"pete_scripted_r1_anims\pt_explosive_breach_idle_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_explosive_breach_idle_B" {
	"pete_scripted_r1_anims\pt_explosive_breach_idle_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_search_hole_wait_A" {
	"pete_scripted_r1_anims\pt_search_hole_wait_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_search_hole_walkup_A" {
	"pete_scripted_r1_anims\pt_search_hole_walkup_A.smd"
	fadein 0.2
	fadeout 0.75
	fps 30
}

$sequence "pt_search_hole_idle_A" {
	"pete_scripted_r1_anims\pt_search_hole_idle_A.smd"
	fadein 0.75
	fadeout 0.75
	fps 30
}

$sequence "pt_search_hole_walkback_A" {
	"pete_scripted_r1_anims\pt_search_hole_walkback_A.smd"
	fadein 0.75
	fadeout 0.2
	fps 30
}

$sequence "pt_search_hole_wait_B" {
	"pete_scripted_r1_anims\pt_search_hole_wait_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_search_hole_walkup_B" {
	"pete_scripted_r1_anims\pt_search_hole_walkup_B.smd"
	fadein 0.2
	fadeout 0.75
	fps 30
}

$sequence "pt_search_hole_idle_B" {
	"pete_scripted_r1_anims\pt_search_hole_idle_B.smd"
	fadein 0.75
	fadeout 0.75
	fps 30
	loop
}

$sequence "pt_search_hole_walkback_B" {
	"pete_scripted_r1_anims\pt_search_hole_walkback_B.smd"
	fadein 0.75
	fadeout 0.2
	fps 30
}

$sequence "pt_search_broken_stairwell_A" {
	"pete_scripted_r1_anims\pt_search_broken_stairwell_A.smd"
	{ event AE_NPC_TOGGLE_ANIM_FOV 1 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_search_broken_stairwell_B" {
	"pete_scripted_r1_anims\pt_search_broken_stairwell_B.smd"
	{ event AE_NPC_TOGGLE_ANIM_FOV 1 "" }
	{ event AE_SV_VSCRIPT_CALLBACK 124 "flare_pullout" }
	{ event AE_SV_VSCRIPT_CALLBACK 157 "flare_crack" }
	{ event AE_SV_VSCRIPT_CALLBACK 171 "flare_toss_preframe" }
	{ event AE_SV_VSCRIPT_CALLBACK 172 "flare_toss" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_data_knife_console_leech_start" {
	"pete_scripted_r1_anims\pt_data_knife_console_leech_start.smd"
	{ event AE_CL_PLAYSOUND 0 "DataKnife_Hack_Console_Pt1" }
	{ event AE_CL_PLAYSOUND 13 "DataKnife_Hack_Console_Pt2" }
	{ event AE_CL_PLAYSOUND 28 "DataKnife_Hack_Console_Pt3" }
	{ event AE_CL_PLAYSOUND 53 "DataKnife_Hack_Console_Pt4" }
	{ event AE_CL_PLAYSOUND 67 "DataKnife_Hack_Console_Pt5" }
	fadein 0.25
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_data_knife_console_leech_remoteturret_start" {
	"pt_data_knife_console_leech_start_anim"
	{ event AE_CL_PLAYSOUND 0 "DataKnife_Hack_Console_Pt3" }
	{ event AE_CL_PLAYSOUND 18 "DataKnife_Hack_Console_Pt4" }
	{ event AE_CL_PLAYSOUND 32 "DataKnife_Hack_Console_Pt5" }
	fadein 0.25
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_data_knife_console_leech_idle" {
	"pete_scripted_r1_anims\pt_data_knife_console_leech_idle.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
	loop
}

$sequence "pt_data_knife_console_leech_end" {
	"pete_scripted_r1_anims\pt_data_knife_console_leech_end.smd"
	{ event AE_CL_PLAYSOUND 0 "DataKnife_HackComplete_Console_Pt1" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_mobile_hardpoint_laptop_start" {
	"pete_scripted_r1_anims\pt_mobile_hardpoint_laptop_start.smd"
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "pt_mobile_hardpoint_laptop_idle" {
	"pete_scripted_r1_anims\pt_mobile_hardpoint_laptop_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_mobile_hardpoint_laptop_end" {
	"pete_scripted_r1_anims\pt_mobile_hardpoint_laptop_end.smd"
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_s2s_bridge_console_start" {
	"pete_scripted_r1_anims\pt_s2s_bridge_console_start.smd"
	{ event AE_CL_PLAYSOUND 0 "s2s_bridge_console_start" }
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "pt_s2s_bridge_console_end" {
	"pete_scripted_r1_anims\pt_s2s_bridge_console_end.smd"
	{ event AE_CL_PLAYSOUND 0 "s2s_bridge_console_end" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_s2s_bridge_console_idle" {
	"pete_scripted_r1_anims\pt_s2s_bridge_console_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_marvin_leech_start" {
	"pete_scripted_r1_anims\pt_marvin_leech_start.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_marvin_leech_idle" {
	"pete_scripted_r1_anims\pt_marvin_leech_idle.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_marvin_leech_end" {
	"pete_scripted_r1_anims\pt_marvin_leech_end.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_rspn101_melee_necksnap_rear" {
	"pete_scripted_r1_anims\pt_rspn101_melee_necksnap_rear.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 27 "weapon_catch" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_rspn101_melee_necksnap_left" {
	"pete_scripted_r1_anims\pt_rspn101_melee_necksnap_left.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 30 "weapon_catch" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_rspn101_melee_necksnap_right" {
	"pete_scripted_r1_anims\pt_rspn101_melee_necksnap_right.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 30 "weapon_catch" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_rspn101_melee_necksnap_front" {
	"pete_scripted_r1_anims\pt_rspn101_melee_necksnap_front.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 52 "weapon_catch" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_rspn101_melee_necksnap_above_back" {
	"pete_scripted_r1_anims\pt_rspn101_melee_necksnap_above_back.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_assassin_melee_necksnap_rear" {
	"pete_scripted_r1_anims\pt_assassin_melee_necksnap_rear.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 27 "weapon_catch" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_bored_check_crate_A" {
	"pete_scripted_r1_anims\pt_bored_check_crate_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_bored_check_crate_B" {
	"pete_scripted_r1_anims\pt_bored_check_crate_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_bored_idle_console_A" {
	"pete_scripted_r1_anims\pt_bored_idle_console_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_bored_idle_console_B" {
	"pete_scripted_r1_anims\pt_bored_idle_console_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_bored_idle_console_B_twitch" {
	"pete_scripted_r1_anims\pt_bored_idle_console_B_twitch.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_bored_stand_talker_A" {
	"pete_scripted_r1_anims\pt_bored_stand_talker_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_bored_stand_talker_B" {
	"pete_scripted_r1_anims\pt_bored_stand_talker_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_bored_stand_talker_A_noloop" {
	"pete_scripted_r1_anims\pt_bored_stand_talker_A_noloop.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_bored_stand_talker_B_noloop" {
	"pete_scripted_r1_anims\pt_bored_stand_talker_B_noloop.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_bored_interface_leanin" {
	"pete_scripted_r1_anims\pt_bored_interface_leanin.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_bored_interface_leanback" {
	"pete_scripted_r1_anims\pt_bored_interface_leanback.smd"
	{ event AE_CL_PLAYSOUND 159 "wargames_pt_bored_interface_leanback_buttons_only" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_bored_interface_leanback_ash" {
	"pete_scripted_r1_anims\pt_bored_interface_leanback_ash.smd"
	{ event AE_CL_PLAYSOUND 138 "wargames_pt_bored_interface_leanback" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_bored_overseer" {
	"pete_scripted_r1_anims\pt_bored_overseer.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_idle_casual_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_satchel_charge_start" {
	"pete_scripted_r1_anims\pt_satchel_charge_start.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_satchel_charge_idle" {
	"pete_scripted_r1_anims\pt_satchel_charge_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_satchel_charge_end" {
	"pete_scripted_r1_anims\pt_satchel_charge_end.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "pt_satchel_charge_interrupt" {
	"pete_scripted_r1_anims\pt_satchel_charge_interrupt.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "a_mmt_drag_soldierA" {
	"pete_scripted_r1_anims\a_mmt_drag_soldierA.smd"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "a_mmt_drag_soldierB" {
	"pete_scripted_r1_anims\a_mmt_drag_soldierB.smd"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "a_mmt_drag_prisoner" {
	"pete_scripted_r1_anims\a_mmt_drag_prisoner.smd"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "Stomped" {
	"a_stomped"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_scripted" 0 0 0 0
	fps 30
}

$sequence "SCENE_Prisoner_Search" {
	"a_search_pri"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "SCENE_Soldier_Search" {
	"a_search_sol"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "SCENE_Prisoner_Kill" {
	"a_kill_pri"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "SCENE_Soldier_Kill" {
	"a_kill_sol"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "CASUAL_idleA" {
	"a_CasualA"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "CASUAL_idleB" {
	"a_CasualB"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "CASUAL_idleA_loop" {
	"a_CasualA"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "CASUAL_idleB_loop" {
	"a_CasualB"
	activity "ACT_BUSY_QUEUE" 2
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_airbase_weapon_toss_right_A" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_right_A.smd"
	{ event AE_CL_PLAYSOUND 0 "Airbase_Scr_IMC_pt_airbase_weapon_toss_right" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_airbase_weapon_toss_right_A_idle" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_right_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_airbase_weapon_toss_right_B" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_right_B.smd"
	{ event AE_CL_PLAYSOUND 0 "Airbase_Scr_IMC_pt_airbase_weapon_toss_right" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_airbase_weapon_toss_right_B_idle" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_right_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_airbase_weapon_toss_left_A" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_left_A.smd"
	{ event AE_CL_PLAYSOUND 0 "Airbase_Scr_IMC_pt_airbase_weapon_toss_left" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_airbase_weapon_toss_left_A_idle" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_left_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_airbase_weapon_toss_left_B" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_left_B.smd"
	{ event AE_CL_PLAYSOUND 0 "Airbase_Scr_IMC_pt_airbase_weapon_toss_left" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_airbase_weapon_toss_left_B_idle" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_left_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_airbase_weapon_toss_background_A" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_background_A.smd"
	{ event AE_CL_PLAYSOUND 0 "Airbase_Scr_IMC_pt_airbase_weapon_toss_background" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_airbase_weapon_toss_background_A_idle" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_background_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_airbase_weapon_toss_background_B" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_background_B.smd"
	{ event AE_CL_PLAYSOUND 0 "Airbase_Scr_IMC_pt_airbase_weapon_toss_background" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_airbase_weapon_toss_background_B_idle" {
	"pete_scripted_r1_anims\pt_airbase_weapon_toss_background_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_dropship_rider_R_A_idle" {
	"pete_scripted_r1_anims\pt_dropship_rider_R_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 15
	loop
}

$sequence "pt_dropship_rider_R_B_idle" {
	"pete_scripted_r1_anims\pt_dropship_rider_R_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 15
	loop
}

$sequence "pt_dropship_rider_R_C_idle" {
	"pete_scripted_r1_anims\pt_dropship_rider_R_C_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 15
	loop
}

$sequence "pt_dropship_rider_L_A_idle" {
	"pete_scripted_r1_anims\pt_dropship_rider_L_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 15
	loop
}

$sequence "pt_dropship_rider_L_B_idle" {
	"pete_scripted_r1_anims\pt_dropship_rider_L_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 15
	loop
}

$sequence "pt_dropship_rider_L_C_idle" {
	"pete_scripted_r1_anims\pt_dropship_rider_L_C_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 15
	loop
}

$sequence "Militia_flyinA_idle_mac" {
	"pete_scripted_r1_anims\Militia_flyinA_idle_mac.smd"
	fadein 1
	fadeout 1
	fps 30
	loop
}

$sequence "Militia_flyinA_countdown_mac" {
	"pete_scripted_r1_anims\Militia_flyinA_countdown_mac.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "signal:dialogue" }
	fadein 1
	fadeout 1
	fps 30
}

$sequence "Classic_MP_flyin_exit_playerA_idle" {
	"pete_scripted_r1_anims\Classic_MP_flyin_exit_playerA_idle.smd"
	{ event AE_CL_PLAYSOUND 5 "PlayerA_Militia_FlyinB_Exit_WeaponFidget_02" }
	{ event AE_CL_PLAYSOUND 31 "PlayerA_Militia_FlyinB_Exit_WeaponFidget_03" }
	{ event AE_CL_PLAYSOUND 56 "PlayerA_Militia_FlyinB_Exit_WeaponFidget_04" }
	{ event AE_CL_PLAYSOUND 71 "PlayerA_Militia_FlyinB_Exit_WeaponFidget_05" }
	{ event AE_CL_PLAYSOUND 82 "PlayerA_Militia_FlyinB_Exit_WeaponFidget_06" }
	fadein 0.2
	fadeout 0.2
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
}

$sequence "Classic_MP_flyin_exit_playerA_jump" {
	"pete_scripted_r1_anims\Classic_MP_flyin_exit_playerA_jump.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 29 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 74 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 87 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 104 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 119 "SetVelocity" }
	{ event AE_SV_VSCRIPT_CALLBACK 119 "PlayFXOnLand" }
	{ event AE_CL_PLAYSOUND 33 "PlayerA_Militia_FlyinB_Exit_ClothGear_04" }
	{ event AE_CL_PLAYSOUND 52 "PlayerA_Militia_FlyinB_Exit_ClothGear_05" }
	{ event AE_CL_PLAYSOUND 36 "PlayerA_Militia_FlyinB_Exit_WeaponFidget_07" }
	fadein 0.2
	fadeout 0.2
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
}

$sequence "Classic_MP_flyin_exit_playerB_idle" {
	"pete_scripted_r1_anims\Classic_MP_flyin_exit_playerB_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
}

$sequence "Classic_MP_flyin_exit_playerB_jump" {
	"pete_scripted_r1_anims\Classic_MP_flyin_exit_playerB_jump.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 54 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 109 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 114 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 129 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 144 "SetVelocity" }
	{ event AE_SV_VSCRIPT_CALLBACK 144 "PlayFXOnLand" }
	fadein 0.2
	fadeout 0.2
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
}

$sequence "Classic_MP_flyin_exit_playerC_idle" {
	"pete_scripted_r1_anims\Classic_MP_flyin_exit_playerC_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
}

$sequence "Classic_MP_flyin_exit_playerC_jump" {
	"pete_scripted_r1_anims\Classic_MP_flyin_exit_playerC_jump.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 39 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 84 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 99 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 119 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 134 "SetVelocity" }
	{ event AE_SV_VSCRIPT_CALLBACK 134 "PlayFXOnLand" }
	fadein 0.2
	fadeout 0.2
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
}

$sequence "Classic_MP_flyin_exit_playerD_idle" {
	"pete_scripted_r1_anims\Classic_MP_flyin_exit_playerD_idle.smd"
	{ event AE_CL_PLAYSOUND 33 "PlayerD_Militia_FlyinB_Exit_ClothGear_04" }
	{ event AE_CL_PLAYSOUND 66 "PlayerD_Militia_FlyinB_Exit_ClothGear_05" }
	{ event AE_CL_PLAYSOUND 123 "PlayerD_Militia_FlyinB_Exit_ClothGear_06" }
	{ event AE_CL_PLAYSOUND 36 "PlayerD_Militia_FlyinB_Exit_WeaponFidget_02" }
	{ event AE_CL_PLAYSOUND 73 "PlayerD_Militia_FlyinB_Exit_WeaponFidget_03" }
	{ event AE_CL_PLAYSOUND 101 "PlayerD_Militia_FlyinB_Exit_WeaponFidget_04" }
	{ event AE_CL_PLAYSOUND 130 "PlayerD_Militia_FlyinB_Exit_WeaponFidget_05" }
	fadein 0.2
	fadeout 0.2
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
}

$sequence "Classic_MP_flyin_exit_playerD_jump" {
	"pete_scripted_r1_anims\Classic_MP_flyin_exit_playerD_jump.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 39 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 100 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 108 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 134 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 149 "SetVelocity" }
	{ event AE_SV_VSCRIPT_CALLBACK 149 "PlayFXOnLand" }
	{ event AE_CL_PLAYSOUND 81 "PlayerD_Militia_FlyinB_Exit_Footstep_05" }
	{ event AE_CL_PLAYSOUND 97 "PlayerD_Militia_FlyinB_Exit_Footstep_06" }
	{ event AE_CL_PLAYSOUND 108 "PlayerD_Militia_FlyinB_Exit_Footstep_07" }
	{ event AE_CL_PLAYSOUND 116 "PlayerD_Militia_FlyinB_Exit_Footstep_08" }
	fadein 0.2
	fadeout 0.2
	blendlayer "sr1_face_grunt_longidle" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_embark_A" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_embark_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 0 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 50 "ViewConeNarrow" }
	{ event AE_SV_VSCRIPT_CALLBACK 10 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_stop" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_embark_B" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_embark_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 0 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 50 "ViewConeNarrow" }
	{ event AE_SV_VSCRIPT_CALLBACK 10 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_stop" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_embark_C" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_embark_C.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 0 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 40 "ViewConeNarrow" }
	{ event AE_SV_VSCRIPT_CALLBACK 10 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_stop" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_embark_D" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_embark_D.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 0 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 40 "ViewConeNarrow" }
	{ event AE_SV_VSCRIPT_CALLBACK 10 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_stop" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_embark_E" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_embark_E.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 0 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "ViewConeNarrow" }
	{ event AE_SV_VSCRIPT_CALLBACK 10 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_stop" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_embark_F" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_embark_F.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 0 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "ViewConeNarrow" }
	{ event AE_SV_VSCRIPT_CALLBACK 10 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_stop" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_embark_G" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_embark_G.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 0 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "ViewConeNarrow" }
	{ event AE_SV_VSCRIPT_CALLBACK 10 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_stop" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_embark_H" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_embark_H.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 0 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "ViewConeNarrow" }
	{ event AE_SV_VSCRIPT_CALLBACK 10 "ShowFPSProxy" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_stop" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_e3_rescue_side_idle_A" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_idle_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_e3_rescue_side_idle_B" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_idle_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_e3_rescue_side_idle_C" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_idle_C.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_e3_rescue_side_idle_D" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_idle_D.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_e3_rescue_side_idle_E" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_idle_E.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_e3_rescue_side_idle_F" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_idle_F.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_e3_rescue_side_idle_G" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_idle_G.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_e3_rescue_side_idle_H" {
	"pete_scripted_r1_anims\pt_e3_rescue_side_idle_H.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_dp_exit_a" {
	"pete_scripted_r1_anims\pt_dp_exit_a.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 29 "enable_planting" }
	{ event AE_CL_PLAYSOUND_SPECTRE 0 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND_SPECTRE 7 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND_SPECTRE 9 "Spectre.Servo.Walk" }
	{ event AE_FOOTSTEP_R 19 "" }
	{ event AE_CL_PLAYSOUND_SPECTRE 23 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND_SPECTRE 38 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND_SPECTRE 42 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND_SPECTRE 44 "Spectre.Servo.Light.Short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_dp_exit_b" {
	"pete_scripted_r1_anims\pt_dp_exit_b.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "enable_planting" }
	{ event AE_CL_PLAYSOUND_SPECTRE 1 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND_SPECTRE 1 "Spectre.Servo.Walk" }
	{ event AE_CL_PLAYSOUND_SPECTRE 2 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND_SPECTRE 7 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND_SPECTRE 14 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND_SPECTRE 19 "Spectre.Servo.Heavy.Short" }
	{ event AE_FOOTSTEP_L 31 "" }
	{ event AE_FOOTSTEP_R 39 "" }
	{ event AE_FOOTSTEP_L 48 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_dp_exit_c" {
	"pete_scripted_r1_anims\pt_dp_exit_c.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "enable_planting" }
	{ event AE_CL_PLAYSOUND_SPECTRE 3 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND_SPECTRE 15 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND_SPECTRE 19 "Spectre.Servo.Walk" }
	{ event AE_CL_PLAYSOUND_SPECTRE 20 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_FOOTSTEP_L 25 "" }
	{ event AE_CL_PLAYSOUND_SPECTRE 32 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_FOOTSTEP_R 38 "" }
	{ event AE_CL_PLAYSOUND_SPECTRE 43 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_FOOTSTEP_R 68 "" }
	{ event AE_CL_PLAYSOUND_SPECTRE 63 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND_SPECTRE 64 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND_SPECTRE 66 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND_SPECTRE 67 "Spectre.Step.Light.Default" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_dp_exit_d" {
	"pete_scripted_r1_anims\pt_dp_exit_d.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "enable_planting" }
	{ event AE_CL_PLAYSOUND_SPECTRE 38 "Spectre.Servo.Walk" }
	{ event AE_CL_PLAYSOUND_SPECTRE 40 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_R 45 "" }
	{ event AE_FOOTSTEP_L 60 "" }
	{ event AE_CL_PLAYSOUND_SPECTRE 68 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND_SPECTRE 75 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND_SPECTRE 76 "Spectre.Servo.Light.Short" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_droppod_exit_A" {
	"a_droppod_exit_A"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_droppod_exit_B" {
	"a_droppod_exit_B"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_dp_exit_player" {
	"pete_scripted_r1_anims\pt_dp_exit_player.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "pt_dp_idle_a" {
	"a_pt_dp_idle_a"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_dp_idle_b" {
	"a_pt_dp_idle_b"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_dp_idle_c" {
	"a_pt_dp_idle_c"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_dp_idle_d" {
	"a_pt_dp_idle_d"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_dp_idle_player" {
	"a_pt_dp_idle_player"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_console_death_slideleft" {
	"pete_scripted_r1_anims\pt_console_death_slideleft.smd"
	{ event AE_CL_PLAYSOUND 0 "pt_console_death_slideleft" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_death_fallforward" {
	"pete_scripted_r1_anims\pt_console_death_fallforward.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_death_slideright" {
	"pete_scripted_r1_anims\pt_console_death_slideright.smd"
	{ event AE_CL_PLAYSOUND 0 "pt_console_death_slideright" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_pain_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_idle" {
	"pete_scripted_r1_anims\pt_console_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_Poised_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_console_runin_R" {
	"pete_scripted_r1_anims\pt_console_runin_R.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_runout_R" {
	"pete_scripted_r1_anims\pt_console_runout_R.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_runin_L" {
	"pete_scripted_r1_anims\pt_console_runin_L.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_runout_L" {
	"pete_scripted_r1_anims\pt_console_runout_L.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_react_R" {
	"pete_scripted_r1_anims\pt_console_react_R.smd"
	{ event AE_CL_PLAYSOUND 0 "pt_console_react_R" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_backin_R" {
	"pete_scripted_r1_anims\pt_console_backin_R.smd"
	{ event AE_CL_PLAYSOUND 0 "pt_console_backin_R" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_react_R_alt" {
	"pete_scripted_r1_anims\pt_console_react_R_alt.smd"
	{ event AE_CL_PLAYSOUND 0 "pt_console_react_R_alt" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_react_L" {
	"pete_scripted_r1_anims\pt_console_react_L.smd"
	{ event AE_CL_PLAYSOUND 0 "pt_console_react_L" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_backin_L" {
	"pete_scripted_r1_anims\pt_console_backin_L.smd"
	{ event AE_CL_PLAYSOUND 0 "pt_console_backin_L" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_console_react_L_alt" {
	"pete_scripted_r1_anims\pt_console_react_L_alt.smd"
	{ event AE_CL_PLAYSOUND 0 "pt_console_react_L_alt" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_MP_disembark" {
	"pete_scripted_r1_anims\pt_MP_disembark.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "pt_mount_idle" {
	"pete_scripted_r1_anims\pt_mount_idle.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "pt_MP_dismount_stand2knee" {
	"pete_scripted_r1_anims\pt_MP_dismount_stand2knee.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "pt_MP_dismount_stand2knee_idle" {
	"pete_scripted_r1_anims\pt_MP_dismount_stand2knee_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "pt_MP_mount_knee2stand" {
	"pete_scripted_r1_anims\pt_MP_mount_knee2stand.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "pt_MP_mount_knee2stand_idle" {
	"pete_scripted_r1_anims\pt_MP_mount_knee2stand_idle.smd"
	fadein 0.5
	fadeout 0.5
	fps 30
	loop
}

$sequence "pt_mount_atlas_kneel_front" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_front.smd"
	fadein 0.25
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_behind" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_left" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_right" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_front" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_front.smd"
	fadein 0.4
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_behind" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_behind.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_right" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_left" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_airgrab" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_airgrab.smd"
	fadein 0.4
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_above_right" {
	"pete_scripted_r1_anims\pt_mount_atlas_above_right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_above_left" {
	"pete_scripted_r1_anims\pt_mount_atlas_above_left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_airgrab" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_airgrab.smd"
	fadein 0.4
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_above_right" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_above_right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_above_left" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_above_left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_front_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_front_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_behind_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_behind_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_left_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_right_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_front_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_front_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_behind_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_behind_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_right_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_left_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_stand_airgrab_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_stand_airgrab_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_above_right_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_above_right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_above_left_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_above_left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_airgrab_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_airgrab_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_above_right_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_above_right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_atlas_kneel_above_left_fast" {
	"pete_scripted_r1_anims\pt_mount_atlas_kneel_above_left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 28 "phase_shift_stop" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_dismount_atlas_stand" {
	"pete_scripted_r1_anims\pt_dismount_atlas_stand.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "pt_dismount_atlas_crouch" {
	"pete_scripted_r1_anims\pt_dismount_atlas_crouch.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "pt_dismount_atlas_stand_fast" {
	"pete_scripted_r1_anims\pt_dismount_atlas_stand_fast.smd"
	fadein 0
	fadeout 0.2
	fps 60
}

$sequence "pt_dismount_atlas_crouch_fast" {
	"pete_scripted_r1_anims\pt_dismount_atlas_crouch_fast.smd"
	fadein 0
	fadeout 0.2
	fps 60
}

$sequence "pt_mount_ogre_Kneel_Front" {
	"pete_scripted_r1_anims\pt_mount_ogre_Kneel_Front.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Kneel_Behind" {
	"pete_scripted_r1_anims\pt_mount_ogre_Kneel_Behind.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Kneel_Right" {
	"pete_scripted_r1_anims\pt_mount_ogre_Kneel_Right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Kneel_Left" {
	"pete_scripted_r1_anims\pt_mount_ogre_Kneel_Left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_Front" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_Front.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_Behind" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_Behind.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_Right" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_Right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_Left" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_Left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_AirGrab" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_AirGrab.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Above_Right" {
	"pete_scripted_r1_anims\pt_mount_ogre_Above_Right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Above_Left" {
	"pete_scripted_r1_anims\pt_mount_ogre_Above_Left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_kneel_AirGrab" {
	"pete_scripted_r1_anims\pt_mount_ogre_kneel_AirGrab.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_kneel_Above_Right" {
	"pete_scripted_r1_anims\pt_mount_ogre_kneel_Above_Right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_kneel_Above_Left" {
	"pete_scripted_r1_anims\pt_mount_ogre_kneel_Above_Left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Kneel_Front_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_Kneel_Front_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Kneel_Behind_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_Kneel_Behind_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Kneel_Right_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_Kneel_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Kneel_Left_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_Kneel_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_Front_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_Front_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_Behind_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_Behind_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 35 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 40 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_Right_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_Left_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_stand_AirGrab_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_stand_AirGrab_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 25 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Above_Right_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_Above_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_Above_Left_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_Above_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 14 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 19 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_kneel_AirGrab_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_kneel_AirGrab_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 25 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_kneel_Above_Right_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_kneel_Above_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 14 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 19 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_ogre_kneel_Above_Left_fast" {
	"pete_scripted_r1_anims\pt_mount_ogre_kneel_Above_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "Pt_OgreDisembark_Kneel_Crouch" {
	"pete_scripted_r1_anims\Pt_OgreDisembark_Kneel_Crouch.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_dismount_ogre_stand" {
	"pete_scripted_r1_anims\pt_dismount_ogre_stand.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "pt_dismount_ogre_stand_fast" {
	"pete_scripted_r1_anims\pt_dismount_ogre_stand_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 60
}

$sequence "pt_dismount_ogre_crouch" {
	"pete_scripted_r1_anims\pt_dismount_ogre_crouch.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "pt_dismount_ogre_crouch_fast" {
	"pete_scripted_r1_anims\pt_dismount_ogre_crouch_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 60
}

$sequence "pt_mount_stryder_Kneel_Front" {
	"pete_scripted_r1_anims\pt_mount_stryder_Kneel_Front.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Kneel_Behind" {
	"pete_scripted_r1_anims\pt_mount_stryder_Kneel_Behind.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Kneel_Right" {
	"pete_scripted_r1_anims\pt_mount_stryder_Kneel_Right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Kneel_Left" {
	"pete_scripted_r1_anims\pt_mount_stryder_Kneel_Left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_Front" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_Front.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 12 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_Behind" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_Behind.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 34 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_Right" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_Right.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 12 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_Left" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_Left.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 12 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_AirGrab" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_AirGrab.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Above_Right" {
	"pete_scripted_r1_anims\pt_mount_stryder_Above_Right.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 32 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Above_Left" {
	"pete_scripted_r1_anims\pt_mount_stryder_Above_Left.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 32 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_kneel_AirGrab" {
	"pete_scripted_r1_anims\pt_mount_stryder_kneel_AirGrab.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 5 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_kneel_Above_Right" {
	"pete_scripted_r1_anims\pt_mount_stryder_kneel_Above_Right.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 32 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_kneel_Above_Left" {
	"pete_scripted_r1_anims\pt_mount_stryder_kneel_Above_Left.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 32 "HMN_Jump_Jet_DBL" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Kneel_Front_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_Kneel_Front_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Kneel_Behind_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_Kneel_Behind_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Kneel_Right_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_Kneel_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Kneel_Left_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_Kneel_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_Front_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_Front_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_Behind_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_Behind_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_Right_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_Left_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_stand_AirGrab_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_stand_AirGrab_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Above_Right_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_Above_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_Above_Left_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_Above_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_kneel_AirGrab_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_kneel_AirGrab_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_kneel_Above_Right_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_kneel_Above_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_stryder_kneel_Above_Left_fast" {
	"pete_scripted_r1_anims\pt_mount_stryder_kneel_Above_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_dismount_stryder_stand" {
	"pete_scripted_r1_anims\pt_dismount_stryder_stand.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 30 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 40 "SetVelocity" }
	fadein 0
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_dismount_stryder_stand_fast" {
	"pete_scripted_r1_anims\pt_dismount_stryder_stand_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 30 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 40 "SetVelocity" }
	fadein 0
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 60
}

$sequence "pt_dismount_stryder_crouch" {
	"pete_scripted_r1_anims\pt_dismount_stryder_crouch.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 30 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 40 "SetVelocity" }
	fadein 0
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_dismount_stryder_crouch_fast" {
	"pete_scripted_r1_anims\pt_dismount_stryder_crouch_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 30 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 40 "SetVelocity" }
	fadein 0
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	snap
	fps 60
}

$sequence "pt_mount_buddy_kneel_front" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_front.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_behind" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_behind.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_left" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_right" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_airgrab" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_airgrab.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_above_left" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_above_left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_above_right" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_above_right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_front" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_front.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_behind" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_behind.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_left" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_right" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_airgrab" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_airgrab.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_above_left" {
	"pete_scripted_r1_anims\pt_mount_buddy_above_left.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_above_right" {
	"pete_scripted_r1_anims\pt_mount_buddy_above_right.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_front_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_front_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_behind_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_behind_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_left_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_left_fast.smd"
	fadein 0.4
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_right_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_right_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_airgrab_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_airgrab_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_above_left_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_above_left_fast.smd"
	fadein 0.4
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_kneel_above_right_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_kneel_above_right_fast.smd"
	fadein 0.4
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_front_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_front_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_behind_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_behind_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_left_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_left_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_right_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_right_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_stand_airgrab_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_stand_airgrab_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_above_left_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_above_left_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_mount_buddy_above_right_fast" {
	"pete_scripted_r1_anims\pt_mount_buddy_above_right_fast.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_buddy_getout" {
	"pete_scripted_r1_anims\pt_buddy_getout.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 60
}

$sequence "pt_dismount_buddy_stand" {
	"pete_scripted_r1_anims\pt_dismount_buddy_stand.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "pt_dismount_buddy_crouch" {
	"pete_scripted_r1_anims\pt_dismount_buddy_crouch.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "pt_dismount_buddy_stand_fast" {
	"pete_scripted_r1_anims\pt_dismount_buddy_stand_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 60
}

$sequence "pt_dismount_buddy_crouch_fast" {
	"pete_scripted_r1_anims\pt_dismount_buddy_crouch_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 60
}

$sequence "pt_rodeo_ride_R_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_ride_R_hijack_battery.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "rodeo_battery_stealth_movement_warning" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "rodeo_battery_show" }
	{ event AE_SV_VSCRIPT_CALLBACK 50 "signal:RodeoPointOfNoReturn" }
	{ event AE_SV_VSCRIPT_CALLBACK 73 "rodeo_battery_rip" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_ride_R_return_battery" {
	"pete_scripted_r1_anims\pt_rodeo_ride_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_ride_L_return_battery" {
	"pete_scripted_r1_anims\pt_rodeo_ride_L_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_nuke_rodeo_ride_R_return_battery" {
	"pete_scripted_r1_anims\pt_nuke_rodeo_ride_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_ride_F_idle" {
	"pete_scripted_r1_anims\pt_rodeo_ride_F_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_rodeo_ride_L_idle" {
	"pete_scripted_r1_anims\pt_rodeo_ride_L_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_rodeo_trans_F2L" {
	"pete_scripted_r1_anims\pt_rodeo_trans_F2L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_trans_F2R" {
	"pete_scripted_r1_anims\pt_rodeo_trans_F2R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_trans_L2F" {
	"pete_scripted_r1_anims\pt_rodeo_trans_L2F.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_trans_L2R" {
	"pete_scripted_r1_anims\pt_rodeo_trans_L2R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_trans_R2F" {
	"pete_scripted_r1_anims\pt_rodeo_trans_R2F.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_trans_R2L" {
	"pete_scripted_r1_anims\pt_rodeo_trans_R2L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_entrance_F_front" {
	"pete_scripted_r1_anims\pt_rodeo_entrance_F_front.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_entrance_L_left" {
	"pete_scripted_r1_anims\pt_rodeo_entrance_L_left.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_entrance_R_right" {
	"pete_scripted_r1_anims\pt_rodeo_entrance_R_right.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_atlas_front_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_atlas_front_hijack_battery.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 14 "rodeo_battery_show" }
	{ event AE_SV_VSCRIPT_CALLBACK 69 "rodeo_battery_rip" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_atlas_back_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_atlas_back_hijack_battery.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 14 "rodeo_battery_show" }
	{ event AE_SV_VSCRIPT_CALLBACK 69 "rodeo_battery_rip" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_atlas_left_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_atlas_left_hijack_battery.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 14 "rodeo_battery_show" }
	{ event AE_SV_VSCRIPT_CALLBACK 69 "rodeo_battery_rip" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_atlas_right_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_atlas_right_hijack_battery.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 14 "rodeo_battery_show" }
	{ event AE_SV_VSCRIPT_CALLBACK 69 "rodeo_battery_rip" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_Piggyback_idle_back" {
	"pete_scripted_r1_anims\pt_Piggyback_idle_back.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_rodeo_move_atlas_back_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_back_entrance.smd"
	fadein 0.25
	fadeout 0.5
	fps 30
}

$sequence "pt_rodeo_move_atlas_front_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_front_entrance.smd"
	fadein 0.25
	fadeout 0.5
	fps 30
}

$sequence "pt_rodeo_move_atlas_front_lower_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_front_lower_entrance.smd"
	fadein 0.25
	fadeout 0.5
	fps 30
}

$sequence "pt_rodeo_move_atlas_left_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_left_entrance.smd"
	fadein 0.25
	fadeout 0.5
	fps 30
}

$sequence "pt_rodeo_move_atlas_right_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_right_entrance.smd"
	fadein 0.25
	fadeout 0.5
	fps 30
}

$sequence "pt_rodeo_move_atlas_back_lower_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_back_lower_entrance.smd"
	fadein 0.25
	fadeout 0.5
	fps 30
}

$sequence "pt_rodeo_move_atlas_back_mid_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_back_mid_entrance.smd"
	fadein 0.25
	fadeout 0.5
	fps 30
}

$sequence "pt_rodeo_move_atlas_back_entrance_Fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_back_entrance_Fast.smd"
	fadein 0.5
	fadeout 0.1
	fps 60
}

$sequence "pt_rodeo_move_atlas_front_entrance_Fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_front_entrance_Fast.smd"
	fadein 0.25
	fadeout 0.1
	fps 60
}

$sequence "pt_rodeo_move_atlas_front_lower_entrance_Fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_front_lower_entrance_Fast.smd"
	fadein 0.25
	fadeout 0.1
	fps 60
}

$sequence "pt_rodeo_move_atlas_left_entrance_Fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_left_entrance_Fast.smd"
	fadein 0.5
	fadeout 0.1
	fps 60
}

$sequence "pt_rodeo_move_atlas_right_entrance_Fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_right_entrance_Fast.smd"
	fadein 0.25
	fadeout 0.1
	fps 60
}

$sequence "pt_rodeo_move_atlas_back_lower_entrance_Fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_back_lower_entrance_Fast.smd"
	fadein 0.1
	fadeout 0.1
	fps 60
}

$sequence "pt_rodeo_move_atlas_back_mid_entrance_Fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_back_mid_entrance_Fast.smd"
	fadein 0.5
	fadeout 0.1
	fps 60
}

$sequence "pt_rodeo_panel_opening" {
	"pete_scripted_r1_anims\pt_rodeo_panel_opening.smd"
	fadein 0.25
	fadeout 0.25
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_rodeo_panel_fire" {
	"a_pt_rodeo_panel"
	activity "ACT_SCRIPT_CUSTOM_ATTACK" 1
	fadein 0
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_panel_aim_idle_move" {
	"a_pt_rodeo_panel"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 60
	loop
}

$sequence "pt_rodeo_jump" {
	"pete_scripted_r1_anims\pt_rodeo_jump.smd"
	{ event AE_CL_PLAYSOUND_SPECTRE 1 "Spectre.Servo.Heavy.Short" }
	{ event AE_FOOTSTEP_R 7 "" }
	{ event AE_CL_PLAYSOUND_SPECTRE 7 "Robot.Land.Default_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_panel_aim_idle" {
	"pete_scripted_r1_anims\pt_rodeo_panel_aim_idle.smd"
	fadein 0
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_rodeo_player_side_lean" {
	"pete_scripted_r1_anims\pt_rodeo_player_side_lean.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_rodeo_stryder_panel_opening" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_panel_opening.smd"
	fadein 0.2
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_rodeo_stryder_panel_fire" {
	"a_pt_rodeo_stryder_panel"
	activity "ACT_SCRIPT_CUSTOM_ATTACK" 1
	fadein 0
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_stryder_panel_aim_idle_move" {
	"a_pt_rodeo_stryder_panel"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 60
	loop
}

$sequence "pt_rodeo_stryder_panel_aim_idle" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_panel_aim_idle.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_rodeo_stryder_player_side_lean" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_player_side_lean.smd"
	fadein 0
	fadeout 0
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_rodeo_ogre_panel_opening" {
	"pete_scripted_r1_anims\pt_rodeo_ogre_panel_opening.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "Aim_ht_rodeo_360" {
	"a_aim_ht_rodeo360_up_left_far"
	"a_aim_ht_rodeo360_up_left"
	"a_aim_ht_rodeo360_up_center"
	"a_aim_ht_rodeo360_up_right"
	"a_aim_ht_rodeo360_up_right_far"
	"a_aim_ht_rodeo360_mid_left_far"
	"a_aim_ht_rodeo360_mid_left"
	"a_aim_ht_rodeo360_mid_center"
	"a_aim_ht_rodeo360_mid_right"
	"a_aim_ht_rodeo360_mid_right_far"
	"a_aim_ht_rodeo360_down_left_far"
	"a_aim_ht_rodeo360_down_left"
	"a_aim_ht_rodeo360_down_center"
	"a_aim_ht_rodeo360_down_right"
	"a_aim_ht_rodeo360_down_right_far"
}

$sequence "pt_rodeo_ogre_panel_fire" {
	"a_pt_rodeo_ogre_panel"
	activity "ACT_SCRIPT_CUSTOM_ATTACK" 1
	fadein 0
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_ogre_panel_aim_idle_move" {
	"a_pt_rodeo_ogre_panel"
	fadein 0
	fadeout 0
	addlayer "Aim_ht_rodeo_360"
	fps 60
	loop
}

$sequence "pt_rodeo_ogre_player_side_lean" {
	"pete_scripted_r1_anims\pt_rodeo_ogre_player_side_lean.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "pt_rodeo_move_atlas_back_idle" {
	"pete_scripted_r1_anims\pt_rodeo_move_atlas_back_idle.smd"
	fadein 0
	fadeout 0.25
	fps 30
	loop
}

$sequence "pt_rodeo_death_back" {
	"pete_scripted_r1_anims\pt_rodeo_death_back.smd"
	{ event AE_RAGDOLL 13 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_move_stryder_back_idle" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_back_idle.smd"
	fadein 0.25
	fadeout 0
	fps 30
	loop
}

$sequence "pt_rodeo_move_stryder_back_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_back_entrance.smd"
	fadein 0.5
	fadeout 0
	fps 30
}

$sequence "pt_rodeo_move_stryder_front_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_front_entrance.smd"
	fadein 0.5
	fadeout 0
	fps 30
}

$sequence "pt_rodeo_move_stryder_front_lower_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_front_lower_entrance.smd"
	fadein 0.25
	fadeout 0
	fps 30
}

$sequence "pt_rodeo_move_stryder_back_lower_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_back_lower_entrance.smd"
	fadein 0.5
	fadeout 0
	fps 30
}

$sequence "pt_rodeo_move_stryder_back_mid_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_back_mid_entrance.smd"
	fadein 0.5
	fadeout 0
	fps 30
}

$sequence "pt_rodeo_move_stryder_left_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_left_entrance.smd"
	fadein 0.25
	fadeout 0
	fps 30
}

$sequence "pt_rodeo_move_stryder_right_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_right_entrance.smd"
	fadein 0.25
	fadeout 0
	fps 30
}

$sequence "pt_rodeo_move_stryder_back_entrance_fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_back_entrance_fast.smd"
	fadein 0.5
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_move_stryder_front_entrance_fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_front_entrance_fast.smd"
	fadein 0.5
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_move_stryder_front_lower_entrance_fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_front_lower_entrance_fast.smd"
	fadein 0.25
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_move_stryder_back_lower_entrance_fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_back_lower_entrance_fast.smd"
	fadein 0.5
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_move_stryder_back_mid_entrance_fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_back_mid_entrance_fast.smd"
	fadein 0.5
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_move_stryder_left_entrance_fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_left_entrance_fast.smd"
	fadein 0.25
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_move_stryder_right_entrance_fast" {
	"pete_scripted_r1_anims\pt_rodeo_move_stryder_right_entrance_fast.smd"
	fadein 0.25
	fadeout 0
	fps 60
}

$sequence "pt_rodeo_stryder_ride_R_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_ride_R_hijack_battery.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 15 "rodeo_battery_show" }
	{ event AE_SV_VSCRIPT_CALLBACK 15 "rodeo_battery_stealth_movement_warning" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "signal:RodeoPointOfNoReturn" }
	{ event AE_SV_VSCRIPT_CALLBACK 75 "rodeo_battery_rip" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_stryder_ride_R_return_battery" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_ride_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_stryder_ride_L_return_battery" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_ride_L_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_nuke_rodeo_stryder_ride_R_return_battery" {
	"pete_scripted_r1_anims\pt_nuke_rodeo_stryder_ride_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_stryder_ride_F_idle" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_ride_F_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_rodeo_stryder_ride_L_idle" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_ride_L_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_rodeo_stryder_ride_R_idle" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_ride_R_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_rodeo_stryder_trans_F2L" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_trans_F2L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_stryder_trans_F2R" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_trans_F2R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_stryder_trans_L2F" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_trans_L2F.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_stryder_trans_L2R" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_trans_L2R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_stryder_trans_R2F" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_trans_R2F.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_stryder_trans_R2L" {
	"pete_scripted_r1_anims\pt_rodeo_stryder_trans_R2L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_stryder_front_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_stryder_front_hijack_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_stryder_back_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_stryder_back_hijack_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_stryder_left_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_stryder_left_hijack_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_stryder_right_hijack_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_stryder_right_hijack_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_stryder_front_return_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_stryder_front_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_stryder_back_return_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_stryder_back_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_stryder_left_return_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_stryder_left_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_3P_stryder_right_return_battery" {
	"pete_scripted_r1_anims\pt_rodeo_3P_stryder_right_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_move_buddy_back_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_buddy_back_entrance.smd"
	fadein 0.5
	fadeout 0.1
	fps 30
}

$sequence "pt_rodeo_move_buddy_back_idle" {
	"pete_scripted_r1_anims\pt_rodeo_move_buddy_back_idle.smd"
	fadein 0
	fadeout 0.25
	fps 30
	loop
}

$sequence "pt_rodeo_move_buddy_back_lower_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_buddy_back_lower_entrance.smd"
	fadein 0.5
	fadeout 0.1
	fps 30
}

$sequence "pt_rodeo_move_buddy_back_mid_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_buddy_back_mid_entrance.smd"
	fadein 0.5
	fadeout 0.1
	fps 30
}

$sequence "pt_rodeo_move_buddy_front_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_buddy_front_entrance.smd"
	fadein 0.25
	fadeout 0.1
	fps 30
}

$sequence "pt_rodeo_move_buddy_front_lower_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_buddy_front_lower_entrance.smd"
	fadein 0.25
	fadeout 0.1
	fps 30
}

$sequence "pt_rodeo_move_buddy_left_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_buddy_left_entrance.smd"
	fadein 0.5
	fadeout 0.2
	fps 30
}

$sequence "pt_rodeo_move_buddy_right_entrance" {
	"pete_scripted_r1_anims\pt_rodeo_move_buddy_right_entrance.smd"
	fadein 0.25
	fadeout 0.1
	fps 30
}

$sequence "pt_zipline_ready_idleA" {
	"pete_scripted_r1_anims\pt_zipline_ready_idleA.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_zipline_ready_idleB" {
	"pete_scripted_r1_anims\pt_zipline_ready_idleB.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_zipline_ready2slide" {
	"pete_scripted_r1_anims\pt_zipline_ready2slide.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_zipline_slide_idle" {
	"pete_scripted_r1_anims\pt_zipline_slide_idle.smd"
	activity "ACT_ZIPLINING" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_zipline_start" {
	"pete_scripted_r1_anims\pt_zipline_start.smd"
	activity "ACT_ZIPLINE_MOUNT" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_zipline_land" {
	"pete_scripted_r1_anims\pt_zipline_land.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 11 "enable_planting" }
	{ event AE_CL_PLAYSOUND 12 "grunt_land" }
	{ event AE_FOOTSTEP_R 36 "" }
	{ event AE_FOOTSTEP_L 41 "" }
	{ event AE_FOOTSTEP_R 62 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_zipline_dismount_standF" {
	"pete_scripted_r1_anims\pt_zipline_dismount_standF.smd"
	{ event AE_CL_PLAYSOUND 9 "grunt_land" }
	{ event AE_FOOTSTEP_R 21 "" }
	{ event AE_CL_PLAYSOUND 22 "grunt_rifle_mvmt" }
	{ event AE_FOOTSTEP_L 31 "" }
	{ event AE_FOOTSTEP_L 41 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_zipline_dismount_runF" {
	"pete_scripted_r1_anims\pt_zipline_dismount_runF.smd"
	{ event AE_CL_PLAYSOUND 14 "grunt_land" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_zipline_dismount_crouchF" {
	"pete_scripted_r1_anims\pt_zipline_dismount_crouchF.smd"
	{ event AE_NPC_SET_STANCE 38 "crouch" }
	{ event AE_CL_PLAYSOUND 9 "grunt_land" }
	{ event AE_FOOTSTEP_R 27 "" }
	{ event AE_FOOTSTEP_L 36 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_zipline_dismount_crouch180" {
	"pete_scripted_r1_anims\pt_zipline_dismount_crouch180.smd"
	{ event AE_NPC_SET_STANCE 38 "crouch" }
	{ event AE_CL_PLAYSOUND 11 "grunt_land" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 22 "grunt_rifle_mvmt" }
	{ event AE_FOOTSTEP_L 36 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_zipline_dismount_breakright" {
	"pete_scripted_r1_anims\pt_zipline_dismount_breakright.smd"
	{ event AE_NPC_SET_STANCE 60 "crouch" }
	{ event AE_CL_PLAYSOUND 8 "grunt_land" }
	{ event AE_FOOTSTEP_R 19 "" }
	{ event AE_FOOTSTEP_L 37 "" }
	{ event AE_FOOTSTEP_R 48 "" }
	{ event AE_FOOTSTEP_L 55 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_O2_briefing_crew_R" {
	"pete_scripted_r1_anims\pt_O2_briefing_crew_R.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_O2_briefing_crew_L" {
	"pete_scripted_r1_anims\pt_O2_briefing_crew_L.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_ds_side_intro_gen_idle_A" {
	"pete_scripted_r1_anims\pt_ds_side_intro_gen_idle_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_medium_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_ds_side_intro_gen_idle_B" {
	"pete_scripted_r1_anims\pt_ds_side_intro_gen_idle_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_medium_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_ds_side_intro_gen_idle_C" {
	"pete_scripted_r1_anims\pt_ds_side_intro_gen_idle_C.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_medium_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_ds_side_intro_gen_idle_D" {
	"pete_scripted_r1_anims\pt_ds_side_intro_gen_idle_D.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_medium_scripted" 0 0 0 0
	fps 30
	loop
}

$sequence "pt_ds_side_intro_gen_exit_A" {
	"pete_scripted_r1_anims\pt_ds_side_intro_gen_exit_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 464 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 484 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 465 "dropship_deploy" }
	fadein 0.5
	fadeout 0.2
	blendlayer "add_face_flyin_long_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_ds_side_intro_gen_exit_B" {
	"pete_scripted_r1_anims\pt_ds_side_intro_gen_exit_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 457 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 477 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 465 "dropship_deploy" }
	fadein 0.5
	fadeout 0.2
	blendlayer "add_face_flyin_long_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_ds_side_intro_gen_exit_C" {
	"pete_scripted_r1_anims\pt_ds_side_intro_gen_exit_C.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 448 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 468 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 465 "dropship_deploy" }
	fadein 0.5
	fadeout 0.2
	blendlayer "add_face_flyin_long_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_ds_side_intro_gen_exit_D" {
	"pete_scripted_r1_anims\pt_ds_side_intro_gen_exit_D.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 450 "ViewConeTight" }
	{ event AE_SV_VSCRIPT_CALLBACK 470 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 465 "dropship_deploy" }
	fadein 0.5
	fadeout 0.2
	blendlayer "add_face_flyin_long_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_ds_coop_side_intro_gen_idle_A" {
	"pete_scripted_r1_anims\pt_ds_coop_side_intro_gen_idle_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_medium_scripted" 0 0 0 0
	snap
	fps 30
	loop
}

$sequence "pt_ds_coop_side_intro_gen_idle_B" {
	"pete_scripted_r1_anims\pt_ds_coop_side_intro_gen_idle_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_medium_scripted" 0 0 0 0
	snap
	fps 30
	loop
}

$sequence "pt_ds_coop_side_intro_gen_idle_C" {
	"pete_scripted_r1_anims\pt_ds_coop_side_intro_gen_idle_C.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_medium_scripted" 0 0 0 0
	snap
	fps 30
	loop
}

$sequence "pt_ds_coop_side_intro_gen_idle_D" {
	"pete_scripted_r1_anims\pt_ds_coop_side_intro_gen_idle_D.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_medium_scripted" 0 0 0 0
	snap
	fps 30
	loop
}

$sequence "pt_ds_coop_side_intro_gen_exit_A" {
	"pete_scripted_r1_anims\pt_ds_coop_side_intro_gen_exit_A.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 54 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 35 "dropship_deploy" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_long_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_ds_coop_side_intro_gen_exit_B" {
	"pete_scripted_r1_anims\pt_ds_coop_side_intro_gen_exit_B.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 47 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 35 "dropship_deploy" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_long_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_ds_coop_side_intro_gen_exit_C" {
	"pete_scripted_r1_anims\pt_ds_coop_side_intro_gen_exit_C.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 38 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 35 "dropship_deploy" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_long_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_ds_coop_side_intro_gen_exit_D" {
	"pete_scripted_r1_anims\pt_ds_coop_side_intro_gen_exit_D.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 40 "SkyScaleDefault" }
	{ event AE_SV_VSCRIPT_CALLBACK 35 "dropship_deploy" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_flyin_long_scripted" 0 0 0 0
	snap
	fps 30
}

$sequence "pt_colony_execution_idle" {
	"pete_scripted_r1_anims\pt_colony_execution_idle.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_colony_execution" {
	"pete_scripted_r1_anims\pt_colony_execution.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 436 "impact_flesh start_at_attachment HEADSHOT" }
	{ event AE_SV_VSCRIPT_CALLBACK 465 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "sp_colony_execution_idle" {
	"pete_scripted_r1_anims\sp_colony_execution_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "sp_colony_execution" {
	"pete_scripted_r1_anims\sp_colony_execution.smd"
	{ event AE_NPC_WEAPON_FIRE 426 "" }
	{ event AE_NPC_WEAPON_FIRE 427 "" }
	{ event AE_NPC_WEAPON_FIRE 428 "" }
	{ event AE_NPC_WEAPON_FIRE 429 "" }
	{ event AE_CL_PLAYSOUND 11 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 18 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 32 "Spectre.Step.Light.Default" }
	{ event AE_FOOTSTEP_R 39 "" }
	{ event AE_CL_PLAYSOUND 43 "Spectre.Servo.Heavy.Short" }
	{ event AE_FOOTSTEP_L 56 "" }
	{ event AE_CL_PLAYSOUND 73 "Spectre.Step.Light.Default" }
	{ event AE_FOOTSTEP_L 84 "" }
	{ event AE_FOOTSTEP_R 100 "" }
	{ event AE_FOOTSTEP_L 110 "" }
	{ event AE_CL_PLAYSOUND 125 "Spectre.Step.Light.Default" }
	{ event AE_FOOTSTEP_L 139 "" }
	{ event AE_CL_PLAYSOUND 149 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 150 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 159 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 169 "Spectre.Servo.Walk" }
	{ event AE_FOOTSTEP_R 187 "" }
	{ event AE_FOOTSTEP_L 201 "" }
	{ event AE_FOOTSTEP_R 224 "" }
	{ event AE_CL_PLAYSOUND 235 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 236 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 259 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 280 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 289 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 305 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 318 "Spectre.Servo.Heavy.Short" }
	{ event AE_CL_PLAYSOUND 344 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 356 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_R 359 "" }
	{ event AE_CL_PLAYSOUND 382 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 382 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 404 "Spectre.Servo.HeadPivot.Long" }
	{ event AE_CL_PLAYSOUND 404 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 410 "Spectre.Step.Light.Default" }
	{ event AE_CL_PLAYSOUND 445 "Spectre.Servo.Walk" }
	{ event AE_FOOTSTEP_L 456 "" }
	{ event AE_FOOTSTEP_R 475 "" }
	{ event AE_CL_PLAYSOUND 479 "Spectre.Servo.Heavy.Short" }
	{ event AE_FOOTSTEP_R 486 "" }
	{ event AE_CL_PLAYSOUND 495 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 502 "Spectre.Step.Light.Default" }
	{ event AE_FOOTSTEP_L 511 "" }
	{ event AE_CL_PLAYSOUND 511 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 526 "Spectre.Servo.Light.Short" }
	{ event AE_FOOTSTEP_R 529 "" }
	{ event AE_CL_PLAYSOUND 558 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 574 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 584 "Spectre.Servo.HeadPivot.Short" }
	{ event AE_CL_PLAYSOUND 594 "Spectre.Servo.HeadPivot.Long" }
	{ event AE_CL_PLAYSOUND 596 "Spectre.Servo.Light.Short" }
	{ event AE_CL_PLAYSOUND 608 "Spectre.Servo.Walk" }
	{ event AE_FOOTSTEP_L 622 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_colony_intro_ambush_kill_sol1" {
	"pete_scripted_r1_anims\pt_colony_intro_ambush_kill_sol1.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 307 "grunt_waves" }
	{ event AE_SV_VSCRIPT_CALLBACK 393 "signal:aiskit_doomed" }
	{ event AE_SV_VSCRIPT_CALLBACK 460 "kill" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_colony_intro_ambush_kill_sol2" {
	"pete_scripted_r1_anims\pt_colony_intro_ambush_kill_sol2.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_focused_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_colony_intro_ambush_kill_sol1_idle" {
	"pete_scripted_r1_anims\pt_colony_intro_ambush_kill_sol1_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_colony_intro_ambush_kill_sol2_idle" {
	"pete_scripted_r1_anims\pt_colony_intro_ambush_kill_sol2_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_roofdrop" {
	"pete_scripted_r1_anims\pt_roofdrop.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_corpse_patrol_A_idle" {
	"pete_scripted_r1_anims\pt_corpse_patrol_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_corpse_patrol_A" {
	"pete_scripted_r1_anims\pt_corpse_patrol_A.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_angryPose_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_corpse_patrol_A_2_idle" {
	"pete_scripted_r1_anims\pt_corpse_patrol_A_2_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_corpse_patrol_A_2" {
	"pete_scripted_r1_anims\pt_corpse_patrol_A_2.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_angryPose_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_corpse_patrol_B_idle" {
	"pete_scripted_r1_anims\pt_corpse_patrol_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_corpse_patrol_B" {
	"pete_scripted_r1_anims\pt_corpse_patrol_B.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_angryPose_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_corpse_patrol_B_2_idle" {
	"pete_scripted_r1_anims\pt_corpse_patrol_B_2_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_corpse_patrol_B_2" {
	"pete_scripted_r1_anims\pt_corpse_patrol_B_2.smd"
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_angryPose_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_outpost_spectre_activation" {
	"pete_scripted_r1_anims\pt_outpost_spectre_activation.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_outpost_spectre_activation_idle" {
	"pete_scripted_r1_anims\pt_outpost_spectre_activation_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_titan_activation_crew_idle" {
	"pete_scripted_r1_anims\pt_titan_activation_crew_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_titan_activation_pilot_idle" {
	"pete_scripted_r1_anims\pt_titan_activation_pilot_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_titan_activation_crew" {
	"pete_scripted_r1_anims\pt_titan_activation_crew.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_titan_activation_pilot" {
	"pete_scripted_r1_anims\pt_titan_activation_pilot.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_flyer_PicksUp_Soldier" {
	"pete_scripted_r1_anims\pt_flyer_PicksUp_Soldier.smd"
	{ event AE_CL_PLAYSOUND 38 "Grunt_FearOfFlyer" }
	{ event AE_SV_VSCRIPT_CALLBACK 112 "flyer_pickup" }
	{ event AE_CL_PLAYSOUND 218 "Grunt_DroppedByFlyer" }
	{ event AE_RAGDOLL 225 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_flyer_pickingup_soldier_dive" {
	"pete_scripted_r1_anims\pt_flyer_pickingup_soldier_dive.smd"
	{ event AE_CL_PLAYSOUND 48 "Grunt_FearOfFlyer" }
	{ event AE_CL_PLAYSOUND 148 "Grunt_DroppedByFlyer" }
	{ event AE_SV_VSCRIPT_CALLBACK 59 "flyer_pickup" }
	{ event AE_RAGDOLL 154 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_flyer_PicksUp_Soldier_intro" {
	"pete_scripted_r1_anims\pt_flyer_PicksUp_Soldier_intro.smd"
	{ event AE_CL_PLAYSOUND 38 "Grunt_FearOfFlyer" }
	{ event AE_SV_VSCRIPT_CALLBACK 96 "flyer_pickup" }
	{ event AE_CL_PLAYSOUND 238 "Grunt_DroppedByFlyer" }
	{ event AE_RAGDOLL 248 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_flyer_PicksUp_Spectre" {
	"pete_scripted_r1_anims\pt_flyer_PicksUp_Spectre.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 112 "flyer_pickup" }
	{ event AE_RAGDOLL 225 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_flyer_pickingup_spectre_dive" {
	"pete_scripted_r1_anims\pt_flyer_pickingup_spectre_dive.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 59 "flyer_pickup" }
	{ event AE_RAGDOLL 154 "" }
	fadein 0.2
	fadeout 0.2
	blendlayer "add_face_fierce_scripted" 0 0 0 0
	fps 30
}

$sequence "pt_trailer_grave_crouching" {
	"pete_scripted_r1_anims\pt_trailer_grave_crouching.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 608 "level_signal:bird_burst_distant" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_trailer_grave_standing" {
	"pete_scripted_r1_anims\pt_trailer_grave_standing.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 684 "level_signal:bird_burst_distant" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "diag_vdu_default" {
	"pete_scripted_r1_anims\diag_vdu_default.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_low_tension" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_low_tension.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_medium_tension" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_medium_tension.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_high_tension" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_high_tension.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_distracted" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_distracted.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_drinking_idle" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_drinking_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_drink" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_drink.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_drinking_point" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_drinking_point.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_drinking_closelook" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_drinking_closelook.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_drinking_closerlook" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_drinking_closerlook.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_drinking_typing" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_drinking_typing.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_smoking" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_smoking.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_smoking_ashing" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_smoking_ashing.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_smoking_typing" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_smoking_typing.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_dispatcher_smoking_relaxed" {
	"pete_scripted_r1_anims\pt_VDU_dispatcher_smoking_relaxed.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_pilot_smooth" {
	"pete_scripted_r1_anims\pt_VDU_pilot_smooth.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_pilot_rough" {
	"pete_scripted_r1_anims\pt_VDU_pilot_rough.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_pilot_rough_alt" {
	"pete_scripted_r1_anims\pt_VDU_pilot_rough_alt.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_pilot_damaged" {
	"pete_scripted_r1_anims\pt_VDU_pilot_damaged.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "pt_VDU_soldier_spotted" {
	"pete_scripted_r1_anims\pt_VDU_soldier_spotted.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_VDU_soldier_update" {
	"pete_scripted_r1_anims\pt_VDU_soldier_update.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "CustomVDUTest_bored_walk" {
	"pete_scripted_r1_anims\CustomVDUTest_bored_walk.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 235 "close_vdu" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_VDU_necksnap" {
	"pete_scripted_r1_anims\pt_VDU_necksnap.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_melee_sync_front_pilotkill_1st" {
	"pete_scripted_r1_anims\pt_melee_sync_front_pilotkill_1st.smd"
	{ event AE_RAGDOLL 87 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_melee_sync_front_pilotkill_3rd" {
	"pete_scripted_r1_anims\pt_melee_sync_front_pilotkill_3rd.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_stry_melee_sync_front_pilotkill_1st" {
	"pete_scripted_r1_anims\pt_stry_melee_sync_front_pilotkill_1st.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 80 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_stry_melee_sync_front_pilotkill_3rd" {
	"pete_scripted_r1_anims\pt_stry_melee_sync_front_pilotkill_3rd.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 80 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_execution_victim_laser" {
	"pete_scripted_r1_anims\pt_execution_victim_laser.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 90 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_execution_victim_ion_prime" {
	"pete_scripted_r1_anims\pt_execution_victim_ion_prime.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 125 "pink_mist" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "pt_execution_victim_tone" {
	"pete_scripted_r1_anims\pt_execution_victim_tone.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 106 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_lt_execution_victim_sword_01" {
	"pete_scripted_r1_anims\pt_lt_execution_victim_sword_01.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 108 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_ht_execution_victim_sword_01" {
	"pete_scripted_r1_anims\pt_ht_execution_victim_sword_01.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 108 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_mt_execution_victim_sword_01" {
	"pete_scripted_r1_anims\pt_mt_execution_victim_sword_01.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 108 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_lt_execution_victim_sword_02" {
	"pete_scripted_r1_anims\pt_lt_execution_victim_sword_02.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 129 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_ht_execution_victim_sword_02" {
	"pete_scripted_r1_anims\pt_ht_execution_victim_sword_02.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 129 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_mt_execution_victim_sword_02" {
	"pete_scripted_r1_anims\pt_mt_execution_victim_sword_02.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 129 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_lt_execution_victim_vanguard" {
	"pete_scripted_r1_anims\pt_lt_execution_victim_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 88 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_mt_execution_victim_vanguard" {
	"pete_scripted_r1_anims\pt_mt_execution_victim_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 88 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_ht_execution_victim_vanguard" {
	"pete_scripted_r1_anims\pt_ht_execution_victim_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 88 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_mt_execution_battery_attacker_vanguard" {
	"pete_scripted_r1_anims\pt_mt_execution_battery_attacker_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 66 "execution_battery_pilot_jump_jets" }
	{ event AE_SV_VSCRIPT_CALLBACK 96 "execution_battery_pilot" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_lt_execution_battery_attacker_vanguard" {
	"pete_scripted_r1_anims\pt_lt_execution_battery_attacker_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 66 "execution_battery_pilot_jump_jets" }
	{ event AE_SV_VSCRIPT_CALLBACK 96 "execution_battery_pilot" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_ht_execution_battery_attacker_vanguard" {
	"pete_scripted_r1_anims\pt_ht_execution_battery_attacker_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 66 "execution_battery_pilot_jump_jets" }
	{ event AE_SV_VSCRIPT_CALLBACK 96 "execution_battery_pilot" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_lt_execution_battery_victim_vanguard" {
	"pete_scripted_r1_anims\pt_lt_execution_battery_victim_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 83 "pink_mist" }
	{ event AE_CL_PLAYSOUND 81 "monarch_battery_execution_bone_crush" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_mt_execution_battery_victim_vanguard" {
	"pete_scripted_r1_anims\pt_mt_execution_battery_victim_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 83 "pink_mist" }
	{ event AE_CL_PLAYSOUND 81 "monarch_battery_execution_bone_crush" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_ht_execution_battery_victim_vanguard" {
	"pete_scripted_r1_anims\pt_ht_execution_battery_victim_vanguard.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 83 "pink_mist" }
	{ event AE_CL_PLAYSOUND 81 "monarch_battery_execution_bone_crush" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_lt_synced_bt_execute_kickshoot_V" {
	"pete_scripted_r1_anims\pt_lt_synced_bt_execute_kickshoot_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 71 "pink_mist" }
	fadein 0.25
	fadeout 0.25
	fps 30
}

$sequence "pt_mt_synced_bt_execute_kickshoot_V" {
	"pete_scripted_r1_anims\pt_mt_synced_bt_execute_kickshoot_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 71 "pink_mist" }
	fadein 0.25
	fadeout 0.25
	fps 30
}

$sequence "pt_ht_synced_bt_execute_kickshoot_V" {
	"pete_scripted_r1_anims\pt_ht_synced_bt_execute_kickshoot_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 71 "pink_mist" }
	fadein 0.25
	fadeout 0.25
	fps 30
}

$sequence "pt_lt_synced_bt_execute_pilot_rip_V" {
	"pete_scripted_r1_anims\pt_lt_synced_bt_execute_pilot_rip_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 106 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_lt_synced_bt_execute_pilot_rip_AI_V" {
	"pete_scripted_r1_anims\pt_lt_synced_bt_execute_pilot_rip_AI_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 100 "pink_mist" }
	fadein 0.4
	fadeout 0.4
	fps 30
}

$sequence "pt_mt_synced_bt_execute_pilot_rip_V" {
	"pete_scripted_r1_anims\pt_mt_synced_bt_execute_pilot_rip_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 106 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_mt_synced_bt_execute_pilot_rip_AI_V" {
	"pete_scripted_r1_anims\pt_mt_synced_bt_execute_pilot_rip_AI_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 100 "pink_mist" }
	fadein 0.4
	fadeout 0.4
	fps 30
}

$sequence "pt_ht_synced_bt_execute_pilot_rip_V" {
	"pete_scripted_r1_anims\pt_ht_synced_bt_execute_pilot_rip_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 106 "pink_mist" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_ht_synced_bt_execute_pilot_rip_AI_V" {
	"pete_scripted_r1_anims\pt_ht_synced_bt_execute_pilot_rip_AI_V.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 100 "pink_mist" }
	fadein 0.4
	fadeout 0.4
	fps 30
}

$sequence "pt_melee_necksnap_rear_attacked" {
	"pete_scripted_r1_anims\pt_melee_necksnap_rear_attacked.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 19 "screen_blackout" }
	{ event AE_SV_VSCRIPT_CALLBACK 19 "mark_for_death" }
	{ event AE_WPN_DROP 30 "" }
	{ event AE_MELEE_KILLED 48 "" }
	{ event AE_RAGDOLL 72 "" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_melee_necksnap_rear_attacked_gun_flip" {
	"pete_scripted_r1_anims\pt_melee_necksnap_rear_attacked_gun_flip.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 19 "screen_blackout" }
	{ event AE_SV_VSCRIPT_CALLBACK 19 "mark_for_death" }
	{ event AE_MELEE_KILLED 48 "" }
	{ event AE_RAGDOLL 72 "" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_melee_necksnap_left_attacked" {
	"pete_scripted_r1_anims\pt_melee_necksnap_left_attacked.smd"
	{ event AE_MELEE_KILLED 19 "" }
	{ event AE_RAGDOLL 65 "" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_melee_necksnap_right_attacked" {
	"pete_scripted_r1_anims\pt_melee_necksnap_right_attacked.smd"
	{ event AE_MELEE_KILLED 19 "" }
	{ event AE_RAGDOLL 65 "" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_melee_necksnap_front_attacked" {
	"pete_scripted_r1_anims\pt_melee_necksnap_front_attacked.smd"
	{ event AE_CL_PLAYSOUND 11 "Weapon_R1Melee.NeckBreak" }
	{ event AE_MELEE_KILLED 40 "" }
	{ event AE_RAGDOLL 82 "" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_melee_necksnap_above_back_attacked" {
	"pete_scripted_r1_anims\pt_melee_necksnap_above_back_attacked.smd"
	{ event AE_WPN_DROP 11 "" }
	{ event AE_MELEE_KILLED 28 "" }
	{ event AE_RAGDOLL 84 "" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_assassin_melee_necksnap_rear_attacked" {
	"pete_scripted_r1_anims\pt_assassin_melee_necksnap_rear_attacked.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 19 "screen_blackout" }
	{ event AE_SV_VSCRIPT_CALLBACK 19 "mark_for_death" }
	{ event AE_WPN_DROP 30 "" }
	{ event AE_MELEE_KILLED 48 "" }
	{ event AE_RAGDOLL 72 "" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_prowler_synced_death_back" {
	"pete_scripted_r1_anims\pt_prowler_synced_death_back.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_prowler_synced_death_front" {
	"pete_scripted_r1_anims\pt_prowler_synced_death_front.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_prowler_synced_death_left" {
	"pete_scripted_r1_anims\pt_prowler_synced_death_left.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_prowler_synced_death_right" {
	"pete_scripted_r1_anims\pt_prowler_synced_death_right.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "pt_vs_prowler_synced_counter" {
	"pete_scripted_r1_anims\pt_vs_prowler_synced_counter.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_synced_prowler_victory_execution" {
	"pete_scripted_r1_anims\pt_synced_prowler_victory_execution.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_sspec_attack_powerdown_hack" {
	"pete_scripted_r1_anims\pt_sspec_attack_powerdown_hack.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_sspec_attack_hack_idle" {
	"pete_scripted_r1_anims\pt_sspec_attack_hack_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_sspec_attack_hack_cancel" {
	"pete_scripted_r1_anims\pt_sspec_attack_hack_cancel.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_trainingpod_doors_close" {
	"pete_scripted_r1_anims\pt_trainingpod_doors_close.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_trainingpod_doors_open" {
	"pete_scripted_r1_anims\pt_trainingpod_doors_open.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_trainingpod_handle_close" {
	"pete_scripted_r1_anims\pt_trainingpod_handle_close.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_trainingpod_handle_open" {
	"pete_scripted_r1_anims\pt_trainingpod_handle_open.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_trainingpod_idle" {
	"pete_scripted_r1_anims\pt_trainingpod_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}
